qpOASES: SQProblem Class Reference
SQProblem Class Reference
Implements the online active set strategy for QPs with varying matrices.
#include <SQProblem.hpp>
Public Member Functions
SQProblem ()
SQProblem (int_t _nV, int_t _nC, HessianType _hessianType=HST_UNKNOWN, BooleanType allocDenseMats=BT_TRUE)
SQProblem (const SQProblem &rhs)
virtual ~SQProblem ()
virtual SQProblem & operator= (const SQProblem &rhs)
returnValue hotstart (SymmetricMatrix *H_new, const real_t *const g_new, Matrix *A_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0)
returnValue hotstart (const real_t *const H_new, const real_t *const g_new, const real_t *const A_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0)
returnValue hotstart (const char *const H_file, const char *const g_file, const char *const A_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0)
returnValue hotstart (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0)
returnValue hotstart (const char *const g_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0)
virtual returnValue reset ()
returnValue init (SymmetricMatrix *_H, const real_t *const _g, Matrix *_A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA, int_t &nWSR, real_t *const cputime=0, const real_t *const xOpt=0, const real_t *const yOpt=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0, const real_t *const _R=0)
returnValue init (const real_t *const _H, const real_t *const _g, const real_t *const _A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA, int_t &nWSR, real_t *const cputime=0, const real_t *const xOpt=0, const real_t *const yOpt=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0, const real_t *const _R=0)
returnValue init (const char *const H_file, const char *const g_file, const char *const A_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, int_t &nWSR, real_t *const cputime=0, const real_t *const xOpt=0, const real_t *const yOpt=0, const Bounds *const guessedBounds=0, const Constraints *const guessedConstraints=0, const char *const R_file=0)
returnValue init (SymmetricMatrix *_H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub, int_t &nWSR, real_t *const cputime=0, const real_t *const xOpt=0, const real_t *const yOpt=0, const Bounds *const guessedBounds=0, const real_t *const _R=0)
returnValue init (const real_t *const _H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub, int_t &nWSR, real_t *const cputime=0, const real_t *const xOpt=0, const real_t *const yOpt=0, const Bounds *const guessedBounds=0, const real_t *const _R=0)
returnValue init (const char *const H_file, const char *const g_file, const char *const lb_file, const char *const ub_file, int_t &nWSR, real_t *const cputime=0, const real_t *const xOpt=0, const real_t *const yOpt=0, const Bounds *const guessedBounds=0, const char *const R_file=0)
returnValue hotstart (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0)
returnValue hotstart (const char *const g_file, const char *const lb_file, const char *const ub_file, int_t &nWSR, real_t *const cputime=0, const Bounds *const guessedBounds=0)
returnValue solveCurrentEQP (const int_t n_rhs, const real_t *g_in, const real_t *lb_in, const real_t *ub_in, const real_t *lbA_in, const real_t *ubA_in, real_t *x_out, real_t *y_out)
virtual returnValue getWorkingSet (real_t *workingSet)
virtual returnValue getWorkingSetBounds (real_t *workingSetB)
virtual returnValue getWorkingSetConstraints (real_t *workingSetC)
returnValue getConstraints (Constraints &_constraints) const
int_t getNC () const
int_t getNEC () const
int_t getNAC () const
int_t getNIAC () const
virtual int_t getNZ () const
virtual returnValue getDualSolution (real_t *const yOpt) const
returnValue setConstraintProduct (ConstraintProduct *const _constraintProduct)
virtual returnValue printProperties ()
returnValue getFreeVariablesFlags (BooleanType *varIsFree)
returnValue writeQpDataIntoMatFile (const char *const filename) const
returnValue writeQpWorkspaceIntoMatFile (const char *const filename)
returnValue getBounds (Bounds &_bounds) const
int_t getNV () const
int_t getNFR () const
int_t getNFX () const
int_t getNFV () const
real_t getObjVal () const
real_t getObjVal (const real_t *const _x) const
returnValue getPrimalSolution (real_t *const xOpt) const
QProblemStatus getStatus () const
BooleanType isInitialised () const
BooleanType isSolved () const
BooleanType isInfeasible () const
BooleanType isUnbounded () const
HessianType getHessianType () const
returnValue setHessianType (HessianType _hessianType)
BooleanType usingRegularisation () const
Options getOptions () const
returnValue setOptions (const Options &_options)
PrintLevel getPrintLevel () const
returnValue setPrintLevel (PrintLevel _printlevel)
uint_t getCount () const
returnValue resetCounter ()
returnValue printOptions () const
Protected Member Functions
virtual returnValue setupNewAuxiliaryQP (SymmetricMatrix *H_new, Matrix *A_new, const real_t *lb_new, const real_t *ub_new, const real_t *lbA_new, const real_t *ubA_new)
virtual returnValue setupNewAuxiliaryQP (const real_t *const H_new, const real_t *const A_new, const real_t *lb_new, const real_t *ub_new, const real_t *lbA_new, const real_t *ubA_new)
returnValue clear ()
returnValue copy (const QProblem &rhs)
returnValue copy (const QProblemB &rhs)
returnValue solveInitialQP (const real_t *const xOpt, const real_t *const yOpt, const Bounds *const guessedBounds, const Constraints *const guessedConstraints, const real_t *const _R, int_t &nWSR, real_t *const cputime)
returnValue solveQP (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t &nWSR, real_t *const cputime, int_t nWSRperformed=0, BooleanType isFirstCall=BT_TRUE)
returnValue solveRegularisedQP (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t &nWSR, real_t *const cputime, int_t nWSRperformed=0, BooleanType isFirstCall=BT_TRUE)
virtual returnValue updateActivitiesForHotstart (const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new)
virtual returnValue setupSubjectToType ()
virtual returnValue setupSubjectToType (const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new)
virtual returnValue setupSubjectToType (const real_t *const lb_new, const real_t *const ub_new)
virtual returnValue computeProjectedCholesky ()
virtual returnValue setupInitialCholesky ()
virtual returnValue setupTQfactorisation ()
returnValue obtainAuxiliaryWorkingSet (const real_t *const xOpt, const real_t *const yOpt, const Bounds *const guessedBounds, const Constraints *const guessedConstraints, Bounds *auxiliaryBounds, Constraints *auxiliaryConstraints) const
returnValue obtainAuxiliaryWorkingSet (const real_t *const xOpt, const real_t *const yOpt, const Bounds *const guessedBounds, Bounds *auxiliaryBounds) const
virtual returnValue setupAuxiliaryWorkingSet (const Bounds *const auxiliaryBounds, const Constraints *const auxiliaryConstraints, BooleanType setupAfresh)
returnValue setupAuxiliaryQPsolution (const real_t *const xOpt, const real_t *const yOpt)
returnValue setupAuxiliaryQPgradient ()
returnValue setupAuxiliaryQPbounds (const Bounds *const auxiliaryBounds, const Constraints *const auxiliaryConstraints, BooleanType useRelaxation)
virtual returnValue addConstraint (int_t number, SubjectToStatus C_status, BooleanType updateCholesky, BooleanType ensureLI=BT_TRUE)
virtual returnValue addConstraint_checkLI (int_t number)
virtual returnValue addConstraint_ensureLI (int_t number, SubjectToStatus C_status)
virtual returnValue addBound (int_t number, SubjectToStatus B_status, BooleanType updateCholesky, BooleanType ensureLI=BT_TRUE)
virtual returnValue addBound_checkLI (int_t number)
virtual returnValue addBound_ensureLI (int_t number, SubjectToStatus B_status)
virtual returnValue removeConstraint (int_t number, BooleanType updateCholesky, BooleanType allowFlipping=BT_FALSE, BooleanType ensureNZC=BT_FALSE)
virtual returnValue removeBound (int_t number, BooleanType updateCholesky, BooleanType allowFlipping=BT_FALSE, BooleanType ensureNZC=BT_FALSE)
returnValue performPlainRatioTest (int_t nIdx, const int_t *const idxList, const real_t *const num, const real_t *const den, real_t epsNum, real_t epsDen, real_t &t, int_t &BC_idx) const
returnValue ensureNonzeroCurvature (BooleanType removeBoundNotConstraint, int_t remIdx, BooleanType &exchangeHappened, BooleanType &addBoundNotConstraint, int_t &addIdx, SubjectToStatus &addStatus)
virtual returnValue backsolveT (const real_t *const b, BooleanType transposed, real_t *const a) const
returnValue determineDataShift (const real_t *const g_new, const real_t *const lbA_new, const real_t *const ubA_new, const real_t *const lb_new, const real_t *const ub_new, real_t *const delta_g, real_t *const delta_lbA, real_t *const delta_ubA, real_t *const delta_lb, real_t *const delta_ub, BooleanType &Delta_bC_isZero, BooleanType &Delta_bB_isZero)
returnValue determineDataShift (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, real_t *const delta_g, real_t *const delta_lb, real_t *const delta_ub, BooleanType &Delta_bB_isZero)
virtual returnValue determineStepDirection (const real_t *const delta_g, const real_t *const delta_lbA, const real_t *const delta_ubA, const real_t *const delta_lb, const real_t *const delta_ub, BooleanType Delta_bC_isZero, BooleanType Delta_bB_isZero, real_t *const delta_xFX, real_t *const delta_xFR, real_t *const delta_yAC, real_t *const delta_yFX)
returnValue performStep (const real_t *const delta_g, const real_t *const delta_lbA, const real_t *const delta_ubA, const real_t *const delta_lb, const real_t *const delta_ub, const real_t *const delta_xFX, const real_t *const delta_xFR, const real_t *const delta_yAC, const real_t *const delta_yFX, int_t &BC_idx, SubjectToStatus &BC_status, BooleanType &BC_isBound)
returnValue changeActiveSet (int_t BC_idx, SubjectToStatus BC_status, BooleanType BC_isBound)
real_t getRelativeHomotopyLength (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new)
real_t getRelativeHomotopyLength (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new)
virtual returnValue performRamping ()
returnValue updateFarBounds (real_t curFarBound, int_t nRamp, const real_t *const lb_new, real_t *const lb_new_far, const real_t *const ub_new, real_t *const ub_new_far, const real_t *const lbA_new, real_t *const lbA_new_far, const real_t *const ubA_new, real_t *const ubA_new_far) const
returnValue updateFarBounds (real_t curFarBound, int_t nRamp, const real_t *const lb_new, real_t *const lb_new_far, const real_t *const ub_new, real_t *const ub_new_far) const
virtual returnValue performDriftCorrection ()
virtual returnValue setupAuxiliaryQP (const Bounds *const guessedBounds, const Constraints *const guessedConstraints)
virtual returnValue setupAuxiliaryQP (const Bounds *const guessedBounds)
BooleanType shallRefactorise (const Bounds *const guessedBounds, const Constraints *const guessedConstraints) const
returnValue setupQPdata (SymmetricMatrix *_H, const real_t *const _g, Matrix *_A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA)
returnValue setupQPdata (const real_t *const _H, const real_t *const _g, const real_t *const _A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA)
returnValue setupQPdata (SymmetricMatrix *_H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub)
returnValue setupQPdata (const real_t *const _H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub)
returnValue setupQPdataFromFile (const char *const H_file, const char *const g_file, const char *const A_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file)
returnValue setupQPdataFromFile (const char *const H_file, const char *const g_file, const char *const lb_file, const char *const ub_file)
returnValue loadQPvectorsFromFile (const char *const g_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, real_t *const g_new, real_t *const lb_new, real_t *const ub_new, real_t *const lbA_new, real_t *const ubA_new) const
returnValue loadQPvectorsFromFile (const char *const g_file, const char *const lb_file, const char *const ub_file, real_t *const g_new, real_t *const lb_new, real_t *const ub_new) const
returnValue printIteration (int_t iter, int_t BC_idx, SubjectToStatus BC_status, BooleanType BC_isBound, real_t homotopyLength, BooleanType isFirstCall=BT_TRUE)
returnValue setA (Matrix *A_new)
returnValue setA (const real_t *const A_new)
returnValue setLBA (const real_t *const lbA_new)
returnValue setLBA (int_t number, real_t value)
returnValue setUBA (const real_t *const ubA_new)
returnValue setUBA (int_t number, real_t value)
returnValue dropInfeasibles (int_t BC_number, SubjectToStatus BC_status, BooleanType BC_isBound, real_t *xiB, real_t *xiC)
returnValue areBoundsConsistent (const real_t *const lb, const real_t *const ub, const real_t *const lbA, const real_t *const ubA) const
returnValue areBoundsConsistent (const real_t *const lb, const real_t *const ub) const
returnValue determineHessianType ()
virtual returnValue computeCholesky ()
virtual returnValue backsolveR (const real_t *const b, BooleanType transposed, real_t *const a) const
virtual returnValue backsolveR (const real_t *const b, BooleanType transposed, BooleanType removingBound, real_t *const a) const
returnValue setInfeasibilityFlag (returnValue returnvalue, BooleanType doThrowError=BT_FALSE)
BooleanType isCPUtimeLimitExceeded (const real_t *const cputime, real_t starttime, int_t nWSR) const
returnValue regulariseHessian ()
returnValue setH (SymmetricMatrix *H_new)
returnValue setH (const real_t *const H_new)
returnValue setG (const real_t *const g_new)
returnValue setLB (const real_t *const lb_new)
returnValue setLB (int_t number, real_t value)
returnValue setUB (const real_t *const ub_new)
returnValue setUB (int_t number, real_t value)
void computeGivens (real_t xold, real_t yold, real_t &xnew, real_t &ynew, real_t &c, real_t &s) const
void applyGivens (real_t c, real_t s, real_t nu, real_t xold, real_t yold, real_t &xnew, real_t &ynew) const
returnValue performRatioTest (int_t nIdx, const int_t *const idxList, const SubjectTo *const subjectTo, const real_t *const num, const real_t *const den, real_t epsNum, real_t epsDen, real_t &t, int_t &BC_idx) const
BooleanType isBlocking (real_t num, real_t den, real_t epsNum, real_t epsDen, real_t &t) const
SymSparseMat * createDiagSparseMat (int_t n, real_t diagVal=1.0)
Protected Attributes
BooleanType freeConstraintMatrix
Matrix * A
real_t * lbA
real_t * ubA
Constraints constraints
real_t * T
real_t * Q
int_t sizeT
real_t * Ax
real_t * Ax_l
real_t * Ax_u
ConstraintProduct * constraintProduct
real_t * tempA
real_t * tempB
real_t * ZFR_delta_xFRz
real_t * delta_xFRy
real_t * delta_xFRz
real_t * delta_yAC_TMP
real_t * tempC
BooleanType freeHessian
SymmetricMatrix * H
real_t * g
real_t * lb
real_t * ub
Bounds bounds
real_t * R
BooleanType haveCholesky
real_t * x
real_t * y
real_t tau
QProblemStatus status
BooleanType infeasible
BooleanType unbounded
HessianType hessianType
real_t regVal
uint_t count
real_t * delta_xFR_TMP
real_t ramp0
real_t ramp1
int_t rampOffset
Options options
Flipper flipper
TabularOutput tabularOutput
Friends
class SolutionAnalysis
Detailed Description
A class for setting up and solving quadratic programs with varying QP matrices. The main feature is the possibily to use the newly developed online active set strategy for parametric quadratic programming.
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.2
Date:
2007-2017
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES SQProblem::SQProblem ()
Default constructor.
SQProblem::SQProblem (int_t _nV, int_t _nC, HessianType _hessianType = HST_UNKNOWN, BooleanType allocDenseMats = BT_TRUE)
Constructor which takes the QP dimension and Hessian type information. If the Hessian is the zero (i.e. HST_ZERO) or the identity matrix (i.e. HST_IDENTITY), respectively, no memory is allocated for it and a NULL pointer can be passed for it to the init() functions.
Parameters:
_nV Number of variables.
_nC Number of constraints.
_hessianType Type of Hessian matrix.
allocDenseMats Enable allocation of dense matrices.
SQProblem::SQProblem (const SQProblem & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
SQProblem::~SQProblem () [virtual]
Destructor.
Member Function Documentation
returnValue QProblem::addBound (int_t number, SubjectToStatus B_status, BooleanType updateCholesky, BooleanType ensureLI = BT_TRUE) [protected, virtual, inherited]
Adds a bound to active set.
Returns:
SUCCESSFUL_RETURN
RET_ADDBOUND_FAILED
RET_ADDBOUND_FAILED_INFEASIBILITY
RET_ENSURELI_FAILED
Parameters:
number Number of bound to be added to active set.
B_status Status of new active bound.
updateCholesky Flag indicating if Cholesky decomposition shall be updated.
ensureLI Ensure linear independence by exchange rules by default.
Reimplemented in SQProblemSchur.
References QProblem::addBound_ensureLI(), QProblemB::applyGivens(), QProblemB::bounds, BT_TRUE, QProblemB::computeGivens(), Bounds::getFree(), Indexlist::getLastNumber(), QProblem::getNAC(), QProblemB::getNFR(), Indexlist::getNumberArray(), Bounds::getNUV(), QProblemB::getNV(), QProblem::getNZ(), SubjectTo::getStatus(), QProblemB::getStatus(), QProblemB::hessianType, HST_IDENTITY, HST_ZERO, TabularOutput::idxAddB, Bounds::moveFreeToFixed(), QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_NOTINITIALISED, QPS_SOLVED, QQ, real_t, RET_ADDBOUND_FAILED, RET_ADDBOUND_FAILED_INFEASIBILITY, RET_ALL_BOUNDS_ACTIVE, RET_BOUND_ALREADY_ACTIVE, RET_ENSURELI_DROPPED, RET_ENSURELI_FAILED, RET_ENSURELI_FAILED_CYCLING, RET_ENSURELI_FAILED_NOINDEX, RET_LI_RESOLVED, RET_UNKNOWN_BUG, RR, QProblem::sizeT, ST_INACTIVE, SUCCESSFUL_RETURN, Bounds::swapFree(), QProblemB::tabularOutput, THROWERROR, and TT.
Referenced by QProblem::changeActiveSet(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::setupAuxiliaryWorkingSet(), and QProblem::updateActivitiesForHotstart().
returnValue QProblem::addBound_checkLI (int_t number) [protected, virtual, inherited]
Checks if new active bound to be added is linearly dependent from from row of the active constraints matrix.
Returns:
RET_LINEARLY_DEPENDENT
RET_LINEARLY_INDEPENDENT
Parameters:
number Number of bound to be added to active set.
Reimplemented in SQProblemSchur.
References BT_FALSE, QProblem::determineStepDirection(), Options::enableFullLITests, Options::epsLITests, getAbs(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), QProblemB::getNV(), QProblem::getNZ(), QProblemB::options, QQ, real_t, RET_LINEARLY_DEPENDENT, RET_LINEARLY_INDEPENDENT, SUCCESSFUL_RETURN, and THROWINFO.
Referenced by QProblem::addBound_ensureLI(), QProblem::setupAuxiliaryWorkingSet(), and QProblem::updateActivitiesForHotstart().
returnValue QProblem::addBound_ensureLI (int_t number, SubjectToStatus B_status) [protected, virtual, inherited]
Ensures linear independence of constraint matrix when a new bound is added. To this end a bound or constraint is removed simultaneously if necessary.
Returns:
SUCCESSFUL_RETURN
RET_LI_RESOLVED
RET_ENSURELI_FAILED
RET_ENSURELI_FAILED_TQ
RET_ENSURELI_FAILED_NOINDEX
RET_REMOVE_FROM_ACTIVESET
Parameters:
number Number of bound to be added to active set.
B_status Status of new active bound.
Reimplemented in SQProblemSchur.
References __FILE__, __FUNC__, __LINE__, QProblem::A, QProblem::addBound_checkLI(), QProblem::backsolveT(), QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, QProblem::dropInfeasibles(), Options::enableDropInfeasibles, Options::epsDen, Options::epsNum, TabularOutput::excRemB, TabularOutput::excRemC, Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), getGlobalMessageHandler(), QProblem::getNAC(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), MAX_STRING_LENGTH, Options::maxDualJump, QProblemB::options, QProblemB::performRatioTest(), QQ, real_t, QProblem::removeBound(), QProblem::removeConstraint(), RET_ENSURELI_FAILED, RET_ENSURELI_FAILED_NOINDEX, RET_ENSURELI_FAILED_TQ, RET_INDEXLIST_CORRUPTED, RET_LI_RESOLVED, RET_LINEARLY_INDEPENDENT, RET_REMOVE_FROM_ACTIVESET, RET_REMOVE_FROM_ACTIVESET_FAILED, QProblemB::setInfeasibilityFlag(), ST_LOWER, SUCCESSFUL_RETURN, QProblemB::tabularOutput, THROWERROR, MessageHandling::throwInfo(), Matrix::transTimes(), VS_VISIBLE, and QProblemB::y.
Referenced by QProblem::addBound().
returnValue QProblem::addConstraint (int_t number, SubjectToStatus C_status, BooleanType updateCholesky, BooleanType ensureLI = BT_TRUE) [protected, virtual, inherited]
Adds a constraint to active set.
Returns:
SUCCESSFUL_RETURN
RET_ADDCONSTRAINT_FAILED
RET_ADDCONSTRAINT_FAILED_INFEASIBILITY
RET_ENSURELI_FAILED
Parameters:
number Number of constraint to be added to active set.
C_status Status of new active constraint.
updateCholesky Flag indicating if Cholesky decomposition shall be updated.
ensureLI Ensure linear independence by exchange rules by default.
Reimplemented in SQProblemSchur.
References QProblem::A, QProblem::addConstraint_ensureLI(), QProblemB::applyGivens(), QProblemB::bounds, BT_TRUE, QProblemB::computeGivens(), QProblem::constraints, Bounds::getFree(), QProblem::getNAC(), Constraints::getNC(), QProblemB::getNFR(), Constraints::getNUC(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), Matrix::getRow(), SubjectTo::getStatus(), QProblemB::getStatus(), QProblemB::hessianType, HST_IDENTITY, HST_ZERO, TabularOutput::idxAddC, Constraints::moveInactiveToActive(), QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_NOTINITIALISED, QPS_SOLVED, QQ, real_t, RET_ADDCONSTRAINT_FAILED, RET_ADDCONSTRAINT_FAILED_INFEASIBILITY, RET_ALL_CONSTRAINTS_ACTIVE, RET_CONSTRAINT_ALREADY_ACTIVE, RET_ENSURELI_DROPPED, RET_ENSURELI_FAILED, RET_ENSURELI_FAILED_CYCLING, RET_ENSURELI_FAILED_NOINDEX, RET_LI_RESOLVED, RET_UNKNOWN_BUG, RR, QProblem::sizeT, ST_INACTIVE, SUCCESSFUL_RETURN, QProblemB::tabularOutput, THROWERROR, and TT.
Referenced by QProblem::changeActiveSet(), QProblem::removeBound(), QProblem::removeConstraint(), and QProblem::setupAuxiliaryWorkingSet().
returnValue QProblem::addConstraint_checkLI (int_t number) [protected, virtual, inherited]
Checks if new active constraint to be added is linearly dependent from from row of the active constraints matrix.
Returns:
RET_LINEARLY_DEPENDENT
RET_LINEARLY_INDEPENDENT
RET_INDEXLIST_CORRUPTED
Parameters:
number Number of constraint to be added to active set.
Reimplemented in SQProblemSchur.
References QProblem::A, QProblemB::bounds, BT_FALSE, QProblem::constraints, QProblem::determineStepDirection(), Options::enableFullLITests, Options::epsLITests, getAbs(), Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), Constraints::getInactive(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), Matrix::getRow(), QProblemB::options, QQ, real_t, RET_LINEARLY_DEPENDENT, RET_LINEARLY_INDEPENDENT, SUCCESSFUL_RETURN, and THROWINFO.
Referenced by QProblem::addConstraint_ensureLI(), and QProblem::setupAuxiliaryWorkingSet().
returnValue QProblem::addConstraint_ensureLI (int_t number, SubjectToStatus C_status) [protected, virtual, inherited]
Ensures linear independence of constraint matrix when a new constraint is added. To this end a bound or constraint is removed simultaneously if necessary.
Returns:
SUCCESSFUL_RETURN
RET_LI_RESOLVED
RET_ENSURELI_FAILED
RET_ENSURELI_FAILED_TQ
RET_ENSURELI_FAILED_NOINDEX
RET_REMOVE_FROM_ACTIVESET
Parameters:
number Number of constraint to be added to active set.
C_status Status of new active bound.
Reimplemented in SQProblemSchur.
References __FILE__, __FUNC__, __LINE__, QProblem::A, QProblem::addConstraint_checkLI(), QProblem::backsolveT(), QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, QProblem::dropInfeasibles(), Options::enableDropInfeasibles, Options::epsDen, Options::epsNum, TabularOutput::excRemB, TabularOutput::excRemC, Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), getGlobalMessageHandler(), QProblem::getNAC(), QProblemB::getNFR(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), Matrix::getRow(), MAX_STRING_LENGTH, Options::maxDualJump, QProblemB::options, QProblemB::performRatioTest(), QQ, real_t, QProblem::removeBound(), QProblem::removeConstraint(), RET_ENSURELI_FAILED, RET_ENSURELI_FAILED_NOINDEX, RET_ENSURELI_FAILED_TQ, RET_INDEXLIST_CORRUPTED, RET_LI_RESOLVED, RET_LINEARLY_INDEPENDENT, RET_REMOVE_FROM_ACTIVESET, RET_REMOVE_FROM_ACTIVESET_FAILED, QProblemB::setInfeasibilityFlag(), ST_LOWER, SUCCESSFUL_RETURN, QProblemB::tabularOutput, THROWERROR, MessageHandling::throwInfo(), Matrix::transTimes(), VS_VISIBLE, and QProblemB::y.
Referenced by QProblem::addConstraint().
void QProblemB::applyGivens (real_t c, real_t s, real_t nu, real_t xold, real_t yold, real_t & xnew, real_t & ynew) const [inline, protected, inherited]
Applies Givens matrix determined by c and s (cf. computeGivens).
Returns:
SUCCESSFUL_RETURN
Parameters:
c Cosine entry of Givens matrix.
s Sine entry of Givens matrix.
nu Further factor: s/(1+c).
xold Matrix entry to be transformed corresponding to the normalised entry of the original matrix.
yold Matrix entry to be transformed corresponding to the annihilated entry of the original matrix.
xnew Output: Transformed matrix entry corresponding to the normalised entry of the original matrix.
ynew Output: Transformed matrix entry corresponding to the annihilated entry of the original matrix.
Referenced by QProblem::addBound(), QProblemB::addBound(), QProblem::addConstraint(), SQProblemSchur::calcDetSchur(), QProblem::removeBound(), QProblem::removeConstraint(), and SQProblemSchur::updateSchurQR().
returnValue QProblemB::areBoundsConsistent (const real_t *const lb, const real_t *const ub) const [protected, inherited]
Decides if lower bounds are smaller than upper bounds
Returns:
SUCCESSFUL_RETURN
RET_QP_INFEASIBLE
Parameters:
lb Vector of lower bounds
ub Vector of upper bounds
References EPS, QProblemB::getNV(), RET_QP_INFEASIBLE, and SUCCESSFUL_RETURN.
Referenced by QProblem::areBoundsConsistent(), and QProblemB::hotstart().
returnValue QProblem::areBoundsConsistent (const real_t *const lb, const real_t *const ub, const real_t *const lbA, const real_t *const ubA) const [protected, inherited]
Decides if lower bounds are smaller than upper bounds
Returns:
SUCCESSFUL_RETURN
RET_QP_INFEASIBLE
Parameters:
lb Vector of lower bounds
ub Vector of upper bounds
lbA Vector of lower constraints
ubA Vector of upper constraints
References QProblemB::areBoundsConsistent(), EPS, QProblem::getNC(), RET_QP_INFEASIBLE, and SUCCESSFUL_RETURN.
Referenced by QProblem::hotstart().
returnValue QProblemB::backsolveR (const real_t *const b, BooleanType transposed, real_t *const a) const [protected, virtual, inherited]
Solves the system Ra = b or R^Ta = b where R is an upper triangular matrix.
Returns:
SUCCESSFUL_RETURN
RET_DIV_BY_ZERO
Parameters:
b Right hand side vector.
transposed Indicates if the transposed system shall be solved.
a Output: Solution vector
Reimplemented in SQProblemSchur.
References BT_FALSE.
Referenced by QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblem::removeBound(), QProblemB::removeBound(), and QProblem::removeConstraint().
returnValue QProblemB::backsolveR (const real_t *const b, BooleanType transposed, BooleanType removingBound, real_t *const a) const [protected, virtual, inherited]
Solves the system Ra = b or R^Ta = b where R is an upper triangular matrix.
Special variant for the case that this function is called from within "removeBound()".
Returns:
SUCCESSFUL_RETURN
RET_DIV_BY_ZERO
Parameters:
b Right hand side vector.
transposed Indicates if the transposed system shall be solved.
removingBound Indicates if function is called from "removeBound()".
a Output: Solution vector
Reimplemented in SQProblemSchur.
References BT_FALSE, BT_TRUE, getAbs(), QProblemB::getNV(), QProblemB::getNZ(), real_t, RET_DIV_BY_ZERO, RR, SUCCESSFUL_RETURN, THROWERROR, and ZERO.
returnValue QProblem::backsolveT (const real_t *const b, BooleanType transposed, real_t *const a) const [protected, virtual, inherited]
Solves the system Ta = b or T^Ta = b where T is a reverse upper triangular matrix.
Returns:
SUCCESSFUL_RETURN
RET_DIV_BY_ZERO
Parameters:
b Right hand side vector.
transposed Indicates if the transposed system shall be solved.
a Output: Solution vector
Reimplemented in SQProblemSchur.
References BT_FALSE, EPS, getAbs(), QProblem::getNAC(), real_t, RET_DIV_BY_ZERO, QProblem::sizeT, SUCCESSFUL_RETURN, THROWERROR, and TT.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), and QProblem::determineStepDirection().
returnValue QProblem::changeActiveSet (int_t BC_idx, SubjectToStatus BC_status, BooleanType BC_isBound) [protected, inherited]
Updates the active set.
Returns:
SUCCESSFUL_RETURN
RET_REMOVE_FROM_ACTIVESET_FAILED
RET_ADD_TO_ACTIVESET_FAILED
Parameters:
BC_idx Index of blocking constraint.
BC_status Status of blocking constraint.
BC_isBound Indicates if blocking constraint is a bound.
References __FILE__, __FUNC__, __LINE__, QProblem::addBound(), QProblem::addConstraint(), BT_TRUE, Options::enableNZCTests, getGlobalMessageHandler(), QProblemB::getNV(), MAX_STRING_LENGTH, QProblemB::options, QProblem::removeBound(), QProblem::removeConstraint(), RET_ADD_TO_ACTIVESET, RET_ADD_TO_ACTIVESET_FAILED, RET_ADDBOUND_FAILED_INFEASIBILITY, RET_ADDCONSTRAINT_FAILED_INFEASIBILITY, RET_REMOVE_FROM_ACTIVESET, RET_REMOVE_FROM_ACTIVESET_FAILED, ST_INACTIVE, ST_LOWER, ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, MessageHandling::throwInfo(), VS_VISIBLE, and QProblemB::y.
Referenced by QProblem::solveQP().
returnValue QProblem::clear () [protected, inherited]
Frees all allocated memory.
Returns:
SUCCESSFUL_RETURN
Reimplemented from QProblemB.
Reimplemented in SQProblemSchur.
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, BT_TRUE, QProblem::delta_xFRy, QProblem::delta_xFRz, QProblem::delta_yAC_TMP, QProblem::freeConstraintMatrix, QProblem::lbA, QProblem::Q, SUCCESSFUL_RETURN, QProblem::T, QProblem::tempA, QProblem::tempB, QProblem::tempC, QProblem::ubA, and QProblem::ZFR_delta_xFRz.
Referenced by QProblem::operator=(), and QProblem::~QProblem().
returnValue QProblemB::computeCholesky () [protected, virtual, inherited]
Computes the Cholesky decomposition of the (simply projected) Hessian (i.e. R^T*R = Z^T*H*Z). It only works in the case where Z is a simple projection matrix! Note: If Hessian turns out not to be positive definite, the Hessian type is set to HST_SEMIDEF accordingly.
Returns:
SUCCESSFUL_RETURN
RET_HESSIAN_NOT_SPD
RET_INDEXLIST_CORRUPTED
References QProblemB::bounds, BT_TRUE, Options::epsRegularisation, getAbs(), Matrix::getCol(), Bounds::getFree(), getMin(), QProblemB::getNFR(), Indexlist::getNumberArray(), QProblemB::getNV(), getSqrt(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_SEMIDEF, HST_ZERO, QProblemB::options, POTRF, QProblemB::R, QProblemB::regVal, RET_CHOLESKY_OF_ZERO_HESSIAN, RET_HESSIAN_NOT_SPD, RR, SUCCESSFUL_RETURN, THROWERROR, and QProblemB::usingRegularisation().
Referenced by QProblem::computeProjectedCholesky(), QProblemB::setupAuxiliaryQP(), QProblemB::setupInitialCholesky(), and QProblemB::solveQP().
void QProblemB::computeGivens (real_t xold, real_t yold, real_t & xnew, real_t & ynew, real_t & c, real_t & s) const [inline, protected, inherited]
Computes parameters for the Givens matrix G for which [x,y]*G = [z,0]
Returns:
SUCCESSFUL_RETURN
Parameters:
xold Matrix entry to be normalised.
yold Matrix entry to be annihilated.
xnew Output: Normalised matrix entry.
ynew Output: Annihilated matrix entry.
c Output: Cosine entry of Givens matrix.
s Output: Sine entry of Givens matrix.
References BT_TRUE, getAbs(), getSqrt(), isZero(), and real_t.
Referenced by QProblem::addBound(), QProblemB::addBound(), QProblem::addConstraint(), SQProblemSchur::calcDetSchur(), QProblem::removeBound(), QProblem::removeConstraint(), and SQProblemSchur::updateSchurQR().
returnValue QProblem::computeProjectedCholesky () [protected, virtual, inherited]
Computes the Cholesky decomposition of the projected Hessian (i.e. R^T*R = Z^T*H*Z). Note: If Hessian turns out not to be positive definite, the Hessian type is set to HST_SEMIDEF accordingly.
Returns:
SUCCESSFUL_RETURN
RET_HESSIAN_NOT_SPD
RET_INDEXLIST_CORRUPTED
Reimplemented in SQProblemSchur.
References SymmetricMatrix::bilinear(), SymSparseMat::bilinear(), QProblemB::bounds, BT_TRUE, QProblemB::computeCholesky(), QProblem::constraints, QProblemB::createDiagSparseMat(), Options::epsRegularisation, getAbs(), Constraints::getActive(), Matrix::getCol(), Bounds::getFree(), getMin(), QProblem::getNAC(), QProblemB::getNFR(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), getSqrt(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_SEMIDEF, HST_ZERO, QProblemB::options, POTRF, QProblem::Q, QQ, QProblemB::R, QProblemB::regVal, RET_HESSIAN_NOT_SPD, RET_UNKNOWN_BUG, RR, SUCCESSFUL_RETURN, THROWERROR, and QProblemB::usingRegularisation().
Referenced by QProblem::setupAuxiliaryQP(), QProblem::setupInitialCholesky(), setupNewAuxiliaryQP(), and QProblem::solveQP().
returnValue QProblem::copy (const QProblem & rhs) [protected, inherited]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, BT_TRUE, QProblem::constraintProduct, QProblem::constraints, QProblem::delta_xFRy, QProblem::delta_xFRz, QProblem::delta_yAC_TMP, Matrix::duplicate(), QProblem::freeConstraintMatrix, QProblem::getNC(), QProblemB::getNV(), QProblem::lbA, QProblem::Q, real_t, QProblem::setLBA(), QProblem::setUBA(), QProblem::sizeT, SUCCESSFUL_RETURN, QProblem::T, QProblem::tempA, QProblem::tempB, QProblem::tempC, QProblem::ubA, QProblemB::y, and QProblem::ZFR_delta_xFRz.
Referenced by QProblem::operator=(), and QProblem::QProblem().
returnValue QProblemB::copy (const QProblemB & rhs) [protected, inherited]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References QProblemB::bounds, BT_TRUE, QProblemB::count, QProblemB::delta_xFR_TMP, SymmetricMatrix::duplicateSym(), QProblemB::flipper, QProblemB::freeHessian, QProblemB::g, QProblemB::getNV(), QProblemB::H, QProblemB::haveCholesky, QProblemB::hessianType, QProblemB::infeasible, QProblemB::lb, QProblemB::options, Options::printLevel, QProblemB::R, QProblemB::ramp0, QProblemB::ramp1, QProblemB::rampOffset, real_t, QProblemB::regVal, QProblemB::setG(), QProblemB::setLB(), QProblemB::setPrintLevel(), QProblemB::setUB(), QProblemB::status, SUCCESSFUL_RETURN, QProblemB::tau, QProblemB::ub, QProblemB::unbounded, QProblemB::x, and QProblemB::y.
Referenced by QProblemB::operator=(), and QProblemB::QProblemB().
SymSparseMat * QProblemB::createDiagSparseMat (int_t n, real_t diagVal = 1.0) [protected, inherited]
Creates a sparse diagonal (square-)matrix which is a given multiple of the identity matrix.
Returns:
Diagonal matrix
Parameters:
n Row/column dimension of matrix to be created.
diagVal Value of all diagonal entries.
References SparseMatrix::createDiagInfo(), Matrix::doFreeMemory(), and real_t.
Referenced by QProblem::computeProjectedCholesky().
returnValue QProblemB::determineDataShift (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, real_t *const delta_g, real_t *const delta_lb, real_t *const delta_ub, BooleanType & Delta_bB_isZero) [protected, inherited]
Determines step direction of the shift of the QP data.
Returns:
SUCCESSFUL_RETURN
Parameters:
g_new New gradient vector.
lb_new New lower bounds.
ub_new New upper bounds.
delta_g Output: Step direction of gradient vector.
delta_lb Output: Step direction of lower bounds.
delta_ub Output: Step direction of upper bounds.
Delta_bB_isZero Output: Indicates if active bounds are to be shifted.
References QProblemB::bounds, BT_FALSE, BT_TRUE, EPS, QProblemB::g, getAbs(), Bounds::getFixed(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), INFTY, QProblemB::lb, SUCCESSFUL_RETURN, and QProblemB::ub.
Referenced by QProblemB::solveQP().
returnValue QProblem::determineDataShift (const real_t *const g_new, const real_t *const lbA_new, const real_t *const ubA_new, const real_t *const lb_new, const real_t *const ub_new, real_t *const delta_g, real_t *const delta_lbA, real_t *const delta_ubA, real_t *const delta_lb, real_t *const delta_ub, BooleanType & Delta_bC_isZero, BooleanType & Delta_bB_isZero) [protected, inherited]
Determines step direction of the shift of the QP data.
Returns:
SUCCESSFUL_RETURN
Parameters:
g_new New gradient vector.
lbA_new New lower constraints' bounds.
ubA_new New upper constraints' bounds.
lb_new New lower bounds.
ub_new New upper bounds.
delta_g Output: Step direction of gradient vector.
delta_lbA Output: Step direction of lower constraints' bounds.
delta_ubA Output: Step direction of upper constraints' bounds.
delta_lb Output: Step direction of lower bounds.
delta_ub Output: Step direction of upper bounds.
Delta_bC_isZero Output: Indicates if active constraints' bounds are to be shifted.
Delta_bB_isZero Output: Indicates if active bounds are to be shifted.
References QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, EPS, getAbs(), Constraints::getActive(), Bounds::getFixed(), QProblem::getNAC(), QProblem::getNC(), Indexlist::getNumberArray(), INFTY, QProblem::lbA, SUCCESSFUL_RETURN, and QProblem::ubA.
Referenced by QProblem::solveQP().
returnValue QProblemB::determineHessianType () [protected, inherited]
If Hessian type has been set by the user, nothing is done. Otherwise the Hessian type is set to HST_IDENTITY, HST_ZERO, or HST_POSDEF (default), respectively.
Returns:
SUCCESSFUL_RETURN
RET_HESSIAN_INDEFINITE
References BT_FALSE, BT_TRUE, Matrix::diag(), Options::enableFlippingBounds, Options::enableRegularisation, EPS, getAbs(), QProblemB::getNV(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_INDEF, HST_POSDEF, HST_POSDEF_NULLSPACE, HST_SEMIDEF, HST_ZERO, INFTY, Matrix::isDiag(), isZero(), Options::numRegularisationSteps, QProblemB::options, real_t, RET_DIAGONAL_NOT_INITIALISED, RET_HESSIAN_INDEFINITE, RET_ZERO_HESSIAN_ASSUMED, SUCCESSFUL_RETURN, THROWERROR, THROWINFO, and ZERO.
Referenced by SQProblemSchur::setupAuxiliaryQP(), setupNewAuxiliaryQP(), QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
returnValue QProblem::determineStepDirection (const real_t *const delta_g, const real_t *const delta_lbA, const real_t *const delta_ubA, const real_t *const delta_lb, const real_t *const delta_ub, BooleanType Delta_bC_isZero, BooleanType Delta_bB_isZero, real_t *const delta_xFX, real_t *const delta_xFR, real_t *const delta_yAC, real_t *const delta_yFX) [protected, virtual, inherited]
Determines step direction of the homotopy path.
Returns:
SUCCESSFUL_RETURN
RET_STEPDIRECTION_FAILED_TQ
RET_STEPDIRECTION_FAILED_CHOLESKY
Parameters:
delta_g Step direction of gradient vector.
delta_lbA Step direction of lower constraints' bounds.
delta_ubA Step direction of upper constraints' bounds.
delta_lb Step direction of lower bounds.
delta_ub Step direction of upper bounds.
Delta_bC_isZero Indicates if active constraints' bounds are to be shifted.
Delta_bB_isZero Indicates if active bounds are to be shifted.
delta_xFX Output: Primal homotopy step direction of fixed variables.
delta_xFR Output: Primal homotopy step direction of free variables.
delta_yAC Output: Dual homotopy step direction of active constraints' multiplier.
delta_yFX Output: Dual homotopy step direction of fixed variables' multiplier.
Reimplemented in SQProblemSchur.
References QProblem::A, QProblemB::backsolveR(), QProblem::backsolveT(), QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, QProblemB::delta_xFR_TMP, QProblem::delta_xFRy, QProblem::delta_xFRz, QProblem::delta_yAC_TMP, Options::epsIterRef, getAbs(), Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), QProblem::getNAC(), QProblemB::getNFR(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), SubjectTo::getStatus(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_ZERO, Options::numRefinementSteps, QProblemB::options, QQ, real_t, QProblemB::regVal, RET_STEPDIRECTION_FAILED_CHOLESKY, RET_STEPDIRECTION_FAILED_TQ, RET_UNKNOWN_BUG, ST_LOWER, SUCCESSFUL_RETURN, QProblem::tempA, QProblem::tempB, THROWERROR, Matrix::times(), Matrix::transTimes(), QProblemB::usingRegularisation(), and QProblem::ZFR_delta_xFRz.
Referenced by QProblem::addBound_checkLI(), QProblem::addConstraint_checkLI(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getVarianceCovariance(), QProblem::solveCurrentEQP(), and QProblem::solveQP().
returnValue QProblem::dropInfeasibles (int_t BC_number, SubjectToStatus BC_status, BooleanType BC_isBound, real_t * xiB, real_t * xiC) [protected, inherited]
Drops the blocking bound/constraint that led to infeasibility, or finds another bound/constraint to drop according to drop priorities.
Returns:
SUCCESSFUL_RETURN
Parameters:
BC_number Number of the bound or constraint to be added.
BC_status New status of the bound or constraint to be added.
BC_isBound Whether a bound or a constraint is to be added.
xiB (not yet documented)
xiC (not yet documented)
References QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, Options::dropBoundPriority, Options::dropEqConPriority, Options::dropIneqConPriority, Options::epsDen, getAbs(), Constraints::getActive(), Bounds::getFixed(), QProblem::getNAC(), QProblemB::getNFX(), Indexlist::getNumberArray(), SubjectTo::getStatus(), SubjectTo::getType(), QProblemB::options, QProblem::removeBound(), QProblem::removeConstraint(), RET_ENSURELI_DROPPED, SubjectTo::setStatus(), ST_BOUNDED, ST_EQUALITY, ST_INFEASIBLE_LOWER, ST_INFEASIBLE_UPPER, ST_LOWER, and SUCCESSFUL_RETURN.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint_ensureLI(), and QProblem::addConstraint_ensureLI().
returnValue QProblem::ensureNonzeroCurvature (BooleanType removeBoundNotConstraint, int_t remIdx, BooleanType & exchangeHappened, BooleanType & addBoundNotConstraint, int_t & addIdx, SubjectToStatus & addStatus) [protected, inherited]
Ensure non-zero curvature by primal jump.
Returns:
SUCCESSFUL_RETURN
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
Parameters:
removeBoundNotConstraint SubjectTo to be removed is a bound.
remIdx Index of bound/constraint to be removed.
exchangeHappened Output: Exchange was necessary to ensure.
addBoundNotConstraint SubjectTo to be added is a bound.
addIdx Index of bound/constraint to be added.
addStatus Status of bound/constraint to be added.
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, QProblem::determineStepDirection(), Options::epsDen, Options::epsNum, Options::epsNZCTests, getAbs(), Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), Constraints::getInactive(), getMax(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), QProblem::getNIAC(), Indexlist::getNumberArray(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::lb, QProblem::lbA, Options::maxPrimalJump, QProblemB::options, QProblem::performPlainRatioTest(), real_t, RET_HOTSTART_STOPPED_UNBOUNDEDNESS, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, Matrix::times(), QProblemB::ub, QProblem::ubA, QProblemB::unbounded, and QProblemB::x.
Referenced by SQProblemSchur::removeBound(), QProblem::removeBound(), SQProblemSchur::removeConstraint(), and QProblem::removeConstraint().
BEGIN_NAMESPACE_QPOASES returnValue QProblemB::getBounds (Bounds & _bounds) const [inline, inherited]
Returns current bounds object of the QP (deep copy).
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
Parameters:
_bounds Output: Bounds object.
References QProblemB::bounds, QProblemB::getNV(), RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints().
BEGIN_NAMESPACE_QPOASES returnValue QProblem::getConstraints (Constraints & _constraints) const [inline, inherited]
Returns current constraints object of the QP (deep copy).
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
Parameters:
_constraints Output: Constraints object.
References QProblem::constraints, QProblemB::getNV(), RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
uint_t QProblemB::getCount () const [inline, inherited]
Returns the current number of QP problems solved.
Returns:
Number of QP problems solved.
References QProblemB::count.
returnValue QProblem::getDualSolution (real_t *const yOpt) const [virtual, inherited]
Returns the dual solution vector (deep copy).
Returns:
SUCCESSFUL_RETURN
RET_QP_NOT_SOLVED
Parameters:
yOpt Output: Dual solution vector (if QP has been solved).
Reimplemented from QProblemB.
References QProblem::getNC(), QProblemB::getNV(), QProblemB::getStatus(), QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_SOLVED, RET_QP_NOT_SOLVED, SUCCESSFUL_RETURN, and QProblemB::y.
Referenced by main(), and solveOqpBenchmark().
returnValue QProblem::getFreeVariablesFlags (BooleanType * varIsFree) [inherited]
Set the incoming array to true for each variable entry that is in the set of free variables
References QProblemB::bounds, BT_FALSE, BT_TRUE, Bounds::getFree(), QProblemB::getNFR(), Indexlist::getNumberArray(), QProblemB::getNV(), and SUCCESSFUL_RETURN.
HessianType QProblemB::getHessianType () const [inline, inherited]
Returns Hessian type flag (type is not determined due to this call!).
Returns:
Hessian type.
References QProblemB::hessianType.
Referenced by SolutionAnalysis::getKktViolation().
int_t QProblem::getNAC () const [inline, inherited]
Returns the number of active constraints.
Returns:
Number of active constraints.
References QProblem::constraints, and Constraints::getNAC().
Referenced by QProblem::addBound(), SQProblemSchur::addBound_checkLI(), QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint(), QProblem::addConstraint(), SQProblemSchur::addConstraint_checkLI(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::backsolveT(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblem::computeProjectedCholesky(), SQProblemSchur::correctInertia(), QProblem::determineDataShift(), QProblem::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), QProblem::getNZ(), SolutionAnalysis::getVarianceCovariance(), QProblem::performStep(), QProblem::printIteration(), SQProblemSchur::removeBound(), QProblem::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), SQProblemSchur::repairSingularWorkingSet(), SQProblemSchur::resetSchurComplement(), SQProblemSchur::setupAuxiliaryQP(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::solveCurrentEQP(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t QProblem::getNC () const [inline, inherited]
Returns the number of constraints.
Returns:
Number of constraints.
References QProblem::constraints, and Constraints::getNC().
Referenced by QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), QProblem::areBoundsConsistent(), QProblem::copy(), QProblem::determineDataShift(), QProblem::ensureNonzeroCurvature(), QProblem::getDualSolution(), SolutionAnalysis::getKktViolation(), QProblem::getRelativeHomotopyLength(), SolutionAnalysis::getVarianceCovariance(), QProblem::getWorkingSetConstraints(), hotstart(), QProblem::hotstart(), QProblem::init(), QProblem::loadQPvectorsFromFile(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::printIteration(), QProblem::printProperties(), QProblem::reset(), QProblem::setA(), QProblem::setLBA(), QProblem::setUBA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::setupAuxiliaryWorkingSet(), setupNewAuxiliaryQP(), QProblem::setupQPdata(), QProblem::setupQPdataFromFile(), QProblem::setupSubjectToType(), QProblem::shallRefactorise(), QProblem::solveCurrentEQP(), QProblem::solveInitialQP(), QProblem::solveQP(), QProblem::updateFarBounds(), QProblem::writeQpDataIntoMatFile(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t QProblem::getNEC () const [inline, inherited]
Returns the number of (implicitly defined) equality constraints.
Returns:
Number of (implicitly defined) equality constraints.
References QProblem::constraints, and Constraints::getNEC().
Referenced by QProblem::printProperties().
int_t QProblemB::getNFR () const [inline, inherited]
Returns the number of free variables.
Returns:
Number of free variables.
References QProblemB::bounds, and Bounds::getNFR().
Referenced by SQProblemSchur::addBound(), QProblem::addBound(), QProblemB::addBound(), QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), QProblem::addConstraint_ensureLI(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), SQProblemSchur::correctInertia(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::ensureNonzeroCurvature(), QProblem::getFreeVariablesFlags(), QProblemB::getNZ(), QProblem::getNZ(), SolutionAnalysis::getVarianceCovariance(), QProblem::performStep(), QProblemB::performStep(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), SQProblemSchur::repairSingularWorkingSet(), SQProblemSchur::resetSchurComplement(), QProblemB::setupInitialCholesky(), QProblem::setupInitialCholesky(), QProblem::setupTQfactorisation(), QProblem::solveCurrentEQP(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t QProblemB::getNFV () const [inline, inherited]
Returns the number of implicitly fixed variables.
Returns:
Number of implicitly fixed variables.
References QProblemB::bounds, and Bounds::getNFV().
Referenced by QProblemB::setupInitialCholesky(), and QProblem::setupInitialCholesky().
int_t QProblemB::getNFX () const [inline, inherited]
Returns the number of fixed variables.
Returns:
Number of fixed variables.
References QProblemB::bounds, and Bounds::getNFX().
Referenced by SQProblemSchur::addBound_checkLI(), QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint_checkLI(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblem::computeProjectedCholesky(), QProblemB::determineDataShift(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getVarianceCovariance(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblem::solveCurrentEQP(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t QProblem::getNIAC () const [inline, inherited]
Returns the number of inactive constraints.
Returns:
Number of inactive constraints.
References QProblem::constraints, and Constraints::getNIAC().
Referenced by QProblem::ensureNonzeroCurvature(), QProblem::performStep(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t QProblemB::getNV () const [inline, inherited]
Returns the number of variables.
Returns:
Number of variables.
References QProblemB::bounds, and Bounds::getNV().
Referenced by QProblem::addBound(), QProblemB::addBound(), QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblemB::areBoundsConsistent(), QProblemB::backsolveR(), QProblem::changeActiveSet(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblem::copy(), QProblemB::copy(), QProblemB::determineDataShift(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblem::ensureNonzeroCurvature(), QProblemB::getBounds(), QProblem::getConstraints(), QProblemB::getDualSolution(), QProblem::getDualSolution(), QProblem::getFreeVariablesFlags(), SolutionAnalysis::getKktViolation(), QProblemB::getObjVal(), QProblemB::getPrimalSolution(), QProblemB::getRelativeHomotopyLength(), SolutionAnalysis::getVarianceCovariance(), QProblem::getWorkingSet(), QProblemB::getWorkingSetBounds(), hotstart(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::init(), QProblem::init(), QProblemB::loadQPvectorsFromFile(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::regulariseHessian(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), QProblem::reset(), QProblemB::reset(), QProblem::setA(), QProblemB::setG(), QProblemB::setH(), QProblemB::setLB(), QProblem::setLBA(), QProblemB::setUB(), QProblem::setUBA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), QProblemB::setupAuxiliaryQPsolution(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupAuxiliaryWorkingSet(), QProblemB::setupInitialCholesky(), QProblem::setupInitialCholesky(), setupNewAuxiliaryQP(), QProblem::setupQPdata(), QProblemB::setupQPdataFromFile(), QProblem::setupQPdataFromFile(), QProblemB::setupSubjectToType(), QProblem::setupTQfactorisation(), QProblem::shallRefactorise(), QProblemB::shallRefactorise(), QProblem::solveCurrentEQP(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::solveQP(), QProblemB::solveQP(), QProblem::solveRegularisedQP(), QProblemB::solveRegularisedQP(), QProblem::updateActivitiesForHotstart(), QProblemB::updateFarBounds(), QProblem::updateFarBounds(), QProblem::writeQpDataIntoMatFile(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t QProblem::getNZ () const [virtual, inherited]
Returns the dimension of null space.
Returns:
Dimension of null space.
Reimplemented from QProblemB.
References QProblem::getNAC(), and QProblemB::getNFR().
Referenced by QProblem::addBound(), QProblem::addBound_checkLI(), QProblem::addBound_ensureLI(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), QProblem::addConstraint_ensureLI(), QProblem::computeProjectedCholesky(), QProblem::determineStepDirection(), QProblem::removeBound(), and QProblem::removeConstraint().
real_t QProblemB::getObjVal () const [inherited]
Returns the optimal objective function value.
Returns:
finite value: Optimal objective function value (QP was solved)
+infinity: QP was not yet solved
References QProblemB::getStatus(), INFTY, QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_SOLVED, real_t, and QProblemB::x.
Referenced by main().
real_t QProblemB::getObjVal (const real_t *const _x) const [inherited]
Returns the objective function value at an arbitrary point x.
Returns:
Objective function value at point x
Parameters:
_x Point at which the objective function shall be evaluated.
References BT_TRUE, QProblemB::g, QProblemB::getNV(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_ZERO, real_t, QProblemB::regVal, Matrix::times(), and QProblemB::usingRegularisation().
Options QProblemB::getOptions () const [inline, inherited]
Returns current options struct.
Returns:
Current options struct.
References QProblemB::options.
returnValue QProblemB::getPrimalSolution (real_t *const xOpt) const [inherited]
Returns the primal solution vector.
Returns:
SUCCESSFUL_RETURN
RET_QP_NOT_SOLVED
Parameters:
xOpt Output: Primal solution vector (if QP has been solved).
References QProblemB::getNV(), QProblemB::getStatus(), QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_SOLVED, RET_QP_NOT_SOLVED, SUCCESSFUL_RETURN, and QProblemB::x.
Referenced by main(), and solveOqpBenchmark().
PrintLevel QProblemB::getPrintLevel () const [inline, inherited]
Returns the print level.
Returns:
Print level.
References QProblemB::options, and Options::printLevel.
real_t QProblemB::getRelativeHomotopyLength (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new) [protected, inherited]
Compute relative length of homotopy in data space for termination criterion.
Returns:
Relative length in data space.
Parameters:
g_new Final gradient.
lb_new Final lower variable bounds.
ub_new Final upper variable bounds.
References QProblemB::g, getAbs(), QProblemB::getNV(), QProblemB::lb, real_t, and QProblemB::ub.
Referenced by QProblemB::solveQP().
real_t QProblem::getRelativeHomotopyLength (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new) [protected, inherited]
Compute relative length of homotopy in data space for termination criterion.
Returns:
Relative length in data space.
Parameters:
g_new Final gradient.
lb_new Final lower variable bounds.
ub_new Final upper variable bounds.
lbA_new Final lower constraint bounds.
ubA_new Final upper constraint bounds.
References getAbs(), QProblem::getNC(), QProblem::lbA, real_t, and QProblem::ubA.
Referenced by QProblem::solveQP().
QProblemStatus QProblemB::getStatus () const [inline, inherited]
Returns status of the solution process.
Returns:
Status of solution process.
References QProblemB::status.
Referenced by SQProblemSchur::addBound(), QProblem::addBound(), QProblemB::addBound(), SQProblemSchur::addConstraint(), QProblem::addConstraint(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblemB::getDualSolution(), QProblem::getDualSolution(), QProblemB::getObjVal(), QProblemB::getPrimalSolution(), hotstart(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), SQProblemSchur::setupAuxiliaryQP(), setupNewAuxiliaryQP(), QProblem::solveQP(), and QProblemB::solveQP().
returnValue QProblem::getWorkingSet (real_t * workingSet) [virtual, inherited]
Writes a vector with the state of the working set
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
workingSet Output: array containing state of the working set.
Reimplemented from QProblemB.
References QProblemB::getNV(), QProblem::getWorkingSetBounds(), QProblem::getWorkingSetConstraints(), RET_INVALID_ARGUMENTS, SUCCESSFUL_RETURN, and THROWERROR.
returnValue QProblem::getWorkingSetBounds (real_t * workingSetB) [virtual, inherited]
Writes a vector with the state of the working set of bounds
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
workingSetB Output: array containing state of the working set of bounds.
Reimplemented from QProblemB.
Referenced by SolutionAnalysis::getKktViolation(), and QProblem::getWorkingSet().
returnValue QProblem::getWorkingSetConstraints (real_t * workingSetC) [virtual, inherited]
Writes a vector with the state of the working set of constraints
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
workingSetC Output: array containing state of the working set of constraints.
Reimplemented from QProblemB.
References QProblem::constraints, QProblem::getNC(), SubjectTo::getStatus(), RET_INVALID_ARGUMENTS, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by SolutionAnalysis::getKktViolation(), and QProblem::getWorkingSet().
returnValue SQProblem::hotstart (SymmetricMatrix * H_new, const real_t *const g_new, Matrix * A_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0)
Solves an initialised QP sequence with matrix shift using the online active set strategy.
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_MATRIX_SHIFT_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
RET_SETUP_AUXILIARYQP_FAILED
Parameters:
H_new Hessian matrix of neighbouring QP to be solved (a shallow copy is made).
If Hessian matrix is trivial, a NULL pointer can be passed.
g_new Gradient of neighbouring QP to be solved.
A_new Constraint matrix of neighbouring QP to be solved (a shallow copy is made).
If QP sequence does not involve constraints, a NULL pointer can be passed.
lb_new Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_new Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
lbA_new Lower constraints' bounds of neighbouring QP to be solved.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new Upper constraints' bounds of neighbouring QP to be solved.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spen for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of bounds is kept!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of constraints is kept!)
References getCPUtime(), QProblemB::getStatus(), QPS_NOTINITIALISED, QPS_PERFORMINGHOMOTOPY, QPS_PREPARINGAUXILIARYQP, real_t, RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED, RET_SETUP_AUXILIARYQP_FAILED, setupNewAuxiliaryQP(), SUCCESSFUL_RETURN, and THROWERROR.
Referenced by hotstart(), and main().
returnValue SQProblem::hotstart (const real_t *const H_new, const real_t *const g_new, const real_t *const A_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0)
Solves an initialised QP sequence with matrix shift using the online active set strategy.
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_MATRIX_SHIFT_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
RET_SETUP_AUXILIARYQP_FAILED
Parameters:
H_new Hessian matrix of neighbouring QP to be solved (a shallow copy is made).
If Hessian matrix is trivial, a NULL pointer can be passed.
g_new Gradient of neighbouring QP to be solved.
A_new Constraint matrix of neighbouring QP to be solved (a shallow copy is made).
If QP sequence does not involve constraints, a NULL pointer can be passed.
lb_new Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_new Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
lbA_new Lower constraints' bounds of neighbouring QP to be solved.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new Upper constraints' bounds of neighbouring QP to be solved.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of bounds is kept!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of constraints is kept!)
References getCPUtime(), QProblemB::getStatus(), hotstart(), QPS_NOTINITIALISED, QPS_PERFORMINGHOMOTOPY, QPS_PREPARINGAUXILIARYQP, real_t, RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED, RET_SETUP_AUXILIARYQP_FAILED, setupNewAuxiliaryQP(), SUCCESSFUL_RETURN, and THROWERROR.
returnValue SQProblem::hotstart (const char *const H_file, const char *const g_file, const char *const A_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0)
Solves an initialised QP sequence with matrix shift using the online active set strategy, where QP data is read from files.
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_MATRIX_SHIFT_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
RET_SETUP_AUXILIARYQP_FAILED
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
Parameters:
H_file Name of file where Hessian matrix is stored.
If Hessian matrix is trivial, a NULL pointer can be passed.
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
A_file Name of file where constraint matrix is stored.
If QP sequence does not involve constraints, a NULL pointer can be passed.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
lbA_file Name of file where lower constraints' bounds, of neighbouring QP to be solved, is stored.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_file Name of file where upper constraints' bounds, of neighbouring QP to be solved, is stored.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of bounds is kept!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of constraints is kept!)
References QProblem::getNC(), QProblemB::getNV(), hotstart(), QProblem::loadQPvectorsFromFile(), readFromFile(), real_t, RET_INVALID_ARGUMENTS, RET_UNABLE_TO_READ_FILE, SUCCESSFUL_RETURN, and THROWERROR.
returnValue SQProblem::hotstart (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0)
Solves an initialised QP sequence (without matrix shift) using the online active set strategy. By default, QP solution is started from previous solution. If a guess for the working set is provided, an initialised homotopy is performed.
Note: This functions just forwards to the corresponding QProblem::hotstart member function.
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
Parameters:
g_new Gradient of neighbouring QP to be solved.
lb_new Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_new Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
lbA_new Lower constraints' bounds of neighbouring QP to be solved.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new Upper constraints' bounds of neighbouring QP to be solved.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of bounds is kept!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of constraints is kept!)
Reimplemented from QProblem.
References hotstart().
returnValue QProblemB::hotstart (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0) [inherited]
Solves an initialised QP sequence using the online active set strategy. By default, QP solution is started from previous solution. If a guess for the working set is provided, an initialised homotopy is performed.
Note: This function internally calls solveQP/solveRegularisedQP for solving an initialised QP!
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
RET_SETUP_AUXILIARYQP_FAILED
Parameters:
g_new Gradient of neighbouring QP to be solved.
lb_new Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_new Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set is kept!)
References QProblemB::areBoundsConsistent(), Options::boundTolerance, BT_FALSE, BT_TRUE, QProblemB::count, Options::enableFarBounds, getAbs(), getCPUtime(), QProblemB::getNV(), Options::growFarBounds, QProblemB::haveCholesky, QProblemB::infeasible, INFTY, Options::initialFarBounds, QProblemB::options, QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_SOLVED, QProblemB::rampOffset, real_t, RET_HOTSTART_STOPPED_INFEASIBILITY, RET_HOTSTART_STOPPED_UNBOUNDEDNESS, RET_QPOBJECT_NOT_SETUP, RET_SETUP_AUXILIARYQP_FAILED, QProblemB::setInfeasibilityFlag(), QProblemB::setupAuxiliaryQP(), QProblemB::setupInitialCholesky(), QProblemB::solveRegularisedQP(), QProblemB::status, SUCCESSFUL_RETURN, THROWERROR, QProblemB::unbounded, QProblemB::updateFarBounds(), and QProblemB::x.
Referenced by QProblemB::hotstart(), main(), QProblemB::solveInitialQP(), and solveOqpBenchmark().
returnValue SQProblem::hotstart (const char *const g_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0)
Solves an initialised QP sequence (without matrix shift) using the online active set strategy, where QP data is read from files. By default, QP solution is started from previous solution. If a guess for the working set is provided, an initialised homotopy is performed.
Note: This functions just forwards to the corresponding QProblem::hotstart member function.
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
Parameters:
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
lbA_file Name of file where lower constraints' bounds, of neighbouring QP to be solved, is stored.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_file Name of file where upper constraints' bounds, of neighbouring QP to be solved, is stored.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of bounds is kept!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set of constraints is kept!)
Reimplemented from QProblem.
References hotstart().
returnValue QProblemB::hotstart (const char *const g_file, const char *const lb_file, const char *const ub_file, int_t & nWSR, real_t *const cputime = 0, const Bounds *const guessedBounds = 0) [inherited]
Solves an initialised QP sequence using the online active set strategy, where QP data is read from files. By default, QP solution is started from previous solution. If a guess for the working set is provided, an initialised homotopy is performed.
Note: This function internally calls solveQP/solveRegularisedQP for solving an initialised QP!
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
RET_UNABLE_TO_READ_FILE
RET_SETUP_AUXILIARYQP_FAILED
RET_INVALID_ARGUMENTS
Parameters:
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, the previous working set is kept!)
References QProblemB::getNV(), QProblemB::hotstart(), QProblemB::loadQPvectorsFromFile(), real_t, RET_INVALID_ARGUMENTS, RET_QPOBJECT_NOT_SETUP, RET_UNABLE_TO_READ_FILE, SUCCESSFUL_RETURN, and THROWERROR.
returnValue QProblemB::init (SymmetricMatrix * _H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub, int_t & nWSR, real_t *const cputime = 0, const real_t *const xOpt = 0, const real_t *const yOpt = 0, const Bounds *const guessedBounds = 0, const real_t *const _R = 0) [inherited]
Initialises a simply bounded QP problem with given QP data and tries to solve it using at most nWSR iterations. Depending on the parameter constellation it:
1. 0, 0, 0 : starts with xOpt = 0, yOpt = 0 and gB empty (or all implicit equality bounds),
2. xOpt, 0, 0 : starts with xOpt, yOpt = 0 and obtain gB by "clipping",
3. 0, yOpt, 0 : starts with xOpt = 0, yOpt and obtain gB from yOpt != 0,
4. 0, 0, gB: starts with xOpt = 0, yOpt = 0 and gB,
5. xOpt, yOpt, 0 : starts with xOpt, yOpt and obtain gB from yOpt != 0,
6. xOpt, 0, gB: starts with xOpt, yOpt = 0 and gB,
7. xOpt, yOpt, gB: starts with xOpt, yOpt and gB (assume them to be consistent!)
Note: This function internally calls solveInitialQP for initialisation!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
RET_INVALID_ARGUMENTS
Parameters:
_H Hessian matrix (a shallow copy is made).
_g Gradient vector.
_lb Lower bounds (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bounds (on variables).
If no upper bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations when using initial homotopy.
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP initialisation.
Output: CPU time spent for QP initialisation (if pointer passed).
xOpt Optimal primal solution vector. A NULL pointer can be passed.
(If a null pointer is passed, the old primal solution is kept!)
yOpt Optimal dual solution vector. A NULL pointer can be passed.
(If a null pointer is passed, the old dual solution is kept!)
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, all bounds are assumed inactive!)
_R Pre-computed (upper triangular) Cholesky factor of Hessian matrix. The Cholesky factor must be stored in a real_t array of size nV*nV in row-major format. Note: Only used if xOpt/yOpt and gB are NULL!
(If a null pointer is passed, Cholesky decomposition is computed internally!)
References BT_TRUE, QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::isInitialised(), QProblemB::reset(), RET_INVALID_ARGUMENTS, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RET_QP_ALREADY_INITIALISED, RET_QPOBJECT_NOT_SETUP, QProblemB::setupQPdata(), QProblemB::solveInitialQP(), ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, and THROWWARNING.
Referenced by main(), and solveOqpBenchmark().
returnValue QProblem::init (SymmetricMatrix * _H, const real_t *const _g, Matrix * _A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA, int_t & nWSR, real_t *const cputime = 0, const real_t *const xOpt = 0, const real_t *const yOpt = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0, const real_t *const _R = 0) [inherited]
Initialises a QP problem with given QP data and tries to solve it using at most nWSR iterations. Depending on the parameter constellation it:
1. 0, 0, 0 : starts with xOpt = 0, yOpt = 0 and gB/gC empty (or all implicit equality bounds),
2. xOpt, 0, 0 : starts with xOpt, yOpt = 0 and obtain gB/gC by "clipping",
3. 0, yOpt, 0 : starts with xOpt = 0, yOpt and obtain gB/gC from yOpt != 0,
4. 0, 0, gB/gC: starts with xOpt = 0, yOpt = 0 and gB/gC,
5. xOpt, yOpt, 0 : starts with xOpt, yOpt and obtain gB/gC from yOpt != 0,
6. xOpt, 0, gB/gC: starts with xOpt, yOpt = 0 and gB/gC,
7. xOpt, yOpt, gB/gC: starts with xOpt, yOpt and gB/gC (assume them to be consistent!)
Note: This function internally calls solveInitialQP for initialisation!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_TQ
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
RET_INVALID_ARGUMENTS
Parameters:
_H Hessian matrix (a shallow copy is made).
_g Gradient vector.
_A Constraint matrix (a shallow copy is made).
_lb Lower bound vector (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bound vector (on variables).
If no upper bounds exist, a NULL pointer can be passed.
_lbA Lower constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
_ubA Upper constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations when using initial homotopy. Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP initialisation.
Output: CPU time spent for QP initialisation (if pointer passed).
xOpt Optimal primal solution vector.
(If a null pointer is passed, the old primal solution is kept!)
yOpt Optimal dual solution vector.
(If a null pointer is passed, the old dual solution is kept!)
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, all bounds are assumed inactive!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, all constraints are assumed inactive!)
_R Pre-computed (upper triangular) Cholesky factor of Hessian matrix. The Cholesky factor must be stored in a real_t array of size nV*nV in row-major format. Note: Only used if xOpt/yOpt and gB are NULL!
(If a null pointer is passed, Cholesky decomposition is computed internally!)
References BT_TRUE, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::isInitialised(), QProblem::reset(), RET_INVALID_ARGUMENTS, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RET_QP_ALREADY_INITIALISED, RET_QPOBJECT_NOT_SETUP, QProblem::setupQPdata(), QProblem::solveInitialQP(), ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, and THROWWARNING.
Referenced by main(), and solveOqpBenchmark().
returnValue QProblemB::init (const real_t *const _H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub, int_t & nWSR, real_t *const cputime = 0, const real_t *const xOpt = 0, const real_t *const yOpt = 0, const Bounds *const guessedBounds = 0, const real_t *const _R = 0) [inherited]
Initialises a simply bounded QP problem with given QP data and tries to solve it using at most nWSR iterations. Depending on the parameter constellation it:
1. 0, 0, 0 : starts with xOpt = 0, yOpt = 0 and gB empty (or all implicit equality bounds),
2. xOpt, 0, 0 : starts with xOpt, yOpt = 0 and obtain gB by "clipping",
3. 0, yOpt, 0 : starts with xOpt = 0, yOpt and obtain gB from yOpt != 0,
4. 0, 0, gB: starts with xOpt = 0, yOpt = 0 and gB,
5. xOpt, yOpt, 0 : starts with xOpt, yOpt and obtain gB from yOpt != 0,
6. xOpt, 0, gB: starts with xOpt, yOpt = 0 and gB,
7. xOpt, yOpt, gB: starts with xOpt, yOpt and gB (assume them to be consistent!)
Note: This function internally calls solveInitialQP for initialisation!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
RET_INVALID_ARGUMENTS
Parameters:
_H Hessian matrix (a shallow copy is made).
If Hessian matrix is trivial, a NULL pointer can be passed.
_g Gradient vector.
_lb Lower bounds (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bounds (on variables).
If no upper bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations when using initial homotopy.
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP initialisation.
Output: CPU time spent for QP initialisation (if pointer passed).
xOpt Optimal primal solution vector. A NULL pointer can be passed.
(If a null pointer is passed, the old primal solution is kept!)
yOpt Optimal dual solution vector. A NULL pointer can be passed.
(If a null pointer is passed, the old dual solution is kept!)
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, all bounds are assumed inactive!)
_R Pre-computed (upper triangular) Cholesky factor of Hessian matrix. The Cholesky factor must be stored in a real_t array of size nV*nV in row-major format. Note: Only used if xOpt/yOpt and gB are NULL!
(If a null pointer is passed, Cholesky decomposition is computed internally!)
References BT_TRUE, QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::isInitialised(), QProblemB::reset(), RET_INVALID_ARGUMENTS, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RET_QP_ALREADY_INITIALISED, RET_QPOBJECT_NOT_SETUP, QProblemB::setupQPdata(), QProblemB::solveInitialQP(), ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, and THROWWARNING.
returnValue QProblem::init (const real_t *const _H, const real_t *const _g, const real_t *const _A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA, int_t & nWSR, real_t *const cputime = 0, const real_t *const xOpt = 0, const real_t *const yOpt = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0, const real_t *const _R = 0) [inherited]
Initialises a QP problem with given QP data and tries to solve it using at most nWSR iterations. Depending on the parameter constellation it:
1. 0, 0, 0 : starts with xOpt = 0, yOpt = 0 and gB/gC empty (or all implicit equality bounds),
2. xOpt, 0, 0 : starts with xOpt, yOpt = 0 and obtain gB/gC by "clipping",
3. 0, yOpt, 0 : starts with xOpt = 0, yOpt and obtain gB/gC from yOpt != 0,
4. 0, 0, gB/gC: starts with xOpt = 0, yOpt = 0 and gB/gC,
5. xOpt, yOpt, 0 : starts with xOpt, yOpt and obtain gB/gC from yOpt != 0,
6. xOpt, 0, gB/gC: starts with xOpt, yOpt = 0 and gB/gC,
7. xOpt, yOpt, gB/gC: starts with xOpt, yOpt and gB/gC (assume them to be consistent!)
Note: This function internally calls solveInitialQP for initialisation!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_TQ
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
RET_INVALID_ARGUMENTS
Parameters:
_H Hessian matrix (a shallow copy is made).
If Hessian matrix is trivial, a NULL pointer can be passed.
_g Gradient vector.
_A Constraint matrix (a shallow copy is made).
_lb Lower bound vector (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bound vector (on variables).
If no upper bounds exist, a NULL pointer can be passed.
_lbA Lower constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
_ubA Upper constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations when using initial homotopy. Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP initialisation.
Output: CPU time spent for QP initialisation (if pointer passed).
xOpt Optimal primal solution vector.
(If a null pointer is passed, the old primal solution is kept!)
yOpt Optimal dual solution vector.
(If a null pointer is passed, the old dual solution is kept!)
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, all bounds are assumed inactive!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, all constraints are assumed inactive!)
_R Pre-computed (upper triangular) Cholesky factor of Hessian matrix. The Cholesky factor must be stored in a real_t array of size nV*nV in row-major format. Note: Only used if xOpt/yOpt and gB are NULL!
(If a null pointer is passed, Cholesky decomposition is computed internally!)
References BT_TRUE, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::isInitialised(), QProblem::reset(), RET_INVALID_ARGUMENTS, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RET_QP_ALREADY_INITIALISED, RET_QPOBJECT_NOT_SETUP, QProblem::setupQPdata(), QProblem::solveInitialQP(), ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, and THROWWARNING.
returnValue QProblemB::init (const char *const H_file, const char *const g_file, const char *const lb_file, const char *const ub_file, int_t & nWSR, real_t *const cputime = 0, const real_t *const xOpt = 0, const real_t *const yOpt = 0, const Bounds *const guessedBounds = 0, const char *const R_file = 0) [inherited]
Initialises a simply bounded QP problem with given QP data to be read from files and solves it using at most nWSR iterations. Depending on the parameter constellation it:
1. 0, 0, 0 : starts with xOpt = 0, yOpt = 0 and gB empty (or all implicit equality bounds),
2. xOpt, 0, 0 : starts with xOpt, yOpt = 0 and obtain gB by "clipping",
3. 0, yOpt, 0 : starts with xOpt = 0, yOpt and obtain gB from yOpt != 0,
4. 0, 0, gB: starts with xOpt = 0, yOpt = 0 and gB,
5. xOpt, yOpt, 0 : starts with xOpt, yOpt and obtain gB from yOpt != 0,
6. xOpt, 0, gB: starts with xOpt, yOpt = 0 and gB,
7. xOpt, yOpt, gB: starts with xOpt, yOpt and gB (assume them to be consistent!)
Note: This function internally calls solveInitialQP for initialisation!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
RET_UNABLE_TO_READ_FILE
Parameters:
H_file Name of file where Hessian matrix is stored.
If Hessian matrix is trivial, a NULL pointer can be passed.
g_file Name of file where gradient vector is stored.
lb_file Name of file where lower bound vector.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bound vector.
If no upper bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations when using initial homotopy.
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP initialisation.
Output: CPU time spent for QP initialisation (if pointer passed).
xOpt Optimal primal solution vector. A NULL pointer can be passed.
(If a null pointer is passed, the old primal solution is kept!)
yOpt Optimal dual solution vector. A NULL pointer can be passed.
(If a null pointer is passed, the old dual solution is kept!)
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, all bounds are assumed inactive!)
R_file Name of the file where a pre-computed (upper triangular) Cholesky factor of the Hessian matrix is stored.
(If a null pointer is passed, Cholesky decomposition is computed internally!)
References BT_TRUE, QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::isInitialised(), QProblemB::R, readFromFile(), QProblemB::reset(), RET_INVALID_ARGUMENTS, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RET_QP_ALREADY_INITIALISED, RET_QPOBJECT_NOT_SETUP, RET_UNABLE_TO_READ_FILE, QProblemB::setupQPdataFromFile(), QProblemB::solveInitialQP(), ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, and THROWWARNING.
returnValue QProblem::init (const char *const H_file, const char *const g_file, const char *const A_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, int_t & nWSR, real_t *const cputime = 0, const real_t *const xOpt = 0, const real_t *const yOpt = 0, const Bounds *const guessedBounds = 0, const Constraints *const guessedConstraints = 0, const char *const R_file = 0) [inherited]
Initialises a QP problem with given data to be read from files and solves it using at most nWSR iterations. Depending on the parameter constellation it:
1. 0, 0, 0 : starts with xOpt = 0, yOpt = 0 and gB/gC empty (or all implicit equality bounds),
2. xOpt, 0, 0 : starts with xOpt, yOpt = 0 and obtain gB/gC by "clipping",
3. 0, yOpt, 0 : starts with xOpt = 0, yOpt and obtain gB/gC from yOpt != 0,
4. 0, 0, gB/gC: starts with xOpt = 0, yOpt = 0 and gB/gC,
5. xOpt, yOpt, 0 : starts with xOpt, yOpt and obtain gB/gC from yOpt != 0,
6. xOpt, 0, gB/gC: starts with xOpt, yOpt = 0 and gB/gC,
7. xOpt, yOpt, gB/gC: starts with xOpt, yOpt and gB/gC (assume them to be consistent!)
Note: This function internally calls solveInitialQP for initialisation!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_TQ
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
Parameters:
H_file Name of file where Hessian matrix is stored.
If Hessian matrix is trivial, a NULL pointer can be passed.
g_file Name of file where gradient vector is stored.
A_file Name of file where constraint matrix is stored.
lb_file Name of file where lower bound vector.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bound vector.
If no upper bounds exist, a NULL pointer can be passed.
lbA_file Name of file where lower constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_file Name of file where upper constraints' bound vector.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations when using initial homotopy. Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP initialisation.
Output: CPU time spent for QP initialisation (if pointer passed).
xOpt Optimal primal solution vector.
(If a null pointer is passed, the old primal solution is kept!)
yOpt Optimal dual solution vector.
(If a null pointer is passed, the old dual solution is kept!)
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
(If a null pointer is passed, all bounds are assumed inactive!)
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
(If a null pointer is passed, all constraints are assumed inactive!)
R_file Name of the file where a pre-computed (upper triangular) Cholesky factor of the Hessian matrix is stored.
(If a null pointer is passed, Cholesky decomposition is computed internally!)
References BT_TRUE, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::isInitialised(), QProblemB::R, readFromFile(), QProblem::reset(), RET_INVALID_ARGUMENTS, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RET_QP_ALREADY_INITIALISED, RET_QPOBJECT_NOT_SETUP, RET_UNABLE_TO_READ_FILE, QProblem::setupQPdataFromFile(), QProblem::solveInitialQP(), ST_UNDEFINED, SUCCESSFUL_RETURN, THROWERROR, and THROWWARNING.
BooleanType QProblemB::isBlocking (real_t num, real_t den, real_t epsNum, real_t epsDen, real_t & t) const [inline, protected, inherited]
Checks whether given ratio is blocking, i.e. limits the maximum step length along the homotopy path to a value lower than given one.
Returns:
SUCCESSFUL_RETURN
Parameters:
num Numerator for performing the ratio test.
den Denominator for performing the ratio test.
epsNum Numerator tolerance.
epsDen Denominator tolerance.
t Input: Current maximum step length along the homotopy path, Output: Updated maximum possible step length along the homotopy path.
References BT_FALSE, and BT_TRUE.
Referenced by QProblemB::performRatioTest().
BooleanType QProblemB::isCPUtimeLimitExceeded (const real_t *const cputime, real_t starttime, int_t nWSR) const [protected, inherited]
Determines if next QP iteration can be performed within given CPU time limit.
Returns:
BT_TRUE: CPU time limit is exceeded, stop QP solution.
BT_FALSE: Sufficient CPU time for next QP iteration.
Parameters:
cputime Maximum CPU time allowed for QP solution.
starttime Start time of current QP solution.
nWSR Number of working set recalculations performed so far.
References BT_FALSE, BT_TRUE, getCPUtime(), and real_t.
Referenced by QProblem::solveQP(), and QProblemB::solveQP().
BooleanType QProblemB::isInfeasible () const [inline, inherited]
Returns if the QP is infeasible.
Returns:
BT_TRUE: QP infeasible
BT_FALSE: QP feasible (or not known to be infeasible!)
References QProblemB::infeasible.
Referenced by QProblem::solveInitialQP(), QProblemB::solveInitialQP(), and QProblem::solveQP().
BooleanType QProblemB::isInitialised () const [inline, inherited]
Returns if the QProblem object is initialised.
Returns:
BT_TRUE: QProblemB initialised
BT_FALSE: QProblemB not initialised
References BT_FALSE, BT_TRUE, QPS_NOTINITIALISED, and QProblemB::status.
Referenced by QProblemB::init(), and QProblem::init().
BooleanType QProblemB::isSolved () const [inline, inherited]
Returns if the QP has been solved.
Returns:
BT_TRUE: QProblemB solved
BT_FALSE: QProblemB not solved
References BT_FALSE, BT_TRUE, QPS_SOLVED, and QProblemB::status.
BooleanType QProblemB::isUnbounded () const [inline, inherited]
Returns if the QP is unbounded.
Returns:
BT_TRUE: QP unbounded
BT_FALSE: QP unbounded (or not known to be unbounded!)
References QProblemB::unbounded.
Referenced by QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
returnValue QProblemB::loadQPvectorsFromFile (const char *const g_file, const char *const lb_file, const char *const ub_file, real_t *const g_new, real_t *const lb_new, real_t *const ub_new) const [protected, inherited]
Loads new QP vectors from files (internal members are not affected!).
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
Parameters:
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
g_new Output: Gradient of neighbouring QP to be solved.
lb_new Output: Lower bounds of neighbouring QP to be solved
ub_new Output: Upper bounds of neighbouring QP to be solved
References QProblemB::getNV(), readFromFile(), RET_INVALID_ARGUMENTS, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblemB::hotstart().
returnValue QProblem::loadQPvectorsFromFile (const char *const g_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file, real_t *const g_new, real_t *const lb_new, real_t *const ub_new, real_t *const lbA_new, real_t *const ubA_new) const [protected, inherited]
Loads new QP vectors from files (internal members are not affected!).
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
Parameters:
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
lbA_file Name of file where lower constraints' bounds, of neighbouring QP to be solved, is stored.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_file Name of file where upper constraints' bounds, of neighbouring QP to be solved, is stored.
If no upper constraints' bounds exist, a NULL pointer can be passed.
g_new Output: Gradient of neighbouring QP to be solved.
lb_new Output: Lower bounds of neighbouring QP to be solved
ub_new Output: Upper bounds of neighbouring QP to be solved
lbA_new Output: Lower constraints' bounds of neighbouring QP to be solved
ubA_new Output: Upper constraints' bounds of neighbouring QP to be solved
References QProblem::getNC(), readFromFile(), RET_INVALID_ARGUMENTS, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by hotstart(), and QProblem::hotstart().
returnValue QProblemB::obtainAuxiliaryWorkingSet (const real_t *const xOpt, const real_t *const yOpt, const Bounds *const guessedBounds, Bounds * auxiliaryBounds) const [protected, inherited]
Obtains the desired working set for the auxiliary initial QP in accordance with the user specifications
Returns:
SUCCESSFUL_RETURN
RET_OBTAINING_WORKINGSET_FAILED
RET_INVALID_ARGUMENTS
Parameters:
xOpt Optimal primal solution vector. If a NULL pointer is passed, all entries are assumed to be zero.
yOpt Optimal dual solution vector. If a NULL pointer is passed, all entries are assumed to be zero.
guessedBounds Guessed working set for solution (xOpt,yOpt).
auxiliaryBounds Input: Allocated bound object.
Output: Working set for auxiliary QP.
References QProblemB::bounds, Options::boundTolerance, EPS, QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), Options::initialStatusBounds, QProblemB::lb, QProblemB::options, RET_INVALID_ARGUMENTS, RET_OBTAINING_WORKINGSET_FAILED, Bounds::setupBound(), ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UNBOUNDED, ST_UPPER, SUCCESSFUL_RETURN, THROWERROR, and QProblemB::ub.
Referenced by QProblem::obtainAuxiliaryWorkingSet(), and QProblemB::solveInitialQP().
returnValue QProblem::obtainAuxiliaryWorkingSet (const real_t *const xOpt, const real_t *const yOpt, const Bounds *const guessedBounds, const Constraints *const guessedConstraints, Bounds * auxiliaryBounds, Constraints * auxiliaryConstraints) const [protected, inherited]
Obtains the desired working set for the auxiliary initial QP in accordance with the user specifications (assumes that member AX has already been initialised!)
Returns:
SUCCESSFUL_RETURN
RET_OBTAINING_WORKINGSET_FAILED
RET_INVALID_ARGUMENTS
Parameters:
xOpt Optimal primal solution vector. If a NULL pointer is passed, all entries are assumed to be zero.
yOpt Optimal dual solution vector. If a NULL pointer is passed, all entries are assumed to be zero.
guessedBounds Guessed working set of bounds for solution (xOpt,yOpt).
guessedConstraints Guessed working set for solution (xOpt,yOpt).
auxiliaryBounds Input: Allocated bound object.
Ouput: Working set of constraints for auxiliary QP.
auxiliaryConstraints Input: Allocated bound object.
Ouput: Working set for auxiliary QP.
References QProblem::Ax, QProblem::Ax_u, Options::boundTolerance, QProblem::constraints, EPS, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), QProblem::lbA, QProblemB::obtainAuxiliaryWorkingSet(), QProblemB::options, RET_INVALID_ARGUMENTS, RET_OBTAINING_WORKINGSET_FAILED, Constraints::setupConstraint(), ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, THROWERROR, and QProblem::ubA.
Referenced by QProblem::solveInitialQP().
SQProblem & SQProblem::operator= (const SQProblem & rhs) [virtual]
Assignment operator (deep copy).
Parameters:
rhs Rhs object.
returnValue QProblem::performDriftCorrection () [protected, virtual, inherited]
Drift correction at end of each active set iteration
Returns:
SUCCESSFUL_RETURN
Reimplemented from QProblemB.
References QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, QProblem::constraints, getMax(), getMin(), QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), QProblemB::lb, QProblem::lbA, QProblem::setupAuxiliaryQPgradient(), ST_BOUNDED, ST_DISABLED, ST_EQUALITY, ST_INACTIVE, ST_INFEASIBLE_LOWER, ST_INFEASIBLE_UPPER, ST_LOWER, ST_UNBOUNDED, ST_UNDEFINED, ST_UNKNOWN, ST_UPPER, QProblemB::ub, QProblem::ubA, QProblemB::x, and QProblemB::y.
Referenced by QProblem::solveQP().
returnValue QProblem::performPlainRatioTest (int_t nIdx, const int_t *const idxList, const real_t *const num, const real_t *const den, real_t epsNum, real_t epsDen, real_t & t, int_t & BC_idx) const [protected, inherited]
Performs robustified ratio test yield the maximum possible step length along the homotopy path.
Returns:
SUCCESSFUL_RETURN
Parameters:
nIdx Number of ratios to be checked.
idxList Array containing the indices of all ratios to be checked.
num Array containing all numerators for performing the ratio test.
den Array containing all denominators for performing the ratio test.
epsNum Numerator tolerance.
epsDen Denominator tolerance.
t Output: Maximum possible step length along the homotopy path.
BC_idx Output: Index of blocking constraint.
References SUCCESSFUL_RETURN.
Referenced by QProblem::ensureNonzeroCurvature().
returnValue QProblem::performRamping () [protected, virtual, inherited]
Ramping Strategy to avoid ties. Modifies homotopy start without changing current active set.
Returns:
SUCCESSFUL_RETURN
Reimplemented from QProblemB.
References QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, QProblem::constraints, getAbs(), getMax(), QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), QProblemB::lb, QProblem::lbA, QProblemB::ramp0, QProblemB::ramp1, QProblemB::rampOffset, real_t, QProblem::setupAuxiliaryQPgradient(), ST_BOUNDED, ST_DISABLED, ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UNBOUNDED, ST_UPPER, SUCCESSFUL_RETURN, QProblemB::ub, QProblem::ubA, QProblemB::x, and QProblemB::y.
Referenced by QProblem::solveInitialQP(), and QProblem::solveQP().
returnValue QProblemB::performRatioTest (int_t nIdx, const int_t *const idxList, const SubjectTo *const subjectTo, const real_t *const num, const real_t *const den, real_t epsNum, real_t epsDen, real_t & t, int_t & BC_idx) const [protected, inherited]
Performs robustified ratio test yield the maximum possible step length along the homotopy path.
Returns:
SUCCESSFUL_RETURN
Parameters:
nIdx Number of ratios to be checked.
idxList Array containing the indices of all ratios to be checked.
subjectTo Bound/Constraint object corresponding to ratios to be checked.
num Array containing all numerators for performing the ratio test.
den Array containing all denominators for performing the ratio test.
epsNum Numerator tolerance.
epsDen Denominator tolerance.
t Output: Maximum possible step length along the homotopy path.
BC_idx Output: Index of blocking constraint.
References BT_TRUE, SubjectTo::getStatus(), SubjectTo::getType(), QProblemB::isBlocking(), ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UPPER, and SUCCESSFUL_RETURN.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::performStep(), and QProblemB::performStep().
returnValue QProblem::performStep (const real_t *const delta_g, const real_t *const delta_lbA, const real_t *const delta_ubA, const real_t *const delta_lb, const real_t *const delta_ub, const real_t *const delta_xFX, const real_t *const delta_xFR, const real_t *const delta_yAC, const real_t *const delta_yFX, int_t & BC_idx, SubjectToStatus & BC_status, BooleanType & BC_isBound) [protected, inherited]
Determines the maximum possible step length along the homotopy path and performs this step (without changing working set).
Returns:
SUCCESSFUL_RETURN
RET_ERROR_IN_CONSTRAINTPRODUCT
RET_QP_INFEASIBLE
Parameters:
delta_g Step direction of gradient.
delta_lbA Step direction of lower constraints' bounds.
delta_ubA Step direction of upper constraints' bounds.
delta_lb Step direction of lower bounds.
delta_ub Step direction of upper bounds.
delta_xFX Primal homotopy step direction of fixed variables.
delta_xFR Primal homotopy step direction of free variables.
delta_yAC Dual homotopy step direction of active constraints' multiplier.
delta_yFX Dual homotopy step direction of fixed variables' multiplier.
BC_idx Output: Index of blocking constraint.
BC_status Output: Status of blocking constraint.
BC_isBound Output: Indicates if blocking constraint is a bound.
References __FILE__, __FUNC__, __LINE__, QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraintProduct, QProblem::constraints, Options::epsDen, Options::epsNum, QProblemB::g, Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), getGlobalMessageHandler(), Constraints::getInactive(), getMax(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), QProblem::getNIAC(), Indexlist::getNumberArray(), QProblemB::getNV(), SubjectTo::getType(), SubjectTo::hasNoLower(), SubjectTo::hasNoUpper(), QProblemB::lb, QProblem::lbA, MAX_STRING_LENGTH, QProblemB::options, QProblemB::performRatioTest(), real_t, RET_ERROR_IN_CONSTRAINTPRODUCT, RET_STEPSIZE, RET_STEPSIZE_NONPOSITIVE, ST_INACTIVE, ST_LOWER, ST_UNBOUNDED, ST_UNDEFINED, ST_UPPER, SUCCESSFUL_RETURN, QProblemB::tau, THROWERROR, MessageHandling::throwInfo(), MessageHandling::throwWarning(), Matrix::times(), QProblemB::ub, QProblem::ubA, VS_VISIBLE, QProblemB::x, QProblemB::y, and ZERO.
Referenced by QProblem::solveQP().
returnValue QProblem::printIteration (int_t iter, int_t BC_idx, SubjectToStatus BC_status, BooleanType BC_isBound, real_t homotopyLength, BooleanType isFirstCall = BT_TRUE) [protected, inherited]
Prints concise information on the current iteration.
Returns:
SUCCESSFUL_RETURN
Parameters:
iter Number of current iteration.
BC_idx Index of blocking constraint.
BC_status Status of blocking constraint.
BC_isBound Indicates if blocking constraint is a bound.
homotopyLength Current homotopy distance.
isFirstCall Indicating whether this is the first call for current QP.
References QProblem::A, BT_TRUE, QProblemB::count, EPS, TabularOutput::excAddB, TabularOutput::excAddC, TabularOutput::excRemB, TabularOutput::excRemC, QProblemB::g, getAbs(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFX(), QProblemB::getNV(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_ZERO, TabularOutput::idxAddB, TabularOutput::idxAddC, TabularOutput::idxRemB, TabularOutput::idxRemC, QProblemB::lb, QProblem::lbA, MAX_STRING_LENGTH, myPrintf(), QProblemB::options, PL_DEBUG_ITER, PL_MEDIUM, PL_TABULAR, Options::printLevel, real_t, QProblemB::regVal, RET_INVALID_ARGUMENTS, QProblem::sizeT, ST_INACTIVE, ST_UNDEFINED, SUCCESSFUL_RETURN, QProblemB::tabularOutput, QProblemB::tau, THROWERROR, Matrix::times(), Matrix::transTimes(), TT, QProblemB::ub, QProblem::ubA, QProblemB::x, and QProblemB::y.
Referenced by QProblem::solveQP().
returnValue QProblemB::printOptions () const [inherited]
Prints a list of all options and their current values.
Returns:
SUCCESSFUL_RETURN
References QProblemB::options, and Options::print().
Referenced by main().
returnValue QProblem::printProperties () [virtual, inherited]
Prints concise list of properties of the current QP.
Returns:
SUCCESSFUL_RETURN
Reimplemented from QProblemB.
References QProblemB::bounds, BT_TRUE, QProblem::constraints, QProblem::getNC(), QProblem::getNEC(), QProblemB::getNV(), SubjectTo::hasNoLower(), SubjectTo::hasNoUpper(), QProblemB::hessianType, HST_IDENTITY, HST_INDEF, HST_POSDEF, HST_POSDEF_NULLSPACE, HST_SEMIDEF, HST_ZERO, QProblemB::infeasible, MAX_STRING_LENGTH, myPrintf(), QProblemB::options, PL_DEBUG_ITER, PL_HIGH, PL_LOW, PL_MEDIUM, PL_NONE, PL_TABULAR, Options::printLevel, QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_NOTINITIALISED, QPS_PERFORMINGHOMOTOPY, QPS_PREPARINGAUXILIARYQP, QPS_SOLVED, QProblemB::status, SUCCESSFUL_RETURN, and QProblemB::unbounded.
returnValue QProblemB::regulariseHessian () [protected, inherited]
Regularise Hessian matrix by adding a scaled identity matrix to it.
Returns:
SUCCESSFUL_RETURN
RET_HESSIAN_ALREADY_REGULARISED
References Matrix::addToDiag(), BT_FALSE, BT_TRUE, Options::enableRegularisation, Options::epsRegularisation, QProblemB::g, Matrix::getNorm(), getNorm(), QProblemB::getNV(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_ZERO, QProblemB::options, QProblemB::regVal, RET_CANNOT_REGULARISE_IDENTITY, RET_CANNOT_REGULARISE_SPARSE, RET_NO_DIAGONAL_AVAILABLE, RET_USING_REGULARISATION, SUCCESSFUL_RETURN, THROWERROR, THROWINFO, and QProblemB::usingRegularisation().
Referenced by SQProblemSchur::setupAuxiliaryQP(), QProblemB::setupInitialCholesky(), QProblem::setupInitialCholesky(), setupNewAuxiliaryQP(), QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
returnValue QProblem::removeBound (int_t number, BooleanType updateCholesky, BooleanType allowFlipping = BT_FALSE, BooleanType ensureNZC = BT_FALSE) [protected, virtual, inherited]
Removes a bounds from active set.
Returns:
SUCCESSFUL_RETURN
RET_BOUND_NOT_ACTIVE
RET_HESSIAN_NOT_SPD
RET_REMOVEBOUND_FAILED
Parameters:
number Number of bound to be removed from active set.
updateCholesky Flag indicating if Cholesky decomposition shall be updated.
allowFlipping Flag indicating if flipping bounds are allowed.
ensureNZC Flag indicating if non-zero curvature is ensured by exchange rules.
Reimplemented in SQProblemSchur.
References QProblem::A, QProblem::addBound(), QProblem::addConstraint(), QProblemB::applyGivens(), QProblemB::backsolveR(), QProblemB::bounds, BT_FALSE, BT_TRUE, QProblemB::computeGivens(), QProblem::constraints, Matrix::diag(), Options::enableFlippingBounds, QProblem::ensureNonzeroCurvature(), EPS, Options::epsFlipping, TabularOutput::excAddB, TabularOutput::excAddC, Bounds::flipFixed(), QProblemB::flipper, Flipper::get(), Constraints::getActive(), Matrix::getCol(), Bounds::getFree(), QProblem::getNAC(), QProblemB::getNFR(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), getSqrt(), SubjectTo::getStatus(), QProblemB::getStatus(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_SEMIDEF, HST_ZERO, TabularOutput::idxAddB, TabularOutput::idxRemB, QProblemB::lb, Bounds::moveFixedToFree(), QProblemB::options, QProblem::Q, QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_NOTINITIALISED, QPS_SOLVED, QQ, QProblemB::R, real_t, RET_BOUND_NOT_ACTIVE, RET_HESSIAN_NOT_SPD, RET_MOVING_BOUND_FAILED, RET_REMOVEBOUND_FAILED, RET_UNKNOWN_BUG, RR, Flipper::set(), QProblem::sizeT, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, QProblem::T, QProblemB::tabularOutput, THROWERROR, Matrix::times(), TT, QProblemB::ub, and ZERO.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::changeActiveSet(), QProblem::dropInfeasibles(), QProblem::setupAuxiliaryWorkingSet(), and QProblem::updateActivitiesForHotstart().
returnValue QProblem::removeConstraint (int_t number, BooleanType updateCholesky, BooleanType allowFlipping = BT_FALSE, BooleanType ensureNZC = BT_FALSE) [protected, virtual, inherited]
Removes a constraint from active set.
Returns:
SUCCESSFUL_RETURN
RET_CONSTRAINT_NOT_ACTIVE
RET_REMOVECONSTRAINT_FAILED
RET_HESSIAN_NOT_SPD
Parameters:
number Number of constraint to be removed from active set.
updateCholesky Flag indicating if Cholesky decomposition shall be updated.
allowFlipping Flag indicating if flipping bounds are allowed.
ensureNZC Flag indicating if non-zero curvature is ensured by exchange rules.
Reimplemented in SQProblemSchur.
References QProblem::addBound(), QProblem::addConstraint(), QProblemB::applyGivens(), QProblem::Ax_l, QProblem::Ax_u, QProblemB::backsolveR(), QProblemB::bounds, BT_FALSE, BT_TRUE, QProblemB::computeGivens(), QProblem::constraints, Options::enableFlippingBounds, QProblem::ensureNonzeroCurvature(), EPS, Options::epsFlipping, TabularOutput::excAddB, TabularOutput::excAddC, Constraints::flipFixed(), QProblemB::flipper, Flipper::get(), Constraints::getActive(), Bounds::getFree(), Indexlist::getIndex(), QProblem::getNAC(), QProblemB::getNFR(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::getNZ(), getSqrt(), SubjectTo::getStatus(), QProblemB::getStatus(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_SEMIDEF, HST_ZERO, TabularOutput::idxAddC, TabularOutput::idxRemC, QProblem::lbA, Constraints::moveActiveToInactive(), QProblemB::options, QProblem::Q, QPS_AUXILIARYQPSOLVED, QPS_HOMOTOPYQPSOLVED, QPS_NOTINITIALISED, QPS_SOLVED, QQ, QProblemB::R, real_t, RET_CONSTRAINT_NOT_ACTIVE, RET_HESSIAN_NOT_SPD, RET_MOVING_BOUND_FAILED, RET_REMOVECONSTRAINT_FAILED, RET_UNKNOWN_BUG, RR, Flipper::set(), QProblem::sizeT, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, QProblem::T, QProblemB::tabularOutput, THROWERROR, Matrix::times(), TT, QProblem::ubA, and ZERO.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::changeActiveSet(), QProblem::dropInfeasibles(), and QProblem::setupAuxiliaryWorkingSet().
returnValue QProblem::reset () [virtual, inherited]
Clears all data structures of QProblemB except for QP data.
Returns:
SUCCESSFUL_RETURN
RET_RESET_FAILED
Reimplemented from QProblemB.
Reimplemented in SQProblemSchur.
References QProblem::constraintProduct, QProblem::constraints, QProblemB::flipper, QProblem::getNC(), QProblemB::getNV(), Constraints::init(), Flipper::init(), QProblem::Q, QProblemB::reset(), RET_QPOBJECT_NOT_SETUP, RET_RESET_FAILED, QProblem::sizeT, SUCCESSFUL_RETURN, QProblem::T, and THROWERROR.
Referenced by QProblem::init(), and SQProblemSchur::reset().
returnValue QProblemB::resetCounter () [inline, inherited]
Resets QP problem counter (to zero).
Returns:
SUCCESSFUL_RETURN.
References QProblemB::count, and SUCCESSFUL_RETURN.
returnValue QProblem::setA (Matrix * A_new) [inline, protected, inherited]
Sets constraint matrix of the QP.
Note: Also internal vector Ax is recomputed!
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
A_new New constraint matrix (a shallow copy is made).
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, BT_FALSE, BT_TRUE, QProblem::constraints, QProblem::freeConstraintMatrix, QProblem::getNC(), QProblemB::getNV(), Matrix::getRowNorm(), isZero(), QProblem::lbA, RET_INVALID_ARGUMENTS, RET_QPOBJECT_NOT_SETUP, SubjectTo::setType(), ST_DISABLED, SUCCESSFUL_RETURN, QProblem::tempC, THROWERROR, Matrix::times(), QProblem::ubA, and QProblemB::x.
Referenced by SQProblemSchur::setupAuxiliaryQP(), setupNewAuxiliaryQP(), QProblem::setupQPdata(), and QProblem::setupQPdataFromFile().
returnValue QProblem::setA (const real_t *const A_new) [inline, protected, inherited]
Sets dense constraint matrix of the QP.
Note: Also internal vector Ax is recomputed!
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
A_new New dense constraint matrix (with correct dimension!), a shallow copy is made.
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, BT_TRUE, QProblem::freeConstraintMatrix, QProblem::getNC(), QProblemB::getNV(), QProblem::lbA, real_t, RET_INVALID_ARGUMENTS, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, THROWERROR, Matrix::times(), QProblem::ubA, and QProblemB::x.
returnValue QProblem::setConstraintProduct (ConstraintProduct *const _constraintProduct) [inherited]
Defines user-defined routine for calculating the constraint product A*x
Returns:
SUCCESSFUL_RETURN
References QProblem::constraintProduct, and SUCCESSFUL_RETURN.
Referenced by main().
returnValue QProblemB::setG (const real_t *const g_new) [inline, protected, inherited]
Changes gradient vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
g_new New gradient vector (with correct dimension!).
References QProblemB::g, QProblemB::getNV(), real_t, RET_INVALID_ARGUMENTS, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblemB::copy(), and QProblemB::setupQPdata().
returnValue QProblemB::setH (SymmetricMatrix * H_new) [inline, protected, inherited]
Sets Hessian matrix of the QP.
Returns:
SUCCESSFUL_RETURN
Parameters:
H_new New Hessian matrix (a shallow copy is made).
References BT_FALSE, BT_TRUE, QProblemB::freeHessian, QProblemB::H, and SUCCESSFUL_RETURN.
Referenced by SQProblemSchur::setupAuxiliaryQP(), setupNewAuxiliaryQP(), QProblemB::setupQPdata(), and QProblemB::setupQPdataFromFile().
returnValue QProblemB::setH (const real_t *const H_new) [inline, protected, inherited]
Sets dense Hessian matrix of the QP. If a null pointer is passed and a) hessianType is HST_IDENTITY, nothing is done, b) hessianType is not HST_IDENTITY, Hessian matrix is set to zero.
Returns:
SUCCESSFUL_RETURN
Parameters:
H_new New dense Hessian matrix (with correct dimension!), a shallow copy is made.
References BT_FALSE, BT_TRUE, QProblemB::freeHessian, QProblemB::getNV(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_ZERO, real_t, and SUCCESSFUL_RETURN.
returnValue QProblemB::setHessianType (HessianType _hessianType) [inline, inherited]
Changes the print level.
Returns:
SUCCESSFUL_RETURN
Parameters:
_hessianType New Hessian type.
References QProblemB::hessianType, and SUCCESSFUL_RETURN.
returnValue QProblemB::setInfeasibilityFlag (returnValue returnvalue, BooleanType doThrowError = BT_FALSE) [protected, inherited]
Sets internal infeasibility flag and throws given error in case the far bound strategy is not enabled (as QP might actually not be infeasible in this case).
Returns:
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_ENSURELI_FAILED_CYCLING
RET_ENSURELI_FAILED_NOINDEX
Parameters:
returnvalue Returnvalue to be tunneled.
doThrowError Flag forcing to throw an error.
References BT_FALSE, BT_TRUE, Options::enableFarBounds, QProblemB::infeasible, QProblemB::options, and THROWERROR.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::solveQP(), and QProblemB::solveQP().
returnValue QProblemB::setLB (const real_t *const lb_new) [inline, protected, inherited]
Changes lower bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
Parameters:
lb_new New lower bound vector (with correct dimension!).
References QProblemB::getNV(), INFTY, QProblemB::lb, real_t, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblemB::copy(), and QProblemB::setupQPdata().
returnValue QProblemB::setLB (int_t number, real_t value) [inline, protected, inherited]
Changes single entry of lower bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
RET_INDEX_OUT_OF_BOUNDS
Parameters:
number Number of entry to be changed.
value New value for entry of lower bound vector.
References QProblemB::getNV(), QProblemB::lb, RET_INDEX_OUT_OF_BOUNDS, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
returnValue QProblem::setLBA (const real_t *const lbA_new) [inline, protected, inherited]
Sets constraints' lower bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
Parameters:
lbA_new New constraints' lower bound vector (with correct dimension!).
References QProblem::getNC(), QProblemB::getNV(), INFTY, QProblem::lbA, real_t, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::copy(), and QProblem::setupQPdata().
returnValue QProblem::setLBA (int_t number, real_t value) [inline, protected, inherited]
Changes single entry of lower constraints' bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
RET_INDEX_OUT_OF_BOUNDS
Parameters:
number Number of entry to be changed.
value New value for entry of lower constraints' bound vector (with correct dimension!).
References QProblem::getNC(), QProblemB::getNV(), QProblem::lbA, RET_INDEX_OUT_OF_BOUNDS, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, and THROWERROR.
returnValue QProblemB::setOptions (const Options & _options) [inline, inherited]
Overrides current options with given ones.
Returns:
SUCCESSFUL_RETURN
Parameters:
_options New options.
References Options::ensureConsistency(), QProblemB::options, Options::printLevel, QProblemB::setPrintLevel(), and SUCCESSFUL_RETURN.
Referenced by main(), and solveOqpBenchmark().
returnValue QProblemB::setPrintLevel (PrintLevel _printlevel) [inherited]
Changes the print level.
Returns:
SUCCESSFUL_RETURN
Parameters:
_printlevel New print level.
References getGlobalMessageHandler(), QProblemB::options, PL_DEBUG_ITER, PL_HIGH, PL_LOW, PL_MEDIUM, PL_NONE, PL_TABULAR, Options::printLevel, RET_PRINTLEVEL_CHANGED, MessageHandling::setErrorVisibilityStatus(), MessageHandling::setInfoVisibilityStatus(), MessageHandling::setWarningVisibilityStatus(), SUCCESSFUL_RETURN, THROWINFO, VS_HIDDEN, and VS_VISIBLE.
Referenced by QProblemB::copy(), main(), QProblemB::QProblemB(), and QProblemB::setOptions().
returnValue QProblemB::setUB (const real_t *const ub_new) [inline, protected, inherited]
Changes upper bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
Parameters:
ub_new New upper bound vector (with correct dimension!).
References QProblemB::getNV(), INFTY, real_t, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, THROWERROR, and QProblemB::ub.
Referenced by QProblemB::copy(), and QProblemB::setupQPdata().
returnValue QProblemB::setUB (int_t number, real_t value) [inline, protected, inherited]
Changes single entry of upper bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
RET_INDEX_OUT_OF_BOUNDS
Parameters:
number Number of entry to be changed.
value New value for entry of upper bound vector.
References QProblemB::getNV(), RET_INDEX_OUT_OF_BOUNDS, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, THROWERROR, and QProblemB::ub.
returnValue QProblem::setUBA (const real_t *const ubA_new) [inline, protected, inherited]
Sets constraints' upper bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
Parameters:
ubA_new New constraints' upper bound vector (with correct dimension!).
References QProblem::getNC(), QProblemB::getNV(), INFTY, real_t, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, THROWERROR, and QProblem::ubA.
Referenced by QProblem::copy(), and QProblem::setupQPdata().
returnValue QProblem::setUBA (int_t number, real_t value) [inline, protected, inherited]
Changes single entry of upper constraints' bound vector of the QP.
Returns:
SUCCESSFUL_RETURN
RET_QPOBJECT_NOT_SETUP
RET_INDEX_OUT_OF_BOUNDS
Parameters:
number Number of entry to be changed.
value New value for entry of upper constraints' bound vector (with correct dimension!).
References QProblem::getNC(), QProblemB::getNV(), RET_INDEX_OUT_OF_BOUNDS, RET_QPOBJECT_NOT_SETUP, SUCCESSFUL_RETURN, THROWERROR, and QProblem::ubA.
returnValue QProblem::setupAuxiliaryQP (const Bounds *const guessedBounds, const Constraints *const guessedConstraints) [protected, virtual, inherited]
Parameters:
guessedBounds Initial guess for working set of bounds.
guessedConstraints Initial guess for working set of constraints.
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::computeProjectedCholesky(), QProblem::constraints, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), Bounds::init(), Constraints::init(), QPS_PREPARINGAUXILIARYQP, RET_INVALID_ARGUMENTS, RET_SETUP_AUXILIARYQP_FAILED, Bounds::setupAllFree(), Constraints::setupAllInactive(), QProblem::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryWorkingSet(), QProblem::setupSubjectToType(), QProblem::setupTQfactorisation(), QProblem::shallRefactorise(), ST_INACTIVE, QProblemB::status, SUCCESSFUL_RETURN, THROWERROR, Matrix::times(), QProblemB::x, and QProblemB::y.
Referenced by QProblem::hotstart().
returnValue QProblemB::setupAuxiliaryQP (const Bounds *const guessedBounds) [protected, virtual, inherited]
Updates QP vectors, working sets and internal data structures in order to start from an optimal solution corresponding to initial guesses of the working set for bounds
Returns:
SUCCESSFUL_RETURN
RET_SETUP_AUXILIARYQP_FAILED
Parameters:
guessedBounds Initial guess for working set of bounds.
References QProblemB::bounds, BT_FALSE, BT_TRUE, QProblemB::computeCholesky(), QProblemB::getNV(), SubjectTo::getStatus(), Bounds::init(), QPS_PREPARINGAUXILIARYQP, RET_SETUP_AUXILIARYQP_FAILED, Bounds::setupAllFree(), QProblemB::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryWorkingSet(), QProblemB::setupSubjectToType(), QProblemB::shallRefactorise(), ST_INACTIVE, QProblemB::status, SUCCESSFUL_RETURN, THROWERROR, and QProblemB::y.
Referenced by QProblemB::hotstart().
returnValue QProblem::setupAuxiliaryQPbounds (const Bounds *const auxiliaryBounds, const Constraints *const auxiliaryConstraints, BooleanType useRelaxation) [protected, inherited]
Sets up (constraints') bounds of the auxiliary initial QP for given optimal primal/dual solution and given initial working set (assumes that members X, Y and BOUNDS, CONSTRAINTS have already been initialised!).
Returns:
SUCCESSFUL_RETURN
RET_UNKNOWN_BUG
Parameters:
auxiliaryBounds Working set of bounds for auxiliary QP.
auxiliaryConstraints Working set of constraints for auxiliary QP.
useRelaxation Flag indicating if inactive (constraints') bounds shall be relaxed.
References QProblem::Ax_l, QProblem::Ax_u, Options::boundRelaxation, QProblemB::bounds, BT_TRUE, QProblem::constraints, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), QProblemB::lb, QProblem::lbA, QProblemB::options, RET_UNKNOWN_BUG, ST_EQUALITY, ST_INACTIVE, ST_INFEASIBLE_LOWER, ST_INFEASIBLE_UPPER, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, THROWERROR, QProblemB::ub, QProblem::ubA, and QProblemB::x.
Referenced by SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), setupNewAuxiliaryQP(), and QProblem::solveInitialQP().
returnValue QProblem::setupAuxiliaryQPgradient () [protected, inherited]
Sets up gradient of the auxiliary initial QP for given optimal primal/dual solution and given initial working set (assumes that members X, Y and BOUNDS, CONSTRAINTS have already been initialised!).
Returns:
SUCCESSFUL_RETURN
Reimplemented from QProblemB.
References QProblem::A, BT_FALSE, QProblemB::g, QProblem::getNC(), QProblemB::getNV(), QProblemB::H, QProblemB::hessianType, HST_IDENTITY, HST_ZERO, QProblemB::regVal, SUCCESSFUL_RETURN, Matrix::times(), Matrix::transTimes(), QProblemB::usingRegularisation(), QProblemB::x, and QProblemB::y.
Referenced by QProblem::performDriftCorrection(), QProblem::performRamping(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), setupNewAuxiliaryQP(), and QProblem::solveInitialQP().
returnValue QProblem::setupAuxiliaryQPsolution (const real_t *const xOpt, const real_t *const yOpt) [protected, inherited]
Sets up the optimal primal/dual solution of the auxiliary initial QP.
Returns:
SUCCESSFUL_RETURN
Parameters:
xOpt Optimal primal solution vector. If a NULL pointer is passed, all entries are set to zero.
yOpt Optimal dual solution vector. If a NULL pointer is passed, all entries are set to zero.
Reimplemented from QProblemB.
References QProblem::A, QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblem::getNC(), QProblemB::getNV(), SUCCESSFUL_RETURN, Matrix::times(), QProblemB::x, and QProblemB::y.
Referenced by QProblem::solveInitialQP().
returnValue QProblem::setupAuxiliaryWorkingSet (const Bounds *const auxiliaryBounds, const Constraints *const auxiliaryConstraints, BooleanType setupAfresh) [protected, virtual, inherited]
Sets up bound and constraints data structures according to auxiliaryBounds/Constraints. (If the working set shall be setup afresh, make sure that bounds and constraints data structure have been resetted and the TQ factorisation has been initialised!)
Returns:
SUCCESSFUL_RETURN
RET_SETUP_WORKINGSET_FAILED
RET_INVALID_ARGUMENTS
RET_UNKNOWN_BUG
Parameters:
auxiliaryBounds Working set of bounds for auxiliary QP.
auxiliaryConstraints Working set of constraints for auxiliary QP.
setupAfresh Flag indicating if given working set shall be setup afresh or by updating the current one.
Reimplemented in SQProblemSchur.
References QProblem::addBound(), QProblem::addBound_checkLI(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, Options::enableFullLITests, Options::enableNZCTests, Options::epsLITests, QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), Bounds::moveFreeToFixed(), QProblemB::options, real_t, QProblem::removeBound(), QProblem::removeConstraint(), RET_INVALID_ARGUMENTS, RET_LINEARLY_INDEPENDENT, RET_SETUP_WORKINGSET_FAILED, RET_UNKNOWN_BUG, SubjectTo::setType(), ST_BOUNDED, ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UNDEFINED, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::setupAuxiliaryQP(), setupNewAuxiliaryQP(), and QProblem::solveInitialQP().
returnValue QProblem::setupInitialCholesky () [protected, virtual, inherited]
Computes initial Cholesky decomposition of the projected Hessian making use of the function computeCholesky() or computeProjectedCholesky().
Returns:
SUCCESSFUL_RETURN
RET_HESSIAN_NOT_SPD
RET_INDEXLIST_CORRUPTED
Reimplemented from QProblemB.
References BT_TRUE, QProblem::computeProjectedCholesky(), Options::enableRegularisation, QProblemB::getNFR(), QProblemB::getNFV(), QProblemB::getNV(), QProblemB::haveCholesky, QProblemB::options, QProblemB::regulariseHessian(), RET_HESSIAN_NOT_SPD, RET_INIT_FAILED_CHOLESKY, RET_INIT_FAILED_REGULARISATION, and SUCCESSFUL_RETURN.
Referenced by QProblem::hotstart().
returnValue SQProblem::setupNewAuxiliaryQP (SymmetricMatrix * H_new, Matrix * A_new, const real_t * lb_new, const real_t * ub_new, const real_t * lbA_new, const real_t * ubA_new) [protected, virtual]
Sets new matrices and calculates their factorisations. If the current Hessian is trivial (i.e. HST_ZERO or HST_IDENTITY) but a non-trivial one is given, memory for Hessian is allocated and it is set to the given one. Afterwards, all QP vectors are transformed in order to start from an optimal solution.
Returns:
SUCCESSFUL_RETURN
RET_MATRIX_FACTORISATION_FAILED
RET_NO_HESSIAN_SPECIFIED
Parameters:
H_new New Hessian matrix.
If Hessian matrix is trivial, a NULL pointer can be passed.
A_new New constraint matrix.
If QP sequence does not involve constraints, a NULL pointer can be passed.
lb_new New lower bounds.
If no lower bounds exist, a NULL pointer can be passed.
ub_new New upper bounds.
If no lower bounds exist, a NULL pointer can be passed.
lbA_new New lower constraints' bounds.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new New lower constraints' bounds.
If no lower constraints' bounds exist, a NULL pointer can be passed.
References QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::computeProjectedCholesky(), QProblem::constraints, QProblemB::determineHessianType(), QProblem::getNC(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::getStatus(), SubjectTo::getType(), QProblemB::H, QProblemB::hessianType, HST_SEMIDEF, HST_UNKNOWN, HST_ZERO, Bounds::init(), Constraints::init(), Options::initialStatusBounds, QProblem::lbA, QProblemB::options, QPS_AUXILIARYQPSOLVED, QPS_NOTINITIALISED, QPS_PERFORMINGHOMOTOPY, QPS_PREPARINGAUXILIARYQP, QProblemB::regulariseHessian(), QProblemB::regVal, RET_INVALID_ARGUMENTS, RET_NO_HESSIAN_SPECIFIED, RET_SETUP_AUXILIARYQP_FAILED, RET_UPDATEMATRICES_FAILED_AS_QP_NOT_SOLVED, QProblem::setA(), QProblemB::setH(), SubjectTo::setStatus(), Bounds::setupAllFree(), Constraints::setupAllInactive(), QProblem::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryWorkingSet(), QProblem::setupSubjectToType(), QProblem::setupTQfactorisation(), ST_BOUNDED, ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UPPER, QProblemB::status, SUCCESSFUL_RETURN, THROWERROR, QProblem::ubA, QProblemB::usingRegularisation(), and QProblemB::y.
Referenced by hotstart(), and setupNewAuxiliaryQP().
returnValue SQProblem::setupNewAuxiliaryQP (const real_t *const H_new, const real_t *const A_new, const real_t * lb_new, const real_t * ub_new, const real_t * lbA_new, const real_t * ubA_new) [protected, virtual]
Sets new matrices and calculates their factorisations. If the current Hessian is trivial (i.e. HST_ZERO or HST_IDENTITY) but a non-trivial one is given, memory for Hessian is allocated and it is set to the given one. Afterwards, all QP vectors are transformed in order to start from an optimal solution.
Returns:
SUCCESSFUL_RETURN
RET_MATRIX_FACTORISATION_FAILED
RET_NO_HESSIAN_SPECIFIED
Parameters:
H_new New Hessian matrix.
If Hessian matrix is trivial, a NULL pointer can be passed.
A_new New constraint matrix.
If QP sequence does not involve constraints, a NULL pointer can be passed.
lb_new New lower bounds.
If no lower bounds exist, a NULL pointer can be passed.
ub_new New upper bounds.
If no lower bounds exist, a NULL pointer can be passed.
lbA_new New lower constraints' bounds.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new New lower constraints' bounds.
If no lower constraints' bounds exist, a NULL pointer can be passed.
References BT_TRUE, QProblem::freeConstraintMatrix, QProblemB::freeHessian, QProblem::getNC(), QProblemB::getNV(), real_t, RET_INVALID_ARGUMENTS, setupNewAuxiliaryQP(), and THROWERROR.
returnValue QProblemB::setupQPdata (SymmetricMatrix * _H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub) [protected, inherited]
Sets up internal QP data.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
_H Hessian matrix.
_g Gradient vector.
_lb Lower bounds (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bounds (on variables).
If no upper bounds exist, a NULL pointer can be passed.
References RET_INVALID_ARGUMENTS, QProblemB::setG(), QProblemB::setH(), QProblemB::setLB(), QProblemB::setUB(), SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblemB::init(), and QProblem::setupQPdata().
returnValue QProblemB::setupQPdata (const real_t *const _H, const real_t *const _g, const real_t *const _lb, const real_t *const _ub) [protected, inherited]
Sets up internal QP data. If the current Hessian is trivial (i.e. HST_ZERO or HST_IDENTITY) but a non-trivial one is given, memory for Hessian is allocated and it is set to the given one.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
RET_NO_HESSIAN_SPECIFIED
Parameters:
_H Hessian matrix.
If Hessian matrix is trivial,a NULL pointer can be passed.
_g Gradient vector.
_lb Lower bounds (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bounds (on variables).
If no upper bounds exist, a NULL pointer can be passed.
References RET_INVALID_ARGUMENTS, QProblemB::setG(), QProblemB::setH(), QProblemB::setLB(), QProblemB::setUB(), SUCCESSFUL_RETURN, and THROWERROR.
returnValue QProblem::setupQPdata (SymmetricMatrix * _H, const real_t *const _g, Matrix * _A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA) [protected, inherited]
Sets up internal QP data.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
RET_UNKNONW_BUG
Parameters:
_H Hessian matrix.
If Hessian matrix is trivial,a NULL pointer can be passed.
_g Gradient vector.
_A Constraint matrix.
_lb Lower bound vector (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bound vector (on variables).
If no upper bounds exist, a NULL pointer can be passed.
_lbA Lower constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
_ubA Upper constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
References getMax(), getMin(), QProblem::getNC(), QProblemB::getNV(), RET_INVALID_ARGUMENTS, QProblem::setA(), QProblem::setLBA(), QProblem::setUBA(), QProblemB::setupQPdata(), SUCCESSFUL_RETURN, THROWERROR, and Matrix::writeToFile().
Referenced by QProblem::init().
returnValue QProblem::setupQPdata (const real_t *const _H, const real_t *const _g, const real_t *const _A, const real_t *const _lb, const real_t *const _ub, const real_t *const _lbA, const real_t *const _ubA) [protected, inherited]
Sets up dense internal QP data. If the current Hessian is trivial (i.e. HST_ZERO or HST_IDENTITY) but a non-trivial one is given, memory for Hessian is allocated and it is set to the given one.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
RET_UNKNONW_BUG
Parameters:
_H Hessian matrix.
If Hessian matrix is trivial,a NULL pointer can be passed.
_g Gradient vector.
_A Constraint matrix.
_lb Lower bound vector (on variables).
If no lower bounds exist, a NULL pointer can be passed.
_ub Upper bound vector (on variables).
If no upper bounds exist, a NULL pointer can be passed.
_lbA Lower constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
_ubA Upper constraints' bound vector.
If no lower constraints' bounds exist, a NULL pointer can be passed.
References QProblem::getNC(), RET_INVALID_ARGUMENTS, QProblem::setA(), QProblem::setLBA(), QProblem::setUBA(), QProblemB::setupQPdata(), SUCCESSFUL_RETURN, and THROWERROR.
returnValue QProblemB::setupQPdataFromFile (const char *const H_file, const char *const g_file, const char *const lb_file, const char *const ub_file) [protected, inherited]
Sets up internal QP data by loading it from files. If the current Hessian is trivial (i.e. HST_ZERO or HST_IDENTITY) but a non-trivial one is given, memory for Hessian is allocated and it is set to the given one.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
RET_NO_HESSIAN_SPECIFIED
Parameters:
H_file Name of file where Hessian matrix, of neighbouring QP to be solved, is stored.
If Hessian matrix is trivial,a NULL pointer can be passed.
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
References Matrix::doFreeMemory(), QProblemB::g, QProblemB::getNV(), QProblemB::H, INFTY, QProblemB::lb, readFromFile(), real_t, RET_INVALID_ARGUMENTS, QProblemB::setH(), SUCCESSFUL_RETURN, THROWERROR, and QProblemB::ub.
Referenced by QProblemB::init().
returnValue QProblem::setupQPdataFromFile (const char *const H_file, const char *const g_file, const char *const A_file, const char *const lb_file, const char *const ub_file, const char *const lbA_file, const char *const ubA_file) [protected, inherited]
Sets up internal QP data by loading it from files. If the current Hessian is trivial (i.e. HST_ZERO or HST_IDENTITY) but a non-trivial one is given, memory for Hessian is allocated and it is set to the given one.
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
RET_UNABLE_TO_READ_FILE
RET_INVALID_ARGUMENTS
RET_UNKNONW_BUG
Parameters:
H_file Name of file where Hessian matrix, of neighbouring QP to be solved, is stored.
If Hessian matrix is trivial,a NULL pointer can be passed.
g_file Name of file where gradient, of neighbouring QP to be solved, is stored.
A_file Name of file where constraint matrix, of neighbouring QP to be solved, is stored.
lb_file Name of file where lower bounds, of neighbouring QP to be solved, is stored.
If no lower bounds exist, a NULL pointer can be passed.
ub_file Name of file where upper bounds, of neighbouring QP to be solved, is stored.
If no upper bounds exist, a NULL pointer can be passed.
lbA_file Name of file where lower constraints' bounds, of neighbouring QP to be solved, is stored.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_file Name of file where upper constraints' bounds, of neighbouring QP to be solved, is stored.
If no upper constraints' bounds exist, a NULL pointer can be passed.
References QProblem::A, Matrix::doFreeMemory(), QProblem::getNC(), QProblemB::getNV(), INFTY, QProblem::lbA, readFromFile(), real_t, RET_INVALID_ARGUMENTS, QProblem::setA(), SUCCESSFUL_RETURN, THROWERROR, and QProblem::ubA.
Referenced by QProblem::init().
returnValue QProblemB::setupSubjectToType (const real_t *const lb_new, const real_t *const ub_new) [protected, virtual, inherited]
Determines type of new constraints and bounds (i.e. implicitly fixed, unbounded etc.).
Returns:
SUCCESSFUL_RETURN
RET_SETUPSUBJECTTOTYPE_FAILED
Parameters:
lb_new New lower bounds.
ub_new New upper bounds.
References QProblemB::bounds, Options::boundTolerance, BT_FALSE, BT_TRUE, Options::enableEqualities, Options::enableFarBounds, QProblemB::getNV(), INFTY, QProblemB::lb, QProblemB::options, SubjectTo::setNoLower(), SubjectTo::setNoUpper(), SubjectTo::setType(), ST_BOUNDED, ST_EQUALITY, ST_UNBOUNDED, SUCCESSFUL_RETURN, and QProblemB::ub.
returnValue QProblem::setupSubjectToType () [protected, virtual, inherited]
Determines type of existing constraints and bounds (i.e. implicitly fixed, unbounded etc.).
Returns:
SUCCESSFUL_RETURN
RET_SETUPSUBJECTTOTYPE_FAILED
Reimplemented from QProblemB.
References QProblemB::lb, QProblem::lbA, QProblemB::ub, and QProblem::ubA.
Referenced by SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), setupNewAuxiliaryQP(), and QProblem::solveInitialQP().
returnValue QProblem::setupSubjectToType (const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new) [protected, virtual, inherited]
Parameters:
lb_new New lower bounds.
ub_new New upper bounds.
lbA_new New lower constraints' bounds.
ubA_new New upper constraints' bounds.
References Options::boundTolerance, BT_FALSE, BT_TRUE, QProblem::constraints, Options::enableEqualities, Options::enableFarBounds, QProblem::getNC(), SubjectTo::getType(), INFTY, QProblem::lbA, QProblemB::options, RET_SETUPSUBJECTTOTYPE_FAILED, SubjectTo::setNoLower(), SubjectTo::setNoUpper(), SubjectTo::setType(), QProblemB::setupSubjectToType(), ST_BOUNDED, ST_DISABLED, ST_EQUALITY, ST_UNBOUNDED, SUCCESSFUL_RETURN, THROWERROR, and QProblem::ubA.
returnValue QProblem::setupTQfactorisation () [protected, virtual, inherited]
Initialises TQ factorisation of A (i.e. A*Q = [0 T]) if NO constraint is active.
Returns:
SUCCESSFUL_RETURN
RET_INDEXLIST_CORRUPTED
Reimplemented in SQProblemSchur.
References QProblemB::bounds, Bounds::getFree(), QProblemB::getNFR(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::Q, QQ, QProblem::sizeT, SUCCESSFUL_RETURN, and QProblem::T.
Referenced by QProblem::setupAuxiliaryQP(), setupNewAuxiliaryQP(), and QProblem::solveInitialQP().
BooleanType QProblem::shallRefactorise (const Bounds *const guessedBounds, const Constraints *const guessedConstraints) const [protected, inherited]
Determines if it is more efficient to refactorise the matrices when hotstarting or not (i.e. better to update the existing factorisations).
Returns:
BT_TRUE iff matrices shall be refactorised afresh
Parameters:
guessedBounds Guessed new working set of bounds.
guessedConstraints Guessed new working set of constraints.
References QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, Constraints::getNAC(), QProblem::getNC(), Bounds::getNFX(), QProblemB::getNV(), SubjectTo::getStatus(), QProblemB::hessianType, HST_INDEF, and HST_SEMIDEF.
Referenced by QProblem::setupAuxiliaryQP().
returnValue QProblem::solveCurrentEQP (const int_t n_rhs, const real_t * g_in, const real_t * lb_in, const real_t * ub_in, const real_t * lbA_in, const real_t * ubA_in, real_t * x_out, real_t * y_out) [inherited]
Solves an equality-constrained QP problem resulting from the current working set.
Returns:
SUCCESSFUL_RETURN
RET_STEPDIRECTION_FAILED_TQ
RET_STEPDIRECTION_FAILED_CHOLESKY
RET_INVALID_ARGUMENTS
Parameters:
n_rhs Number of consecutive right hand sides
g_in Gradient of neighbouring QP to be solved.
lb_in Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_in Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
lbA_in Lower constraints' bounds of neighbouring QP to be solved.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_in Upper constraints' bounds of neighbouring QP to be solved.
x_out Output: Primal solution
y_out Output: Dual solution
References QProblemB::bounds, BT_FALSE, QProblem::constraints, QProblem::determineStepDirection(), Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), Indexlist::getNumberArray(), QProblemB::getNV(), real_t, RET_INVALID_ARGUMENTS, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by main().
returnValue QProblem::solveInitialQP (const real_t *const xOpt, const real_t *const yOpt, const Bounds *const guessedBounds, const Constraints *const guessedConstraints, const real_t *const _R, int_t & nWSR, real_t *const cputime) [protected, inherited]
Solves a QProblem whose QP data is assumed to be stored in the member variables. A guess for its primal/dual optimal solution vectors and the corresponding working sets of bounds and constraints can be provided. Note: This function is internally called by all init functions!
Returns:
SUCCESSFUL_RETURN
RET_INIT_FAILED
RET_INIT_FAILED_CHOLESKY
RET_INIT_FAILED_TQ
RET_INIT_FAILED_HOTSTART
RET_INIT_FAILED_INFEASIBILITY
RET_INIT_FAILED_UNBOUNDEDNESS
RET_MAX_NWSR_REACHED
Parameters:
xOpt Optimal primal solution vector.
yOpt Optimal dual solution vector.
guessedBounds Optimal working set of bounds for solution (xOpt,yOpt).
guessedConstraints Optimal working set of constraints for solution (xOpt,yOpt).
_R Pre-computed (upper triangular) Cholesky factor of Hessian matrix.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
References QProblemB::bounds, BT_FALSE, BT_TRUE, QProblem::constraints, QProblemB::determineHessianType(), Options::enableRamping, QProblemB::g, getCPUtime(), QProblem::getNC(), QProblemB::getNV(), QProblemB::haveCholesky, QProblemB::hessianType, QProblem::hotstart(), HST_SEMIDEF, HST_ZERO, Options::initialStatusBounds, QProblemB::isInfeasible(), QProblemB::isUnbounded(), QProblemB::lb, QProblem::lbA, QProblem::obtainAuxiliaryWorkingSet(), QProblemB::options, QProblem::performRamping(), QPS_AUXILIARYQPSOLVED, QPS_NOTINITIALISED, QPS_PREPARINGAUXILIARYQP, QProblemB::R, real_t, QProblemB::regulariseHessian(), RET_INIT_FAILED, RET_INIT_FAILED_HOTSTART, RET_INIT_FAILED_INFEASIBILITY, RET_INIT_FAILED_REGULARISATION, RET_INIT_FAILED_TQ, RET_INIT_FAILED_UNBOUNDEDNESS, RET_INIT_SUCCESSFUL, RET_MAX_NWSR_REACHED, RET_NO_CHOLESKY_WITH_INITIAL_GUESS, RR, Bounds::setupAllFree(), Constraints::setupAllInactive(), QProblem::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), QProblem::setupAuxiliaryWorkingSet(), QProblem::setupSubjectToType(), QProblem::setupTQfactorisation(), ST_INACTIVE, QProblemB::status, SUCCESSFUL_RETURN, THROWERROR, THROWINFO, THROWWARNING, QProblemB::ub, and QProblem::ubA.
Referenced by QProblem::init().
returnValue QProblem::solveQP (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t & nWSR, real_t *const cputime, int_t nWSRperformed = 0, BooleanType isFirstCall = BT_TRUE) [protected, inherited]
Solves QProblem using online active set strategy. Note: This function is internally called by all hotstart functions!
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
Parameters:
g_new Gradient of neighbouring QP to be solved.
lb_new Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_new Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
lbA_new Lower constraints' bounds of neighbouring QP to be solved.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new Upper constraints' bounds of neighbouring QP to be solved.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
nWSRperformed Number of working set recalculations already performed to solve this QP within previous solveQP() calls. This number is always zero, except for successive calls from solveRegularisedQP() or when using the far bound strategy.
isFirstCall Indicating whether this is the first call for current QP.
References __FILE__, __FUNC__, __LINE__, BT_FALSE, BT_TRUE, QProblem::changeActiveSet(), QProblem::computeProjectedCholesky(), QProblem::determineDataShift(), QProblem::determineStepDirection(), Options::enableCholeskyRefactorisation, Options::enableDriftCorrection, Options::enableRamping, EPS, TabularOutput::excAddB, TabularOutput::excAddC, TabularOutput::excRemB, TabularOutput::excRemC, getCPUtime(), getGlobalMessageHandler(), QProblem::getNC(), QProblemB::getNV(), QProblem::getRelativeHomotopyLength(), QProblemB::getStatus(), TabularOutput::idxAddB, TabularOutput::idxAddC, TabularOutput::idxRemB, TabularOutput::idxRemC, QProblemB::infeasible, QProblemB::isCPUtimeLimitExceeded(), QProblemB::isInfeasible(), MAX_STRING_LENGTH, QProblemB::options, QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), PL_HIGH, QProblem::printIteration(), Options::printLevel, QPS_HOMOTOPYQPSOLVED, QPS_NOTINITIALISED, QPS_PERFORMINGHOMOTOPY, QPS_PREPARINGAUXILIARYQP, QPS_SOLVED, real_t, RET_HOMOTOPY_STEP_FAILED, RET_HOTSTART_FAILED, RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED, RET_HOTSTART_STOPPED_INFEASIBILITY, RET_HOTSTART_STOPPED_UNBOUNDEDNESS, RET_ITERATION_STARTED, RET_MAX_NWSR_REACHED, RET_OPTIMAL_SOLUTION_FOUND, RET_PRINT_ITERATION_FAILED, RET_SHIFT_DETERMINATION_FAILED, RET_STEPDIRECTION_DETERMINATION_FAILED, RET_STEPLENGTH_DETERMINATION_FAILED, QProblemB::setInfeasibilityFlag(), ST_UNDEFINED, QProblemB::status, SUCCESSFUL_RETURN, QProblemB::tabularOutput, QProblemB::tau, Options::terminationTolerance, THROWERROR, MessageHandling::throwInfo(), THROWINFO, MessageHandling::throwWarning(), QProblemB::unbounded, QProblem::updateActivitiesForHotstart(), and VS_VISIBLE.
Referenced by QProblem::solveRegularisedQP().
returnValue QProblem::solveRegularisedQP (const real_t *const g_new, const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new, int_t & nWSR, real_t *const cputime, int_t nWSRperformed = 0, BooleanType isFirstCall = BT_TRUE) [protected, inherited]
Solves QProblem using online active set strategy. Note: This function is internally called by all hotstart functions!
Returns:
SUCCESSFUL_RETURN
RET_MAX_NWSR_REACHED
RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED
RET_HOTSTART_FAILED
RET_SHIFT_DETERMINATION_FAILED
RET_STEPDIRECTION_DETERMINATION_FAILED
RET_STEPLENGTH_DETERMINATION_FAILED
RET_HOMOTOPY_STEP_FAILED
RET_HOTSTART_STOPPED_INFEASIBILITY
RET_HOTSTART_STOPPED_UNBOUNDEDNESS
Parameters:
g_new Gradient of neighbouring QP to be solved.
lb_new Lower bounds of neighbouring QP to be solved.
If no lower bounds exist, a NULL pointer can be passed.
ub_new Upper bounds of neighbouring QP to be solved.
If no upper bounds exist, a NULL pointer can be passed.
lbA_new Lower constraints' bounds of neighbouring QP to be solved.
If no lower constraints' bounds exist, a NULL pointer can be passed.
ubA_new Upper constraints' bounds of neighbouring QP to be solved.
If no upper constraints' bounds exist, a NULL pointer can be passed.
nWSR Input: Maximum number of working set recalculations;
Output: Number of performed working set recalculations.
cputime Input: Maximum CPU time allowed for QP solution.
Output: CPU time spent for QP solution (or to perform nWSR iterations).
nWSRperformed Number of working set recalculations already performed to solve this QP within previous solveRegularisedQP() calls. This number is always zero, except for successive calls when using the far bound strategy.
isFirstCall Indicating whether this is the first call for current QP.
References BT_FALSE, QProblemB::g, QProblemB::getNV(), Options::numRegularisationSteps, QProblemB::options, real_t, QProblemB::regVal, RET_FEWER_REGSTEPS_NWSR, RET_MAX_NWSR_REACHED, RET_NO_REGSTEP_NWSR, QProblem::solveQP(), SUCCESSFUL_RETURN, THROWWARNING, QProblemB::usingRegularisation(), and QProblemB::x.
Referenced by QProblem::hotstart().
returnValue QProblem::updateActivitiesForHotstart (const real_t *const lb_new, const real_t *const ub_new, const real_t *const lbA_new, const real_t *const ubA_new) [protected, virtual, inherited]
Update activities in a hot start if some of the bounds have become infinity or if variables have become fixed.
Parameters:
lb_new New lower bounds.
ub_new New upper bounds.
lbA_new New lower constraints' bounds.
ubA_new New upper constraints' bounds.
References QProblem::addBound(), QProblem::addBound_checkLI(), Options::boundRelaxation, QProblemB::bounds, BT_FALSE, BT_TRUE, Options::enableNZCTests, QProblemB::g, QProblemB::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), INFTY, QProblemB::lb, QProblemB::options, QProblem::removeBound(), RET_LINEARLY_INDEPENDENT, RET_SETUPSUBJECTTOTYPE_FAILED, QProblemB::setupSubjectToType(), ST_EQUALITY, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, THROWERROR, QProblemB::ub, QProblemB::x, and QProblemB::y.
Referenced by QProblem::solveQP().
returnValue QProblemB::updateFarBounds (real_t curFarBound, int_t nRamp, const real_t *const lb_new, real_t *const lb_new_far, const real_t *const ub_new, real_t *const ub_new_far) const [protected, inherited]
...
Parameters:
curFarBound ...
nRamp ...
lb_new ...
lb_new_far ...
ub_new ...
ub_new_far ...
References BT_TRUE, Options::enableRamping, getMax(), getMin(), QProblemB::getNV(), QProblemB::options, QProblemB::ramp0, QProblemB::ramp1, QProblemB::rampOffset, real_t, and SUCCESSFUL_RETURN.
Referenced by QProblemB::hotstart().
returnValue QProblem::updateFarBounds (real_t curFarBound, int_t nRamp, const real_t *const lb_new, real_t *const lb_new_far, const real_t *const ub_new, real_t *const ub_new_far, const real_t *const lbA_new, real_t *const lbA_new_far, const real_t *const ubA_new, real_t *const ubA_new_far) const [protected, inherited]
...
Parameters:
curFarBound ...
nRamp ...
lb_new ...
lb_new_far ...
ub_new ...
ub_new_far ...
lbA_new ...
lbA_new_far ...
ubA_new ...
ubA_new_far ...
References BT_TRUE, Options::enableRamping, getMax(), getMin(), QProblem::getNC(), QProblemB::getNV(), QProblemB::options, QProblemB::ramp0, QProblemB::ramp1, QProblemB::rampOffset, real_t, and SUCCESSFUL_RETURN.
Referenced by QProblem::hotstart().
BooleanType QProblemB::usingRegularisation () const [inline, inherited]
Returns if the QP has been internally regularised.
Returns:
BT_TRUE: Hessian is internally regularised for QP solution
BT_FALSE: No internal Hessian regularisation is used for QP solution
References BT_FALSE, BT_TRUE, QProblemB::regVal, and ZERO.
Referenced by QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SolutionAnalysis::getKktViolation(), QProblemB::getObjVal(), QProblemB::regulariseHessian(), QProblemB::removeBound(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), setupNewAuxiliaryQP(), QProblem::solveRegularisedQP(), and QProblemB::solveRegularisedQP().
returnValue QProblem::writeQpDataIntoMatFile (const char *const filename) const [inherited]
...
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
Parameters:
filename Mat file name.
References QProblem::A, Matrix::full(), QProblemB::g, QProblem::getNC(), QProblemB::getNV(), QProblemB::H, QProblemB::lb, QProblem::lbA, real_t, RET_NOT_YET_IMPLEMENTED, RET_UNABLE_TO_OPEN_FILE, SUCCESSFUL_RETURN, QProblemB::ub, QProblem::ubA, and writeIntoMatFile().
returnValue QProblem::writeQpWorkspaceIntoMatFile (const char *const filename) [inherited]
...
Returns:
SUCCESSFUL_RETURN
RET_UNABLE_TO_OPEN_FILE
Parameters:
filename Mat file name.
References QProblem::Ax, QProblem::Ax_l, QProblem::Ax_u, QProblemB::bounds, QProblem::constraints, Constraints::getActive(), Bounds::getFixed(), Bounds::getFree(), Constraints::getInactive(), QProblem::getNAC(), QProblem::getNC(), QProblemB::getNFR(), QProblemB::getNFX(), QProblem::getNIAC(), Indexlist::getNumberArray(), QProblemB::getNV(), QProblem::Q, RET_NOT_YET_IMPLEMENTED, RET_UNABLE_TO_OPEN_FILE, QProblem::sizeT, SUCCESSFUL_RETURN, QProblem::T, and writeIntoMatFile().
Member Data Documentation
Matrix* QProblem::A [protected, inherited]
Constraint matrix.
Referenced by QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), QProblem::addConstraint_ensureLI(), QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblem::performStep(), QProblem::printIteration(), QProblem::QProblem(), SQProblemSchur::removeBound(), QProblem::removeBound(), SQProblemSchur::resetSchurComplement(), QProblem::setA(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), QProblem::setupQPdataFromFile(), and QProblem::writeQpDataIntoMatFile().
real_t* QProblem::Ax [protected, inherited]
Stores the current A*x
(for increased efficiency only).
Referenced by QProblem::clear(), QProblem::copy(), QProblem::ensureNonzeroCurvature(), QProblem::hotstart(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::QProblem(), QProblem::setA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPsolution(), setupNewAuxiliaryQP(), and QProblem::writeQpWorkspaceIntoMatFile().
real_t* QProblem::Ax_l [protected, inherited]
Stores the current distance to lower constraints' bounds A*x-lbA
(for increased efficiency only).
Referenced by QProblem::clear(), QProblem::copy(), QProblem::ensureNonzeroCurvature(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::QProblem(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), QProblem::setA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPsolution(), setupNewAuxiliaryQP(), and QProblem::writeQpWorkspaceIntoMatFile().
real_t* QProblem::Ax_u [protected, inherited]
Stores the current distance to lower constraints' bounds ubA-A*x
(for increased efficiency only).
Referenced by QProblem::clear(), QProblem::copy(), QProblem::ensureNonzeroCurvature(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::QProblem(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), QProblem::setA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPsolution(), setupNewAuxiliaryQP(), and QProblem::writeQpWorkspaceIntoMatFile().
Bounds QProblemB::bounds [protected, inherited]
Data structure for problem's bounds.
Referenced by SQProblemSchur::addBound(), QProblem::addBound(), QProblemB::addBound(), SQProblemSchur::addBound_checkLISchur(), SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblemB::copy(), SQProblemSchur::correctInertia(), QProblemB::determineDataShift(), QProblem::determineDataShift(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), QProblemB::getBounds(), QProblem::getFreeVariablesFlags(), QProblemB::getNFR(), QProblemB::getNFV(), QProblemB::getNFX(), QProblemB::getNV(), SolutionAnalysis::getVarianceCovariance(), QProblemB::getWorkingSetBounds(), QProblem::hotstart(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::QProblemB(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), SQProblemSchur::repairSingularWorkingSet(), QProblemB::reset(), SQProblemSchur::resetSchurComplement(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupAuxiliaryWorkingSet(), setupNewAuxiliaryQP(), QProblemB::setupSubjectToType(), QProblem::setupTQfactorisation(), QProblem::shallRefactorise(), QProblemB::shallRefactorise(), QProblem::solveCurrentEQP(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::updateActivitiesForHotstart(), and QProblem::writeQpWorkspaceIntoMatFile().
ConstraintProduct* QProblem::constraintProduct [protected, inherited]
Pointer to user-defined constraint product function.
Referenced by SQProblemSchur::addConstraint(), QProblem::copy(), QProblem::performStep(), QProblem::QProblem(), SQProblemSchur::removeBound(), QProblem::reset(), SQProblemSchur::resetSchurComplement(), and QProblem::setConstraintProduct().
Constraints QProblem::constraints [protected, inherited]
Data structure for problem's constraints.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::computeProjectedCholesky(), QProblem::copy(), QProblem::determineDataShift(), QProblem::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), QProblem::getConstraints(), QProblem::getNAC(), QProblem::getNC(), QProblem::getNEC(), QProblem::getNIAC(), SolutionAnalysis::getVarianceCovariance(), QProblem::getWorkingSetConstraints(), QProblem::hotstart(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::printProperties(), QProblem::QProblem(), QProblem::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), SQProblemSchur::repairSingularWorkingSet(), QProblem::reset(), SQProblemSchur::resetSchurComplement(), QProblem::setA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::setupAuxiliaryWorkingSet(), setupNewAuxiliaryQP(), QProblem::setupSubjectToType(), QProblem::shallRefactorise(), QProblem::solveCurrentEQP(), QProblem::solveInitialQP(), and QProblem::writeQpWorkspaceIntoMatFile().
uint_t QProblemB::count [protected, inherited]
Counts the number of hotstart function calls.
Referenced by QProblemB::copy(), QProblemB::getCount(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), and QProblemB::resetCounter().
real_t* QProblemB::delta_xFR_TMP [protected, inherited]
Temporary for determineStepDirection
Referenced by QProblemB::clear(), QProblemB::copy(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), and QProblemB::QProblemB().
real_t* QProblem::delta_xFRy [protected, inherited]
Temporary for determineStepDirection.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), and QProblem::QProblem().
real_t* QProblem::delta_xFRz [protected, inherited]
Temporary for determineStepDirection.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), and QProblem::QProblem().
real_t* QProblem::delta_yAC_TMP [protected, inherited]
Temporary for determineStepDirection.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), and QProblem::QProblem().
Flipper QProblemB::flipper [protected, inherited]
Struct for making a temporary copy of the matrix factorisations.
Referenced by QProblemB::copy(), QProblem::QProblem(), QProblemB::QProblemB(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), QProblem::reset(), and QProblemB::reset().
BooleanType QProblem::freeConstraintMatrix [protected, inherited]
Flag indicating whether the constraint matrix needs to be de-allocated.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::QProblem(), QProblem::setA(), and setupNewAuxiliaryQP().
BooleanType QProblemB::freeHessian [protected, inherited]
Flag indicating whether the Hessian matrix needs to be de-allocated.
Referenced by QProblemB::clear(), QProblemB::copy(), QProblemB::QProblemB(), QProblemB::setH(), and setupNewAuxiliaryQP().
real_t* QProblemB::g [protected, inherited]
Gradient.
Referenced by QProblemB::clear(), QProblemB::copy(), QProblemB::determineDataShift(), SolutionAnalysis::getKktViolation(), QProblemB::getObjVal(), QProblemB::getRelativeHomotopyLength(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), QProblemB::regulariseHessian(), QProblemB::setG(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), QProblemB::setupQPdataFromFile(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::solveRegularisedQP(), QProblemB::solveRegularisedQP(), QProblem::updateActivitiesForHotstart(), and QProblem::writeQpDataIntoMatFile().
SymmetricMatrix* QProblemB::H [protected, inherited]
Hessian matrix.
Referenced by QProblemB::clear(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblemB::copy(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SolutionAnalysis::getKktViolation(), QProblemB::getObjVal(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), QProblemB::regulariseHessian(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), SQProblemSchur::resetSchurComplement(), QProblemB::setH(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), setupNewAuxiliaryQP(), QProblemB::setupQPdataFromFile(), and QProblem::writeQpDataIntoMatFile().
BooleanType QProblemB::haveCholesky [protected, inherited]
Flag indicating whether Cholesky decomposition has already been setup.
Referenced by QProblemB::copy(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::QProblemB(), QProblemB::reset(), QProblemB::setupInitialCholesky(), QProblem::setupInitialCholesky(), QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
HessianType QProblemB::hessianType [protected, inherited]
Type of Hessian matrix.
Referenced by QProblem::addBound(), QProblemB::addBound(), QProblem::addConstraint(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblemB::copy(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblemB::getHessianType(), QProblemB::getObjVal(), QProblem::printIteration(), QProblemB::printIteration(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::QProblemB(), QProblemB::regulariseHessian(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), QProblemB::reset(), SQProblemSchur::resetSchurComplement(), QProblemB::setH(), QProblemB::setHessianType(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), setupNewAuxiliaryQP(), QProblem::shallRefactorise(), QProblemB::shallRefactorise(), QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
BooleanType QProblemB::infeasible [protected, inherited]
QP infeasible?
Referenced by QProblemB::copy(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::isInfeasible(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::QProblemB(), QProblemB::reset(), QProblemB::setInfeasibilityFlag(), QProblem::solveQP(), and QProblemB::solveQP().
real_t* QProblemB::lb [protected, inherited]
Lower bound vector (on variables).
Referenced by QProblemB::clear(), QProblemB::copy(), SQProblemSchur::correctInertia(), QProblemB::determineDataShift(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblemB::getRelativeHomotopyLength(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::repairSingularWorkingSet(), QProblemB::setLB(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblemB::setupQPdataFromFile(), QProblemB::setupSubjectToType(), QProblem::setupSubjectToType(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::updateActivitiesForHotstart(), and QProblem::writeQpDataIntoMatFile().
real_t* QProblem::lbA [protected, inherited]
Lower constraints' bound vector.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineDataShift(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblem::getRelativeHomotopyLength(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::printIteration(), QProblem::QProblem(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), QProblem::setA(), QProblem::setLBA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), setupNewAuxiliaryQP(), QProblem::setupQPdataFromFile(), QProblem::setupSubjectToType(), QProblem::solveInitialQP(), and QProblem::writeQpDataIntoMatFile().
Options QProblemB::options [protected, inherited]
Struct containing all user-defined options for solving QPs.
Referenced by SQProblemSchur::addBound(), QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), SQProblemSchur::addToSchurComplement(), QProblem::changeActiveSet(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblemB::copy(), SQProblemSchur::correctInertia(), SQProblemSchur::deleteFromSchurComplement(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), QProblemB::getOptions(), QProblemB::getPrintLevel(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::printOptions(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::QProblemB(), QProblemB::regulariseHessian(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), SQProblemSchur::repairSingularWorkingSet(), QProblemB::reset(), SQProblemSchur::resetSchurComplement(), QProblemB::setInfeasibilityFlag(), QProblemB::setOptions(), QProblemB::setPrintLevel(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupInitialCholesky(), QProblem::setupInitialCholesky(), setupNewAuxiliaryQP(), QProblemB::setupSubjectToType(), QProblem::setupSubjectToType(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::solveQP(), QProblemB::solveQP(), QProblem::solveRegularisedQP(), QProblemB::solveRegularisedQP(), SQProblemSchur::undoDeleteFromSchurComplement(), QProblem::updateActivitiesForHotstart(), QProblemB::updateFarBounds(), QProblem::updateFarBounds(), and SQProblemSchur::updateSchurQR().
real_t* QProblem::Q [protected, inherited]
Orthonormal quadratic matrix, A = [0 T]*Q'.
Referenced by QProblem::clear(), QProblem::computeProjectedCholesky(), QProblem::copy(), QProblem::QProblem(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::reset(), QProblem::setupTQfactorisation(), and QProblem::writeQpWorkspaceIntoMatFile().
real_t* QProblemB::R [protected, inherited]
Cholesky factor of H (i.e. H = R^T*R).
Referenced by QProblemB::clear(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblemB::copy(), QProblemB::init(), QProblem::init(), QProblemB::QProblemB(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), QProblemB::reset(), QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
real_t QProblemB::ramp0 [protected, inherited]
Start value for Ramping Strategy.
Referenced by QProblemB::copy(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::QProblemB(), QProblemB::reset(), QProblemB::updateFarBounds(), and QProblem::updateFarBounds().
real_t QProblemB::ramp1 [protected, inherited]
Final value for Ramping Strategy.
Referenced by QProblemB::copy(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::QProblemB(), QProblemB::reset(), QProblemB::updateFarBounds(), and QProblem::updateFarBounds().
int_t QProblemB::rampOffset [protected, inherited]
Offset index for Ramping.
Referenced by QProblemB::copy(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::QProblemB(), QProblemB::reset(), QProblemB::updateFarBounds(), and QProblem::updateFarBounds().
real_t QProblemB::regVal [protected, inherited]
Holds the offset used to regularise Hessian matrix (zero by default).
Referenced by QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblemB::copy(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SolutionAnalysis::getKktViolation(), QProblemB::getObjVal(), QProblem::printIteration(), QProblemB::QProblemB(), QProblemB::regulariseHessian(), QProblemB::removeBound(), QProblemB::reset(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), setupNewAuxiliaryQP(), QProblem::solveRegularisedQP(), QProblemB::solveRegularisedQP(), and QProblemB::usingRegularisation().
int_t QProblem::sizeT [protected, inherited]
Matrix T is stored in a (sizeT x sizeT) array.
Referenced by QProblem::addBound(), QProblem::addConstraint(), QProblem::backsolveT(), QProblem::copy(), QProblem::printIteration(), QProblem::QProblem(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::reset(), QProblem::setupTQfactorisation(), and QProblem::writeQpWorkspaceIntoMatFile().
QProblemStatus QProblemB::status [protected, inherited]
Current status of the solution process.
Referenced by SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblemB::copy(), QProblemB::getStatus(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::isInitialised(), QProblemB::isSolved(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::QProblemB(), QProblemB::reset(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), setupNewAuxiliaryQP(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::solveQP(), and QProblemB::solveQP().
real_t* QProblem::T [protected, inherited]
Reverse triangular matrix, A = [0 T]*Q'.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::QProblem(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::reset(), QProblem::setupTQfactorisation(), and QProblem::writeQpWorkspaceIntoMatFile().
TabularOutput QProblemB::tabularOutput [protected, inherited]
Struct storing information for tabular output (printLevel == PL_TABULAR).
Referenced by SQProblemSchur::addBound(), QProblem::addBound(), QProblemB::addBound(), SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint(), QProblem::addConstraint(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::printIteration(), QProblemB::printIteration(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), QProblem::solveQP(), and QProblemB::solveQP().
real_t QProblemB::tau [protected, inherited]
Last homotopy step length.
Referenced by QProblemB::copy(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), QProblemB::reset(), QProblem::solveQP(), and QProblemB::solveQP().
real_t* QProblem::tempA [protected, inherited]
Temporary for determineStepDirection.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), and QProblem::QProblem().
real_t* QProblem::tempB [protected, inherited]
Temporary for determineStepDirection.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), and QProblem::QProblem().
real_t* QProblem::tempC [protected, inherited]
Temporary for constraint types.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::QProblem(), and QProblem::setA().
real_t* QProblemB::ub [protected, inherited]
Upper bound vector (on variables).
Referenced by QProblemB::clear(), QProblemB::copy(), SQProblemSchur::correctInertia(), QProblemB::determineDataShift(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblemB::getRelativeHomotopyLength(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::repairSingularWorkingSet(), QProblemB::setUB(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblemB::setupQPdataFromFile(), QProblemB::setupSubjectToType(), QProblem::setupSubjectToType(), QProblem::solveInitialQP(), QProblemB::solveInitialQP(), QProblem::updateActivitiesForHotstart(), and QProblem::writeQpDataIntoMatFile().
real_t* QProblem::ubA [protected, inherited]
Upper constraints' bound vector.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineDataShift(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblem::getRelativeHomotopyLength(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblem::printIteration(), QProblem::QProblem(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), QProblem::setA(), QProblem::setUBA(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), setupNewAuxiliaryQP(), QProblem::setupQPdataFromFile(), QProblem::setupSubjectToType(), QProblem::solveInitialQP(), and QProblem::writeQpDataIntoMatFile().
BooleanType QProblemB::unbounded [protected, inherited]
QP unbounded?
Referenced by QProblemB::copy(), QProblem::ensureNonzeroCurvature(), QProblemB::hotstart(), QProblem::hotstart(), QProblemB::isUnbounded(), QProblem::printProperties(), QProblemB::printProperties(), QProblemB::QProblemB(), QProblemB::reset(), QProblem::solveQP(), and QProblemB::solveQP().
real_t* QProblemB::x [protected, inherited]
Primal solution vector.
Referenced by SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblemB::clear(), QProblemB::copy(), SQProblemSchur::correctInertia(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblemB::getObjVal(), QProblemB::getPrimalSolution(), QProblemB::hotstart(), QProblem::hotstart(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblemB::QProblemB(), SQProblemSchur::repairSingularWorkingSet(), QProblem::setA(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), QProblemB::setupAuxiliaryQPsolution(), QProblem::solveRegularisedQP(), QProblemB::solveRegularisedQP(), and QProblem::updateActivitiesForHotstart().
real_t* QProblemB::y [protected, inherited]
Dual solution vector.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::changeActiveSet(), QProblemB::changeActiveSet(), QProblemB::clear(), QProblem::copy(), QProblemB::copy(), QProblemB::getDualSolution(), QProblem::getDualSolution(), SolutionAnalysis::getKktViolation(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblem::QProblem(), QProblemB::QProblemB(), SQProblemSchur::repairSingularWorkingSet(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), QProblemB::setupAuxiliaryQPsolution(), setupNewAuxiliaryQP(), and QProblem::updateActivitiesForHotstart().
real_t* QProblem::ZFR_delta_xFRz [protected, inherited]
Temporary for determineStepDirection.
Referenced by QProblem::clear(), QProblem::copy(), QProblem::determineStepDirection(), and QProblem::QProblem().
The documentation for this class was generated from the following files:
include/qpOASES/SQProblem.hpp
src/SQProblem.cpp