qpOASES: Bounds Class Reference
Bounds Class Reference
Manages working sets of bounds (i.e. box constraints).
#include <Bounds.hpp>
Public Member Functions
Bounds ()
Bounds (int_t _n)
Bounds (const Bounds &rhs)
virtual ~Bounds ()
Bounds & operator= (const Bounds &rhs)
returnValue init (int_t _n=0)
returnValue setupBound (int_t number, SubjectToStatus _status)
returnValue setupAllFree ()
returnValue setupAllLower ()
returnValue setupAllUpper ()
returnValue moveFixedToFree (int_t number)
returnValue moveFreeToFixed (int_t number, SubjectToStatus _status)
returnValue flipFixed (int_t number)
returnValue swapFree (int_t number1, int_t number2)
int_t getNV () const
int_t getNFV () const
int_t getNBV () const
int_t getNUV () const
int_t getNFR () const
int_t getNFX () const
Indexlist * getFree ()
Indexlist * getFixed ()
virtual returnValue shift (int_t offset)
virtual returnValue rotate (int_t offset)
returnValue print ()
int_t getNumberOfType (SubjectToType _type) const
SubjectToType getType (int_t i) const
SubjectToStatus getStatus (int_t i) const
returnValue setType (int_t i, SubjectToType value)
returnValue setStatus (int_t i, SubjectToStatus value)
void setNoLower (BooleanType _status)
void setNoUpper (BooleanType _status)
BooleanType hasNoLower () const
BooleanType hasNoUpper () const
Protected Member Functions
returnValue clear ()
returnValue copy (const Bounds &rhs)
returnValue setupAll (SubjectToStatus _status)
returnValue copy (const SubjectTo &rhs)
returnValue addIndex (Indexlist *const indexlist, int_t newnumber, SubjectToStatus newstatus)
returnValue removeIndex (Indexlist *const indexlist, int_t removenumber)
returnValue swapIndex (Indexlist *const indexlist, int_t number1, int_t number2)
Protected Attributes
Indexlist freee
Indexlist fixed
int_t n
SubjectToType * type
SubjectToStatus * status
BooleanType noLower
BooleanType noUpper
Detailed Description
This class manages working sets of bounds (= box constraints) by storing index sets and other status information.
Author:
Hans Joachim Ferreau
Version:
3.2
Date:
2007-2017
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES Bounds::Bounds ()
Default constructor.
Bounds::Bounds (int_t _n)
Constructor which takes the number of bounds.
Parameters:
_n Number of bounds.
References init().
Bounds::Bounds (const Bounds & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
References copy().
Bounds::~Bounds () [virtual]
Destructor.
References clear().
Member Function Documentation
returnValue SubjectTo::addIndex (Indexlist *const indexlist, int_t newnumber, SubjectToStatus newstatus) [protected, inherited]
Adds the index of a new constraint or bound to index set.
Returns:
SUCCESSFUL_RETURN
RET_ADDINDEX_FAILED
RET_INVALID_ARGUMENTS
Parameters:
indexlist Index list to which the new index shall be added.
newnumber Number of new constraint or bound.
newstatus Status of new constraint or bound.
References Indexlist::addNumber(), RET_ADDINDEX_FAILED, RET_INDEX_ALREADY_OF_DESIRED_STATUS, RET_INDEXLIST_EXCEEDS_MAX_LENGTH, RET_INVALID_ARGUMENTS, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by Constraints::moveActiveToInactive(), moveFixedToFree(), moveFreeToFixed(), Constraints::moveInactiveToActive(), setupBound(), and Constraints::setupConstraint().
returnValue Bounds::clear () [protected]
Frees all allocated memory.
Returns:
SUCCESSFUL_RETURN
Reimplemented from SubjectTo.
References SUCCESSFUL_RETURN.
Referenced by init(), operator=(), and ~Bounds().
returnValue SubjectTo::copy (const SubjectTo & rhs) [protected, inherited]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References SubjectTo::n, SubjectTo::noLower, SubjectTo::noUpper, SubjectTo::status, SUCCESSFUL_RETURN, and SubjectTo::type.
Referenced by SubjectTo::operator=(), and SubjectTo::SubjectTo().
returnValue Bounds::copy (const Bounds & rhs) [protected]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References fixed, freee, and SUCCESSFUL_RETURN.
Referenced by Bounds(), and operator=().
returnValue Bounds::flipFixed (int_t number)
Flip fixed bound.
Returns:
SUCCESSFUL_RETURN
RET_MOVING_BOUND_FAILED
RET_INDEX_OUT_OF_BOUNDS
References SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_MOVING_BOUND_FAILED, ST_LOWER, ST_UPPER, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::removeBound(), and QProblemB::removeBound().
Indexlist * Bounds::getFixed () [inline]
Returns a pointer to fixed variables index list.
Returns:
Pointer to fixed variables index list.
References fixed.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblemB::determineDataShift(), QProblem::determineDataShift(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getVarianceCovariance(), moveFixedToFree(), moveFreeToFixed(), QProblem::performStep(), QProblemB::performStep(), print(), setupBound(), QProblem::solveCurrentEQP(), and QProblem::writeQpWorkspaceIntoMatFile().
Indexlist * Bounds::getFree () [inline]
Returns a pointer to free variables index list.
Returns:
Pointer to free variables index list.
References freee.
Referenced by QProblem::addBound(), QProblemB::addBound(), SQProblemSchur::addBound_checkLISchur(), QProblem::addBound_ensureLI(), QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), QProblem::addConstraint_ensureLI(), QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), SQProblemSchur::correctInertia(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::ensureNonzeroCurvature(), QProblem::getFreeVariablesFlags(), SolutionAnalysis::getVarianceCovariance(), moveFixedToFree(), moveFreeToFixed(), QProblem::performStep(), QProblemB::performStep(), print(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), SQProblemSchur::repairSingularWorkingSet(), SQProblemSchur::resetSchurComplement(), setupBound(), QProblem::setupTQfactorisation(), QProblem::solveCurrentEQP(), swapFree(), and QProblem::writeQpWorkspaceIntoMatFile().
int_t Bounds::getNBV () const [inline]
Returns number of bounded (but possibly free) variables.
Returns:
Number of bounded (but possibly free) variables.
References SubjectTo::getNumberOfType(), and ST_BOUNDED.
int_t Bounds::getNFR () const [inline]
Returns number of free variables.
Returns:
Number of free variables.
References freee, and Indexlist::getLength().
Referenced by QProblemB::getNFR(), and print().
int_t Bounds::getNFV () const [inline]
Returns number of implicitly fixed variables.
Returns:
Number of implicitly fixed variables.
References SubjectTo::getNumberOfType(), and ST_EQUALITY.
Referenced by QProblemB::getNFV().
int_t Bounds::getNFX () const [inline]
Returns number of fixed variables.
Returns:
Number of fixed variables.
References fixed, and Indexlist::getLength().
Referenced by QProblemB::getNFX(), print(), QProblem::shallRefactorise(), and QProblemB::shallRefactorise().
BEGIN_NAMESPACE_QPOASES int_t SubjectTo::getNumberOfType (SubjectToType _type) const [inline, inherited]
Returns number of constraints/bounds with given SubjectTo type.
Returns:
Number of constraints/bounds with given type.
Parameters:
_type Type of (constraints') bound.
References SubjectTo::n, and SubjectTo::type.
Referenced by getNBV(), Constraints::getNEC(), getNFV(), Constraints::getNIC(), Constraints::getNUC(), and getNUV().
int_t Bounds::getNUV () const [inline]
Returns number of unbounded variables.
Returns:
Number of unbounded variables.
References SubjectTo::getNumberOfType(), and ST_UNBOUNDED.
Referenced by SQProblemSchur::addBound(), and QProblem::addBound().
BEGIN_NAMESPACE_QPOASES int_t Bounds::getNV () const [inline]
Returns number of variables.
Returns:
Number of variables.
References SubjectTo::n.
Referenced by QProblemB::getNV().
SubjectToStatus SubjectTo::getStatus (int_t i) const [inline, inherited]
Returns status of (constraints') bound.
Returns:
Status of (constraints') bound
ST_UNDEFINED
Parameters:
i Number of (constraints') bound.
References SubjectTo::n, ST_UNDEFINED, and SubjectTo::status.
Referenced by SQProblemSchur::addBound(), QProblem::addBound(), SQProblemSchur::addConstraint(), QProblem::addConstraint(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), SQProblemSchur::determineStepDirection2(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), QProblemB::getWorkingSetBounds(), QProblem::getWorkingSetConstraints(), QProblemB::init(), QProblem::init(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::performRatioTest(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), SQProblemSchur::removeConstraint(), QProblem::removeConstraint(), Constraints::rotate(), rotate(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), SQProblemSchur::setupAuxiliaryWorkingSet(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupAuxiliaryWorkingSet(), SQProblem::setupNewAuxiliaryQP(), QProblem::shallRefactorise(), QProblemB::shallRefactorise(), Constraints::shift(), shift(), and QProblem::updateActivitiesForHotstart().
SubjectToType SubjectTo::getType (int_t i) const [inline, inherited]
Returns type of (constraints') bound.
Returns:
Type of (constraints') bound
RET_INDEX_OUT_OF_BOUNDS
Parameters:
i Number of (constraints') bound.
References SubjectTo::n, ST_UNKNOWN, and SubjectTo::type.
Referenced by QProblem::dropInfeasibles(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::performRatioTest(), QProblem::performStep(), SQProblemSchur::repairSingularWorkingSet(), Constraints::rotate(), rotate(), Constraints::setupAll(), setupAll(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryWorkingSet(), SQProblem::setupNewAuxiliaryQP(), QProblem::setupSubjectToType(), Constraints::shift(), shift(), and QProblem::updateActivitiesForHotstart().
BooleanType SubjectTo::hasNoLower () const [inline, inherited]
Returns status of lower (constraints') bounds.
Returns:
BT_TRUE if there is no lower (constraints') bound on any variable.
References SubjectTo::noLower.
Referenced by QProblem::performStep(), QProblemB::performStep(), QProblem::printProperties(), and QProblemB::printProperties().
BooleanType SubjectTo::hasNoUpper () const [inline, inherited]
Returns status of upper bounds.
Returns:
BT_TRUE if there is no upper (constraints') bound on any variable.
References SubjectTo::noUpper.
Referenced by QProblem::performStep(), QProblemB::performStep(), QProblem::printProperties(), and QProblemB::printProperties().
returnValue Bounds::init (int_t _n = 0)
Initialises object with given number of bounds.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
_n Number of bounds.
Reimplemented from SubjectTo.
References clear(), fixed, freee, Indexlist::init(), RET_INVALID_ARGUMENTS, and THROWERROR.
Referenced by Bounds(), QProblemB::QProblemB(), QProblemB::reset(), SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), and SQProblem::setupNewAuxiliaryQP().
returnValue Bounds::moveFixedToFree (int_t number)
Moves index of a bound from index list of fixed to that of free bounds.
Returns:
SUCCESSFUL_RETURN
RET_MOVING_BOUND_FAILED
RET_INDEX_OUT_OF_BOUNDS
Parameters:
number Number of bound to be freed.
References SubjectTo::addIndex(), getFixed(), getFree(), SubjectTo::n, SubjectTo::removeIndex(), RET_INDEX_OUT_OF_BOUNDS, RET_MOVING_BOUND_FAILED, ST_INACTIVE, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), SQProblemSchur::removeBound(), QProblem::removeBound(), QProblemB::removeBound(), and SQProblemSchur::setupAuxiliaryWorkingSet().
returnValue Bounds::moveFreeToFixed (int_t number, SubjectToStatus _status)
Moves index of a bound from index list of free to that of fixed bounds.
Returns:
SUCCESSFUL_RETURN
RET_MOVING_BOUND_FAILED
RET_INDEX_OUT_OF_BOUNDS
Parameters:
number Number of bound to be fixed.
_status Status of bound to be fixed.
References SubjectTo::addIndex(), getFixed(), getFree(), SubjectTo::n, SubjectTo::removeIndex(), RET_INDEX_OUT_OF_BOUNDS, RET_MOVING_BOUND_FAILED, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by SQProblemSchur::addBound(), QProblem::addBound(), QProblemB::addBound(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), SQProblemSchur::removeBound(), SQProblemSchur::repairSingularWorkingSet(), SQProblemSchur::setupAuxiliaryWorkingSet(), and QProblem::setupAuxiliaryWorkingSet().
Bounds & Bounds::operator= (const Bounds & rhs)
Assignment operator (deep copy).
Parameters:
rhs Rhs object.
References clear(), and copy().
returnValue Bounds::print ()
Prints information on bounds object (in particular, lists of free and fixed bounds.
Returns:
SUCCESSFUL_RETURN
RET_INDEXLIST_CORRUPTED
References getFixed(), getFree(), getNFR(), getNFX(), Indexlist::getNumberArray(), MAX_STRING_LENGTH, myPrintf(), SubjectTo::n, REFER_NAMESPACE_QPOASES, and SUCCESSFUL_RETURN.
returnValue SubjectTo::removeIndex (Indexlist *const indexlist, int_t removenumber) [protected, inherited]
Removes the index of a constraint or bound from index set.
Returns:
SUCCESSFUL_RETURN
RET_REMOVEINDEX_FAILED
RET_INVALID_ARGUMENTS
Parameters:
indexlist Index list from which the new index shall be removed.
removenumber Number of constraint or bound to be removed.
References Indexlist::removeNumber(), RET_INVALID_ARGUMENTS, RET_REMOVEINDEX_FAILED, ST_UNDEFINED, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by Constraints::moveActiveToInactive(), moveFixedToFree(), moveFreeToFixed(), and Constraints::moveInactiveToActive().
returnValue Bounds::rotate (int_t offset) [virtual]
Rotates forward type and status of all bounds by a given offset. This offset has to lie within the range [0,n]. Example for offset = 2:
rotate({b1,b2,b3,b4,b5,b6}) = {b3,b4,b5,b6,b1,b2}
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
RET_ROTATING_FAILED
Parameters:
offset Rotation offset within the range [0,n].
Implements SubjectTo.
References Indexlist::addNumber(), fixed, freee, SubjectTo::getStatus(), SubjectTo::getType(), SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_ROTATING_FAILED, SubjectTo::setStatus(), SubjectTo::setType(), ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
void SubjectTo::setNoLower (BooleanType _status) [inline, inherited]
Sets status of lower (constraints') bounds.
Parameters:
_status Status of lower (constraints') bounds.
References SubjectTo::noLower.
Referenced by QProblemB::setupSubjectToType(), and QProblem::setupSubjectToType().
void SubjectTo::setNoUpper (BooleanType _status) [inline, inherited]
Sets status of upper (constraints') bounds.
Parameters:
_status Status of upper (constraints') bounds.
References SubjectTo::noUpper.
Referenced by QProblemB::setupSubjectToType(), and QProblem::setupSubjectToType().
returnValue SubjectTo::setStatus (int_t i, SubjectToStatus value) [inline, inherited]
Sets status of (constraints') bound.
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
Parameters:
i Number of (constraints') bound.
value Status of (constraints') bound.
References SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::dropInfeasibles(), Constraints::rotate(), rotate(), SQProblemSchur::setupAuxiliaryQP(), SQProblem::setupNewAuxiliaryQP(), Constraints::shift(), and shift().
returnValue SubjectTo::setType (int_t i, SubjectToType value) [inline, inherited]
Sets type of (constraints') bound.
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
Parameters:
i Number of (constraints') bound.
value Type of (constraints') bound.
References SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, SUCCESSFUL_RETURN, THROWERROR, and SubjectTo::type.
Referenced by SQProblemSchur::repairSingularWorkingSet(), Constraints::rotate(), rotate(), QProblem::setA(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupSubjectToType(), QProblem::setupSubjectToType(), Constraints::shift(), and shift().
returnValue Bounds::setupAll (SubjectToStatus _status) [protected]
Initially adds all numbers of new (i.e. not yet in the list) bounds to to the index set corresponding to the desired status; the order depends on the SujectToType of each index.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_BOUND_FAILED
Parameters:
_status Desired initial status for all bounds.
References SubjectTo::getType(), SubjectTo::n, RET_SETUP_BOUND_FAILED, setupBound(), ST_BOUNDED, ST_DISABLED, ST_EQUALITY, ST_UNBOUNDED, ST_UNKNOWN, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by setupAllFree(), setupAllLower(), and setupAllUpper().
returnValue Bounds::setupAllFree ()
Initially adds all numbers of new (i.e. not yet in the list) bounds to to the index set of free bounds; the order depends on the SujectToType of each index.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_BOUND_FAILED
References setupAll(), and ST_INACTIVE.
Referenced by SQProblemSchur::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), SQProblem::setupNewAuxiliaryQP(), QProblem::solveInitialQP(), and QProblemB::solveInitialQP().
returnValue Bounds::setupAllLower ()
Initially adds all numbers of new (i.e. not yet in the list) bounds to to the index set of fixed bounds (on their lower bounds); the order depends on the SujectToType of each index.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_BOUND_FAILED
References setupAll(), and ST_LOWER.
returnValue Bounds::setupAllUpper ()
Initially adds all numbers of new (i.e. not yet in the list) bounds to to the index set of fixed bounds (on their upper bounds); the order depends on the SujectToType of each index.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_BOUND_FAILED
References setupAll(), and ST_UPPER.
returnValue Bounds::setupBound (int_t number, SubjectToStatus _status)
Initially adds number of a new (i.e. not yet in the list) bound to given index set.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_BOUND_FAILED
RET_INDEX_OUT_OF_BOUNDS
RET_INVALID_ARGUMENTS
Parameters:
number Number of new bound.
_status Status of new bound.
References SubjectTo::addIndex(), getFixed(), getFree(), SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_INVALID_ARGUMENTS, RET_SETUP_BOUND_FAILED, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblemB::obtainAuxiliaryWorkingSet(), and setupAll().
returnValue Bounds::shift (int_t offset) [virtual]
Shifts forward type and status of all bounds by a given offset. This offset has to lie within the range [0,n/2] and has to be an integer divisor of the total number of bounds n. Type and status of the first <offset> bounds is thrown away, type and status of the last <offset> bounds is doubled, e.g. for offset = 2:
shift({b1,b2,b3,b4,b5,b6}) = {b3,b4,b5,b6,b5,b6}
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
RET_INVALID_ARGUMENTS
RET_SHIFTING_FAILED
Parameters:
offset Shift offset within the range [0,n/2] and integer divisor of n.
Implements SubjectTo.
References Indexlist::addNumber(), fixed, freee, SubjectTo::getStatus(), SubjectTo::getType(), SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_INVALID_ARGUMENTS, RET_SHIFTING_FAILED, SubjectTo::setStatus(), SubjectTo::setType(), ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
returnValue Bounds::swapFree (int_t number1, int_t number2)
Swaps the indices of two free bounds within the index set.
Returns:
SUCCESSFUL_RETURN
RET_SWAPINDEX_FAILED
Parameters:
number1 Number of first constraint or bound.
number2 Number of second constraint or bound.
References getFree(), SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, SubjectTo::swapIndex(), and THROWERROR.
Referenced by QProblem::addBound().
returnValue SubjectTo::swapIndex (Indexlist *const indexlist, int_t number1, int_t number2) [protected, inherited]
Swaps the indices of two constraints or bounds within the index set.
Returns:
SUCCESSFUL_RETURN
RET_SWAPINDEX_FAILED
RET_INVALID_ARGUMENTS
Parameters:
indexlist Index list in which the indices shold be swapped.
number1 Number of first constraint or bound.
number2 Number of second constraint or bound.
References RET_INVALID_ARGUMENTS, RET_NOTHING_TO_DO, RET_SWAPINDEX_FAILED, SubjectTo::status, SUCCESSFUL_RETURN, Indexlist::swapNumbers(), THROWERROR, and THROWWARNING.
Referenced by swapFree().
Member Data Documentation
Indexlist Bounds::fixed [protected]
Index list of fixed variables.
Referenced by copy(), getFixed(), getNFX(), init(), rotate(), and shift().
Indexlist Bounds::freee [protected]
Index list of free variables.
Referenced by copy(), getFree(), getNFR(), init(), rotate(), and shift().
int_t SubjectTo::n [protected, inherited]
Total number of constraints/bounds.
Referenced by SubjectTo::copy(), Constraints::flipFixed(), flipFixed(), Constraints::getNC(), SubjectTo::getNumberOfType(), getNV(), SubjectTo::getStatus(), SubjectTo::getType(), SubjectTo::init(), Constraints::moveActiveToInactive(), moveFixedToFree(), moveFreeToFixed(), Constraints::moveInactiveToActive(), Constraints::print(), print(), Constraints::rotate(), rotate(), SubjectTo::setStatus(), SubjectTo::setType(), Constraints::setupAll(), setupAll(), setupBound(), Constraints::setupConstraint(), Constraints::shift(), shift(), and swapFree().
BooleanType SubjectTo::noLower [protected, inherited]
This flag indicates if there is no lower bound on any variable.
Referenced by SubjectTo::copy(), SubjectTo::hasNoLower(), SubjectTo::init(), and SubjectTo::setNoLower().
BooleanType SubjectTo::noUpper [protected, inherited]
This flag indicates if there is no upper bound on any variable.
Referenced by SubjectTo::copy(), SubjectTo::hasNoUpper(), SubjectTo::init(), and SubjectTo::setNoUpper().
SubjectToStatus* SubjectTo::status [protected, inherited]
Status of constraints/bounds.
Referenced by SubjectTo::addIndex(), SubjectTo::clear(), SubjectTo::copy(), Constraints::flipFixed(), flipFixed(), SubjectTo::getStatus(), SubjectTo::init(), SubjectTo::removeIndex(), SubjectTo::setStatus(), SubjectTo::SubjectTo(), and SubjectTo::swapIndex().
SubjectToType* SubjectTo::type [protected, inherited]
Type of constraints/bounds.
Referenced by SubjectTo::clear(), SubjectTo::copy(), SubjectTo::getNumberOfType(), SubjectTo::getType(), SubjectTo::init(), SubjectTo::setType(), and SubjectTo::SubjectTo().
The documentation for this class was generated from the following files:
include/qpOASES/Bounds.hpp
src/Bounds.cpp
include/qpOASES/Bounds.ipp