qpOASES: include/qpOASES/LapackBlasReplacement.hpp File Reference
include/qpOASES/LapackBlasReplacement.hpp File Reference
Defines
#define GEMM dgemm_
#define SYR dsyr_
#define SYR2 dsyr2_
#define POTRF dpotrf_
#define TRTRS dtrtrs_
#define TRCON dtrcon_
Functions
void dgemm_ (const char *, const char *, const la_uint_t *, const la_uint_t *, const la_uint_t *, const double *, const double *, const la_uint_t *, const double *, const la_uint_t *, const double *, double *, const la_uint_t *)
void sgemm_ (const char *, const char *, const la_uint_t *, const la_uint_t *, const la_uint_t *, const float *, const float *, const la_uint_t *, const float *, const la_uint_t *, const float *, float *, const la_uint_t *)
void dsyr_ (const char *, const la_uint_t *, const double *, const double *, const la_uint_t *, double *, const la_uint_t *)
void ssyr_ (const char *, const la_uint_t *, const float *, const float *, const la_uint_t *, float *, const la_uint_t *)
void dsyr2_ (const char *, const la_uint_t *, const double *, const double *, const la_uint_t *, const double *, const la_uint_t *, double *, const la_uint_t *)
void ssyr2_ (const char *, const la_uint_t *, const float *, const float *, const la_uint_t *, const float *, const la_uint_t *, float *, const la_uint_t *)
void dpotrf_ (const char *, const la_uint_t *, double *, const la_uint_t *, la_int_t *)
void spotrf_ (const char *, const la_uint_t *, float *, const la_uint_t *, la_int_t *)
void dtrtrs_ (const char *UPLO, const char *TRANS, const char *DIAG, const la_uint_t *N, const la_uint_t *NRHS, double *A, const la_uint_t *LDA, double *B, const la_uint_t *LDB, la_int_t *INFO)
void strtrs_ (const char *UPLO, const char *TRANS, const char *DIAG, const la_uint_t *N, const la_uint_t *NRHS, float *A, const la_uint_t *LDA, float *B, const la_uint_t *LDB, la_int_t *INFO)
void dtrcon_ (const char *NORM, const char *UPLO, const char *DIAG, const la_uint_t *N, double *A, const la_uint_t *LDA, double *RCOND, double *WORK, const la_uint_t *IWORK, la_int_t *INFO)
void strcon_ (const char *NORM, const char *UPLO, const char *DIAG, const la_uint_t *N, float *A, const la_uint_t *LDA, float *RCOND, float *WORK, const la_uint_t *IWORK, la_int_t *INFO)
Detailed Description
Author:
Andreas Potschka, Hans Joachim Ferreau, Christian Kirches
Version:
3.2
Date:
2009-2017
Declarations for external LAPACK/BLAS functions.
Define Documentation
#define GEMM dgemm_
Macro for calling level 3 BLAS operation in double precision.
Referenced by DenseMatrix::times(), and DenseMatrix::transTimes().
#define POTRF dpotrf_
Macro for calling level 3 BLAS operation in double precision.
Referenced by QProblemB::computeCholesky(), and QProblem::computeProjectedCholesky().
#define SYR dsyr_
Macro for calling level 3 BLAS operation in double precision.
#define SYR2 dsyr2_
Macro for calling level 3 BLAS operation in double precision.
#define TRCON dtrcon_
Macro for calling level 3 BLAS operation in double precision.
Referenced by SQProblemSchur::updateSchurQR().
#define TRTRS dtrtrs_
Macro for calling level 3 BLAS operation in double precision. Macro for calling level 3 BLAS operation in double precision. Macro for calling level 3 BLAS operation in double precision.
Referenced by SQProblemSchur::backsolveSchurQR().
Function Documentation
void dgemm_ (const char * , const char * , const la_uint_t * , const la_uint_t * , const la_uint_t * , const double * , const double * , const la_uint_t * , const double * , const la_uint_t * , const double * , double * , const la_uint_t *)
Performs one of the matrix-matrix operation in double precision.
References BT_FALSE, BT_TRUE, isEqual(), isZero(), and REFER_NAMESPACE_QPOASES.
void dpotrf_ (const char * , const la_uint_t * , double * , const la_uint_t * , la_int_t *)
Calculates the Cholesky factorization of a real symmetric positive definite matrix in double precision.
References getSqrt(), and REFER_NAMESPACE_QPOASES.
void dsyr2_ (const char * , const la_uint_t * , const double * , const double * , const la_uint_t * , const double * , const la_uint_t * , double * , const la_uint_t *)
Performs a symmetric rank 2 operation in double precision.
void dsyr_ (const char * , const la_uint_t * , const double * , const double * , const la_uint_t * , double * , const la_uint_t *)
Performs a symmetric rank 1 operation in double precision.
void dtrcon_ (const char * NORM, const char * UPLO, const char * DIAG, const la_uint_t * N, double * A, const la_uint_t * LDA, double * RCOND, double * WORK, const la_uint_t * IWORK, la_int_t * INFO)
Estimate the reciprocal of the condition number of a triangular matrix in double precision
void dtrtrs_ (const char * UPLO, const char * TRANS, const char * DIAG, const la_uint_t * N, const la_uint_t * NRHS, double * A, const la_uint_t * LDA, double * B, const la_uint_t * LDB, la_int_t * INFO)
Computes a QR factorization of a real M-by-N matrix A in double precision Computes a QR factorization of a real M-by-N matrix A in single precision Multiplies C with orthogonal matrix Q**T as returned by geqrf (double precision) Multiplies C with orthogonal matrix Q**T as returned by geqrf (single precision) Solves a triangular system (double precision)
void sgemm_ (const char * , const char * , const la_uint_t * , const la_uint_t * , const la_uint_t * , const float * , const float * , const la_uint_t * , const float * , const la_uint_t * , const float * , float * , const la_uint_t *)
Performs one of the matrix-matrix operation in single precision.
References BT_FALSE, BT_TRUE, isEqual(), isZero(), and REFER_NAMESPACE_QPOASES.
void spotrf_ (const char * , const la_uint_t * , float * , const la_uint_t * , la_int_t *)
Calculates the Cholesky factorization of a real symmetric positive definite matrix in single precision.
References getSqrt(), and REFER_NAMESPACE_QPOASES.
void ssyr2_ (const char * , const la_uint_t * , const float * , const float * , const la_uint_t * , const float * , const la_uint_t * , float * , const la_uint_t *)
Performs a symmetric rank 2 operation in single precision.
void ssyr_ (const char * , const la_uint_t * , const float * , const float * , const la_uint_t * , float * , const la_uint_t *)
Performs a symmetric rank 1 operation in single precision.
void strcon_ (const char * NORM, const char * UPLO, const char * DIAG, const la_uint_t * N, float * A, const la_uint_t * LDA, float * RCOND, float * WORK, const la_uint_t * IWORK, la_int_t * INFO)
Estimate the reciprocal of the condition number of a triangular matrix in single precision
void strtrs_ (const char * UPLO, const char * TRANS, const char * DIAG, const la_uint_t * N, const la_uint_t * NRHS, float * A, const la_uint_t * LDA, float * B, const la_uint_t * LDB, la_int_t * INFO)
Solves a triangular system (single precision)