qpOASES: src/MessageHandling.cpp File Reference
src/MessageHandling.cpp File Reference
#include <stdio.h>
#include <qpOASES/MessageHandling.hpp>
#include <qpOASES/Utils.hpp>
Functions
MessageHandling * getGlobalMessageHandler ()
Variables
BEGIN_NAMESPACE_QPOASES FILE * stdFile = stdout
MessageHandling::ReturnValueList returnValueList []
Detailed Description
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.2
Date:
2007-2017
Implementation of the MessageHandling class including global return values.
Function Documentation
MessageHandling* getGlobalMessageHandler ()
Global message handler for all qpOASES modules.
References stdFile, and VS_VISIBLE.
Referenced by SQProblemSchur::addBound_ensureLI(), QProblem::addBound_ensureLI(), SQProblemSchur::addConstraint_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::changeActiveSet(), QProblemB::changeActiveSet(), getSimpleStatus(), myPrintf(), QProblem::performStep(), QProblemB::performStep(), QProblemB::QProblemB(), readFromFile(), QProblemB::setPrintLevel(), QProblem::solveQP(), QProblemB::solveQP(), writeIntoFile(), and QProblemB::~QProblemB().
Variable Documentation
MessageHandling::ReturnValueList returnValueList[]
Defines pairs of global return values and messages.
BEGIN_NAMESPACE_QPOASES FILE* stdFile = stdout
Default file to display messages.
Referenced by getGlobalMessageHandler(), MessageHandling::MessageHandling(), and MessageHandling::reset().