qpOASES: include/qpOASES/Utils.ipp File Reference
include/qpOASES/Utils.ipp File Reference
#include <math.h>
Functions
BEGIN_NAMESPACE_QPOASES BooleanType isEqual (real_t x, real_t y, real_t TOL)
BooleanType isZero (real_t x, real_t TOL)
real_t getSign (real_t arg)
int_t getMax (int_t x, int_t y)
int_t getMin (int_t x, int_t y)
real_t getMax (real_t x, real_t y)
real_t getMin (real_t x, real_t y)
real_t getAbs (real_t x)
real_t getSqrt (real_t x)
Detailed Description
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.2
Date:
2007-2017
Implementation of some inlined utilities for working with the different QProblem classes.
Function Documentation
real_t getAbs (real_t x) [inline]
Returns the absolute value of a real number.
Returns:
Absolute value of a real number
Parameters:
x Real number.
Referenced by QProblem::addBound_checkLI(), SQProblemSchur::addBound_checkLISchur(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), QProblemB::backsolveR(), QProblem::backsolveT(), SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), QProblemB::computeCholesky(), QProblemB::computeGivens(), QProblem::computeProjectedCholesky(), QProblemB::determineDataShift(), QProblem::determineDataShift(), QProblemB::determineHessianType(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), getKktViolation(), getNorm(), QProblemB::getRelativeHomotopyLength(), QProblem::getRelativeHomotopyLength(), SparseMatrix::getRowNorm(), QProblemB::hotstart(), QProblem::hotstart(), DenseMatrix::isDiag(), isEqual(), isZero(), main(), QProblem::performRamping(), QProblem::printIteration(), QProblemB::printIteration(), and SparseMatrix::times().
int_t getMax (int_t x, int_t y) [inline]
Returns maximum of two integers.
Returns:
Maximum of two integers
Parameters:
x First integer.
y Second integer.
Referenced by SQProblemSchur::addToSchurComplement(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getKktViolation(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblem::performRamping(), QProblem::performStep(), QProblemB::performStep(), QProblem::setupQPdata(), DenseMatrix::times(), SparseMatrix::times(), DenseMatrix::transTimes(), QProblemB::updateFarBounds(), and QProblem::updateFarBounds().
real_t getMax (real_t x, real_t y) [inline]
Returns maximum of two reals.
Returns:
Maximum of two reals
Parameters:
x First real number.
y Second real number.
int_t getMin (int_t x, int_t y) [inline]
Returns minimum of two integers.
Returns:
Minimum of two integers
Parameters:
x First integer.
y Second integer.
Referenced by QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblem::QProblem(), QProblem::setupQPdata(), QProblemB::updateFarBounds(), and QProblem::updateFarBounds().
real_t getMin (real_t x, real_t y) [inline]
Returns minimum of two reals.
Returns:
Minimum of two reals
Parameters:
x First real number.
y Second real number.
real_t getSign (real_t arg) [inline]
Returns sign of a real-valued argument.
Returns:
1.0: argument is non-negative
-1.0: argument is negative
Parameters:
arg real-valued argument whose sign is to be determined.
real_t getSqrt (real_t x) [inline]
Returns the square-root of a real number.
Returns:
Square-root of a real number
Parameters:
x Non-negative real number.
Referenced by QProblemB::computeCholesky(), QProblemB::computeGivens(), QProblem::computeProjectedCholesky(), dpotrf_(), getNorm(), SparseMatrix::getRowNorm(), normaliseConstraints(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), and spotrf_().
BEGIN_NAMESPACE_QPOASES BooleanType isEqual (real_t x, real_t y, real_t TOL = ZERO) [inline]
Tests whether two real_t-valued arguments are (numerically) equal.
Returns:
BT_TRUE: arguments differ not more than TOL
BT_FALSE: arguments differ more than TOL
Parameters:
x First real number.
y Second real number.
TOL Tolerance for comparison.
References BT_FALSE, BT_TRUE, and getAbs().
Referenced by SQProblemSchur::computeMTimes(), SQProblemSchur::computeMTransTimes(), dgemm_(), DenseMatrix::getCol(), SparseMatrix::getCol(), SparseMatrixRow::getCol(), getKktViolation(), DenseMatrix::getRow(), SparseMatrix::getRow(), SparseMatrixRow::getRow(), sgemm_(), DenseMatrix::times(), SparseMatrix::times(), SparseMatrixRow::times(), DenseMatrix::transTimes(), SparseMatrix::transTimes(), and SparseMatrixRow::transTimes().
BooleanType isZero (real_t x, real_t TOL = ZERO) [inline]
Tests whether a real-valued argument is (numerically) zero.
Returns:
BT_TRUE: argument differs from 0.0 not more than TOL
BT_FALSE: argument differs from 0.0 more than TOL
Parameters:
x Real number.
TOL Tolerance for comparison.
References BT_FALSE, BT_TRUE, and getAbs().
Referenced by SparseMatrix::addToDiag(), SparseMatrixRow::addToDiag(), QProblemB::computeGivens(), SQProblemSchur::computeMTransTimes(), QProblemB::determineHessianType(), dgemm_(), DenseMatrix::getSparseSubmatrix(), QProblem::setA(), sgemm_(), SparseMatrix::SparseMatrix(), SparseMatrixRow::SparseMatrixRow(), DenseMatrix::times(), SparseMatrix::times(), SparseMatrixRow::times(), DenseMatrix::transTimes(), SparseMatrix::transTimes(), and SparseMatrixRow::transTimes().