qpOASES: Constraints Class Reference
Constraints Class Reference
Manages working sets of constraints.
#include <Constraints.hpp>
Public Member Functions
Constraints ()
Constraints (int _n)
Constraints (const Constraints &rhs)
virtual ~Constraints ()
Constraints & operator= (const Constraints &rhs)
returnValue init (int _n=0)
returnValue setupConstraint (int number, SubjectToStatus _status)
returnValue setupAllInactive ()
returnValue setupAllLower ()
returnValue setupAllUpper ()
returnValue moveActiveToInactive (int number)
returnValue moveInactiveToActive (int number, SubjectToStatus _status)
returnValue flipFixed (int number)
int getNC () const
int getNEC () const
int getNIC () const
int getNUC () const
int getNAC () const
int getNIAC () const
Indexlist * getActive ()
Indexlist * getInactive ()
virtual returnValue shift (int offset)
virtual returnValue rotate (int offset)
returnValue print ()
int getNumberOfType (SubjectToType _type) const
SubjectToType getType (int i) const
SubjectToStatus getStatus (int i) const
returnValue setType (int i, SubjectToType value)
returnValue setStatus (int i, SubjectToStatus value)
void setNoLower (BooleanType _status)
void setNoUpper (BooleanType _status)
BooleanType hasNoLower () const
BooleanType hasNoUpper () const
Protected Member Functions
returnValue clear ()
returnValue copy (const Constraints &rhs)
returnValue setupAll (SubjectToStatus _status)
returnValue copy (const SubjectTo &rhs)
returnValue addIndex (Indexlist *const indexlist, int newnumber, SubjectToStatus newstatus)
returnValue removeIndex (Indexlist *const indexlist, int removenumber)
returnValue swapIndex (Indexlist *const indexlist, int number1, int number2)
Protected Attributes
Indexlist active
Indexlist inactive
int n
SubjectToType * type
SubjectToStatus * status
BooleanType noLower
BooleanType noUpper
Detailed Description
This class manages working sets of constraints by storing index sets and other status information.
Author:
Hans Joachim Ferreau
Version:
3.0
Date:
2007-2014
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES Constraints::Constraints ()
Default constructor.
Constraints::Constraints (int _n)
Constructor which takes the number of constraints.
Parameters:
_n Number of constraints.
References init().
Constraints::Constraints (const Constraints & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
References copy().
Constraints::~Constraints () [virtual]
Destructor.
References clear().
Member Function Documentation
returnValue SubjectTo::addIndex (Indexlist *const indexlist, int newnumber, SubjectToStatus newstatus) [protected, inherited]
Adds the index of a new constraint or bound to index set.
Returns:
SUCCESSFUL_RETURN
RET_ADDINDEX_FAILED
RET_INVALID_ARGUMENTS
Parameters:
indexlist Index list to which the new index shall be added.
newnumber Number of new constraint or bound.
newstatus Status of new constraint or bound.
References Indexlist::addNumber(), RET_ADDINDEX_FAILED, RET_INDEX_ALREADY_OF_DESIRED_STATUS, RET_INDEXLIST_EXCEEDS_MAX_LENGTH, RET_INVALID_ARGUMENTS, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by moveActiveToInactive(), Bounds::moveFixedToFree(), Bounds::moveFreeToFixed(), moveInactiveToActive(), Bounds::setupBound(), and setupConstraint().
returnValue Constraints::clear () [protected]
Frees all allocated memory.
Returns:
SUCCESSFUL_RETURN
Reimplemented from SubjectTo.
References SUCCESSFUL_RETURN.
Referenced by init(), operator=(), and ~Constraints().
returnValue SubjectTo::copy (const SubjectTo & rhs) [protected, inherited]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References SubjectTo::n, SubjectTo::noLower, SubjectTo::noUpper, SubjectTo::status, SUCCESSFUL_RETURN, and SubjectTo::type.
Referenced by SubjectTo::operator=(), and SubjectTo::SubjectTo().
returnValue Constraints::copy (const Constraints & rhs) [protected]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References active, inactive, and SUCCESSFUL_RETURN.
Referenced by Constraints(), and operator=().
returnValue Constraints::flipFixed (int number)
Flip fixed constraint.
Returns:
SUCCESSFUL_RETURN
RET_MOVING_CONSTRAINT_FAILED
RET_INDEX_OUT_OF_BOUNDS
References SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_MOVING_CONSTRAINT_FAILED, ST_LOWER, ST_UPPER, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::removeConstraint().
Indexlist * Constraints::getActive () [inline]
Returns a pointer to active constraints index list.
Returns:
Pointer to active constraints index list.
References active.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_checkLI(), QProblem::addConstraint_ensureLI(), QProblem::computeProjectedCholesky(), QProblem::determineDataShift(), QProblem::determineStepDirection(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getVarianceCovariance(), moveActiveToInactive(), moveInactiveToActive(), QProblem::performStep(), print(), QProblem::removeBound(), QProblem::removeConstraint(), setupConstraint(), QProblem::solveCurrentEQP(), and QProblem::writeQpWorkspaceIntoMatFile().
Indexlist * Constraints::getInactive () [inline]
Returns a pointer to inactive constraints index list.
Returns:
Pointer to inactive constraints index list.
References inactive.
Referenced by QProblem::addConstraint_checkLI(), QProblem::ensureNonzeroCurvature(), moveActiveToInactive(), moveInactiveToActive(), QProblem::performStep(), print(), setupConstraint(), and QProblem::writeQpWorkspaceIntoMatFile().
int Constraints::getNAC () const [inline]
Returns the number of active constraints.
Returns:
Number of active constraints.
References active, and Indexlist::getLength().
Referenced by QProblem::getNAC(), print(), and QProblem::shallRefactorise().
BEGIN_NAMESPACE_QPOASES int Constraints::getNC () const [inline]
Returns the number of constraints.
Returns:
Number of constraints.
References SubjectTo::n.
Referenced by QProblem::addConstraint(), and QProblem::getNC().
int Constraints::getNEC () const [inline]
Returns the number of implicit equality constraints.
Returns:
Number of implicit equality constraints.
References SubjectTo::getNumberOfType(), and ST_EQUALITY.
Referenced by QProblem::getNEC().
int Constraints::getNIAC () const [inline]
Returns the number of inactive constraints.
Returns:
Number of inactive constraints.
References Indexlist::getLength(), and inactive.
Referenced by QProblem::getNIAC(), and print().
int Constraints::getNIC () const [inline]
Returns the number of "real" inequality constraints.
Returns:
Number of "real" inequality constraints.
References SubjectTo::getNumberOfType(), and ST_BOUNDED.
int Constraints::getNUC () const [inline]
Returns the number of unbounded constraints (i.e. without any bounds).
Returns:
Number of unbounded constraints (i.e. without any bounds).
References SubjectTo::getNumberOfType(), and ST_UNBOUNDED.
Referenced by QProblem::addConstraint().
BEGIN_NAMESPACE_QPOASES int SubjectTo::getNumberOfType (SubjectToType _type) const [inline, inherited]
Returns number of constraints/bounds with given SubjectTo type.
Returns:
Number of constraints/bounds with given type.
Parameters:
_type Type of (constraints') bound.
References SubjectTo::n, and SubjectTo::type.
Referenced by Bounds::getNBV(), getNEC(), Bounds::getNFV(), getNIC(), getNUC(), and Bounds::getNUV().
SubjectToStatus SubjectTo::getStatus (int i) const [inline, inherited]
Returns status of (constraints') bound.
Returns:
Status of (constraints') bound
ST_UNDEFINED
Parameters:
i Number of (constraints') bound.
References SubjectTo::n, ST_UNDEFINED, and SubjectTo::status.
Referenced by QProblem::addBound(), QProblem::addConstraint(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblem::dropInfeasibles(), QProblem::ensureNonzeroCurvature(), SolutionAnalysis::getMaxKKTviolation(), QProblemB::getWorkingSet(), QProblem::getWorkingSet(), QProblemB::init(), QProblem::init(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::performRatioTest(), QProblem::removeBound(), QProblemB::removeBound(), QProblem::removeConstraint(), rotate(), Bounds::rotate(), SQProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), QProblemB::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupAuxiliaryWorkingSet(), QProblem::shallRefactorise(), QProblemB::shallRefactorise(), shift(), and Bounds::shift().
SubjectToType SubjectTo::getType (int i) const [inline, inherited]
Returns type of (constraints') bound.
Returns:
Type of (constraints') bound
RET_INDEX_OUT_OF_BOUNDS
Parameters:
i Number of (constraints') bound.
References SubjectTo::n, ST_UNKNOWN, and SubjectTo::type.
Referenced by QProblem::dropInfeasibles(), QProblemB::obtainAuxiliaryWorkingSet(), QProblem::obtainAuxiliaryWorkingSet(), QProblem::performDriftCorrection(), QProblemB::performDriftCorrection(), QProblemB::performRamping(), QProblem::performRamping(), QProblemB::performRatioTest(), QProblem::performStep(), rotate(), Bounds::rotate(), setupAll(), Bounds::setupAll(), SQProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPbounds(), QProblemB::setupAuxiliaryQPbounds(), QProblem::setupAuxiliaryWorkingSet(), QProblem::setupSubjectToType(), shift(), and Bounds::shift().
BooleanType SubjectTo::hasNoLower () const [inline, inherited]
Returns status of lower (constraints') bounds.
Returns:
BT_TRUE if there is no lower (constraints') bound on any variable.
References SubjectTo::noLower.
Referenced by QProblem::performStep(), QProblemB::performStep(), QProblemB::printProperties(), and QProblem::printProperties().
BooleanType SubjectTo::hasNoUpper () const [inline, inherited]
Returns status of upper bounds.
Returns:
BT_TRUE if there is no upper (constraints') bound on any variable.
References SubjectTo::noUpper.
Referenced by QProblem::performStep(), QProblemB::performStep(), QProblemB::printProperties(), and QProblem::printProperties().
returnValue Constraints::init (int _n = 0)
Initialises object with given number of constraints.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
_n Number of constraints.
Reimplemented from SubjectTo.
References active, clear(), inactive, Indexlist::init(), RET_INVALID_ARGUMENTS, and THROWERROR.
Referenced by Constraints(), QProblem::QProblem(), QProblem::reset(), SQProblem::setupAuxiliaryQP(), and QProblem::setupAuxiliaryQP().
returnValue Constraints::moveActiveToInactive (int number)
Moves index of a constraint from index list of active to that of inactive constraints.
Returns:
SUCCESSFUL_RETURN
RET_MOVING_CONSTRAINT_FAILED
Parameters:
number Number of constraint to become inactive.
References SubjectTo::addIndex(), getActive(), getInactive(), SubjectTo::n, SubjectTo::removeIndex(), RET_INDEX_OUT_OF_BOUNDS, RET_MOVING_BOUND_FAILED, ST_INACTIVE, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::removeConstraint().
returnValue Constraints::moveInactiveToActive (int number, SubjectToStatus _status)
Moves index of a constraint from index list of inactive to that of active constraints.
Returns:
SUCCESSFUL_RETURN
RET_MOVING_CONSTRAINT_FAILED
Parameters:
number Number of constraint to become active.
_status Status of constraint to become active.
References SubjectTo::addIndex(), getActive(), getInactive(), SubjectTo::n, SubjectTo::removeIndex(), RET_INDEX_OUT_OF_BOUNDS, RET_MOVING_BOUND_FAILED, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::addConstraint().
Constraints & Constraints::operator= (const Constraints & rhs)
Assignment operator (deep copy).
Parameters:
rhs Rhs object.
References clear(), and copy().
returnValue Constraints::print ()
Prints information on constraints object (in particular, lists of inactive and active constraints.
Returns:
SUCCESSFUL_RETURN
RET_INDEXLIST_CORRUPTED
References getActive(), getInactive(), getNAC(), getNIAC(), Indexlist::getNumberArray(), MAX_STRING_LENGTH, myPrintf(), SubjectTo::n, REFER_NAMESPACE_QPOASES, and SUCCESSFUL_RETURN.
returnValue SubjectTo::removeIndex (Indexlist *const indexlist, int removenumber) [protected, inherited]
Removes the index of a constraint or bound from index set.
Returns:
SUCCESSFUL_RETURN
RET_REMOVEINDEX_FAILED
RET_INVALID_ARGUMENTS
Parameters:
indexlist Index list from which the new index shall be removed.
removenumber Number of constraint or bound to be removed.
References Indexlist::removeNumber(), RET_INVALID_ARGUMENTS, RET_REMOVEINDEX_FAILED, ST_UNDEFINED, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by moveActiveToInactive(), Bounds::moveFixedToFree(), Bounds::moveFreeToFixed(), and moveInactiveToActive().
returnValue Constraints::rotate (int offset) [virtual]
Rotates forward type and status of all constraints by a given offset. This offset has to lie within the range [0,n]. Example for offset = 2:
rotate({c1,c2,c3,c4,c5,c6}) = {c3,c4,c5,c6,c1,c2}
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
RET_ROTATING_FAILED
Parameters:
offset Rotation offset within the range [0,n].
Implements SubjectTo.
References active, Indexlist::addNumber(), SubjectTo::getStatus(), SubjectTo::getType(), inactive, SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_ROTATING_FAILED, SubjectTo::setStatus(), SubjectTo::setType(), ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
void SubjectTo::setNoLower (BooleanType _status) [inline, inherited]
Sets status of lower (constraints') bounds.
Parameters:
_status Status of lower (constraints') bounds.
References SubjectTo::noLower.
Referenced by QProblemB::setupSubjectToType(), and QProblem::setupSubjectToType().
void SubjectTo::setNoUpper (BooleanType _status) [inline, inherited]
Sets status of upper (constraints') bounds.
Parameters:
_status Status of upper (constraints') bounds.
References SubjectTo::noUpper.
Referenced by QProblemB::setupSubjectToType(), and QProblem::setupSubjectToType().
returnValue SubjectTo::setStatus (int i, SubjectToStatus value) [inline, inherited]
Sets status of (constraints') bound.
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
Parameters:
i Number of (constraints') bound.
value Status of (constraints') bound.
References SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, SubjectTo::status, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::dropInfeasibles(), rotate(), Bounds::rotate(), SQProblem::setupAuxiliaryQP(), shift(), and Bounds::shift().
returnValue SubjectTo::setType (int i, SubjectToType value) [inline, inherited]
Sets type of (constraints') bound.
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
Parameters:
i Number of (constraints') bound.
value Type of (constraints') bound.
References SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, SUCCESSFUL_RETURN, THROWERROR, and SubjectTo::type.
Referenced by rotate(), Bounds::rotate(), QProblem::setA(), QProblem::setupAuxiliaryWorkingSet(), QProblemB::setupSubjectToType(), QProblem::setupSubjectToType(), shift(), and Bounds::shift().
returnValue Constraints::setupAll (SubjectToStatus _status) [protected]
Initially adds all numbers of new (i.e. not yet in the list) bounds to to the index set corresponding to the desired status; the order depends on the SujectToType of each index.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_CONSTRAINT_FAILED
Parameters:
_status Desired initial status for all bounds.
References SubjectTo::getType(), SubjectTo::n, RET_SETUP_CONSTRAINT_FAILED, setupConstraint(), ST_BOUNDED, ST_DISABLED, ST_EQUALITY, ST_UNBOUNDED, ST_UNKNOWN, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by setupAllInactive(), setupAllLower(), and setupAllUpper().
returnValue Constraints::setupAllInactive ()
Initially adds all enabled numbers of new (i.e. not yet in the list) constraints to to the index set of inactive constraints; the order depends on the SujectToType of each index. Only disabled constraints are added to index set of disabled constraints!
Returns:
SUCCESSFUL_RETURN
RET_SETUP_CONSTRAINT_FAILED
References setupAll(), and ST_INACTIVE.
Referenced by QProblem::hotstart(), SQProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQP(), and QProblem::solveInitialQP().
returnValue Constraints::setupAllLower ()
Initially adds all enabled numbers of new (i.e. not yet in the list) constraints to to the index set of active constraints (on their lower bounds); the order depends on the SujectToType of each index. Only disabled constraints are added to index set of disabled constraints!
Returns:
SUCCESSFUL_RETURN
RET_SETUP_CONSTRAINT_FAILED
References setupAll(), and ST_LOWER.
returnValue Constraints::setupAllUpper ()
Initially adds all enabled numbers of new (i.e. not yet in the list) constraints to to the index set of active constraints (on their upper bounds); the order depends on the SujectToType of each index. Only disabled constraints are added to index set of disabled constraints!
Returns:
SUCCESSFUL_RETURN
RET_SETUP_CONSTRAINT_FAILED
References setupAll(), and ST_UPPER.
returnValue Constraints::setupConstraint (int number, SubjectToStatus _status)
Initially adds number of a new (i.e. not yet in the list) constraint to a given index set.
Returns:
SUCCESSFUL_RETURN
RET_SETUP_CONSTRAINT_FAILED
RET_INDEX_OUT_OF_BOUNDS
RET_INVALID_ARGUMENTS
Parameters:
number Number of new constraint.
_status Status of new constraint.
References SubjectTo::addIndex(), getActive(), getInactive(), SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_INVALID_ARGUMENTS, RET_SETUP_CONSTRAINT_FAILED, ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
Referenced by QProblem::obtainAuxiliaryWorkingSet(), and setupAll().
returnValue Constraints::shift (int offset) [virtual]
Shifts forward type and status of all constraints by a given offset. This offset has to lie within the range [0,n/2] and has to be an integer divisor of the total number of constraints n. Type and status of the first <offset> constraints is thrown away, type and status of the last <offset> constraints is doubled, e.g. for offset = 2:
shift({c1,c2,c3,c4,c5,c6}) = {c3,c4,c5,c6,c5,c6}
Returns:
SUCCESSFUL_RETURN
RET_INDEX_OUT_OF_BOUNDS
RET_INVALID_ARGUMENTS
RET_SHIFTING_FAILED
Parameters:
offset Shift offset within the range [0,n/2] and integer divisor of n.
Implements SubjectTo.
References active, Indexlist::addNumber(), SubjectTo::getStatus(), SubjectTo::getType(), inactive, SubjectTo::n, RET_INDEX_OUT_OF_BOUNDS, RET_INVALID_ARGUMENTS, RET_SHIFTING_FAILED, SubjectTo::setStatus(), SubjectTo::setType(), ST_INACTIVE, ST_LOWER, ST_UPPER, SUCCESSFUL_RETURN, and THROWERROR.
returnValue SubjectTo::swapIndex (Indexlist *const indexlist, int number1, int number2) [protected, inherited]
Swaps the indices of two constraints or bounds within the index set.
Returns:
SUCCESSFUL_RETURN
RET_SWAPINDEX_FAILED
RET_INVALID_ARGUMENTS
Parameters:
indexlist Index list in which the indices shold be swapped.
number1 Number of first constraint or bound.
number2 Number of second constraint or bound.
References RET_INVALID_ARGUMENTS, RET_NOTHING_TO_DO, RET_SWAPINDEX_FAILED, SubjectTo::status, SUCCESSFUL_RETURN, Indexlist::swapNumbers(), THROWERROR, and THROWWARNING.
Referenced by Bounds::swapFree().
Member Data Documentation
Indexlist Constraints::active [protected]
Index list of active constraints.
Referenced by copy(), getActive(), getNAC(), init(), rotate(), and shift().
Indexlist Constraints::inactive [protected]
Index list of inactive constraints.
Referenced by copy(), getInactive(), getNIAC(), init(), rotate(), and shift().
int SubjectTo::n [protected, inherited]
Total number of constraints/bounds.
Referenced by SubjectTo::copy(), flipFixed(), Bounds::flipFixed(), getNC(), SubjectTo::getNumberOfType(), Bounds::getNV(), SubjectTo::getStatus(), SubjectTo::getType(), SubjectTo::init(), moveActiveToInactive(), Bounds::moveFixedToFree(), Bounds::moveFreeToFixed(), moveInactiveToActive(), print(), Bounds::print(), rotate(), Bounds::rotate(), SubjectTo::setStatus(), SubjectTo::setType(), setupAll(), Bounds::setupAll(), Bounds::setupBound(), setupConstraint(), shift(), Bounds::shift(), and Bounds::swapFree().
BooleanType SubjectTo::noLower [protected, inherited]
This flag indicates if there is no lower bound on any variable.
Referenced by SubjectTo::copy(), SubjectTo::hasNoLower(), SubjectTo::init(), and SubjectTo::setNoLower().
BooleanType SubjectTo::noUpper [protected, inherited]
This flag indicates if there is no upper bound on any variable.
Referenced by SubjectTo::copy(), SubjectTo::hasNoUpper(), SubjectTo::init(), and SubjectTo::setNoUpper().
SubjectToStatus* SubjectTo::status [protected, inherited]
Status of constraints/bounds.
Referenced by SubjectTo::addIndex(), SubjectTo::clear(), SubjectTo::copy(), flipFixed(), Bounds::flipFixed(), SubjectTo::getStatus(), SubjectTo::init(), SubjectTo::removeIndex(), SubjectTo::setStatus(), SubjectTo::SubjectTo(), and SubjectTo::swapIndex().
SubjectToType* SubjectTo::type [protected, inherited]
Type of constraints/bounds.
Referenced by SubjectTo::clear(), SubjectTo::copy(), SubjectTo::getNumberOfType(), SubjectTo::getType(), SubjectTo::init(), SubjectTo::setType(), and SubjectTo::SubjectTo().
The documentation for this class was generated from the following files:
include/qpOASES/Constraints.hpp
src/Constraints.cpp
include/qpOASES/Constraints.ipp