qpOASES: examples/example1a.cpp File Reference
examples/example1a.cpp File Reference
#include <qpOASES.hpp>
Functions
int main ()
Detailed Description
Author:
Hans Joachim Ferreau
Version:
3.0
Date:
2007-2014
Very simple example for testing qpOASES using the SQProblem class.
Function Documentation
int main ()
Example for qpOASES main function using the SQProblem class.
References g, QProblemB::getObjVal(), QProblemB::getPrimalSolution(), SQProblem::hotstart(), QProblem::init(), lb, lbA, real_t, ub, ubA, and USING_NAMESPACE_QPOASES.