qpOASES: MessageHandling Class Reference
MessageHandling Class Reference
Handles all kind of error messages, warnings and other information.
#include <MessageHandling.hpp>
Classes
struct ReturnValueList
Data structure for entries in global message list.
Public Member Functions
MessageHandling ()
MessageHandling (FILE *_outputFile)
MessageHandling (VisibilityStatus _errorVisibility, VisibilityStatus _warningVisibility, VisibilityStatus _infoVisibility)
MessageHandling (FILE *_outputFile, VisibilityStatus _errorVisibility, VisibilityStatus _warningVisibility, VisibilityStatus _infoVisibility)
MessageHandling (const MessageHandling &rhs)
~MessageHandling ()
MessageHandling & operator= (const MessageHandling &rhs)
returnValue throwError (returnValue Enumber, const char *additionaltext, const char *functionname, const char *filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus)
returnValue throwWarning (returnValue Wnumber, const char *additionaltext, const char *functionname, const char *filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus)
returnValue throwInfo (returnValue Inumber, const char *additionaltext, const char *functionname, const char *filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus)
returnValue reset ()
returnValue listAllMessages ()
VisibilityStatus getErrorVisibilityStatus () const
VisibilityStatus getWarningVisibilityStatus () const
VisibilityStatus getInfoVisibilityStatus () const
FILE * getOutputFile () const
int getErrorCount () const
void setErrorVisibilityStatus (VisibilityStatus _errorVisibility)
void setWarningVisibilityStatus (VisibilityStatus _warningVisibility)
void setInfoVisibilityStatus (VisibilityStatus _infoVisibility)
void setOutputFile (FILE *_outputFile)
returnValue setErrorCount (int _errorCount)
Static Public Member Functions
static const char * getErrorCodeMessage (const returnValue _returnValue)
Protected Member Functions
returnValue throwMessage (returnValue RETnumber, const char *additionaltext, const char *functionname, const char *filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus, const char *RETstring)
Protected Attributes
VisibilityStatus errorVisibility
VisibilityStatus warningVisibility
VisibilityStatus infoVisibility
FILE * outputFile
int errorCount
Detailed Description
This class handles all kinds of messages (errors, warnings, infos) initiated by qpOASES modules and stores the corresponding global preferences.
Author:
Hans Joachim Ferreau (thanks to Leonard Wirsching)
Version:
3.1
Date:
2007-2015
Constructor & Destructor Documentation
MessageHandling::MessageHandling ()
Default constructor.
References errorCount, errorVisibility, infoVisibility, outputFile, stdFile, VS_VISIBLE, and warningVisibility.
MessageHandling::MessageHandling (FILE * _outputFile)
Constructor which takes the desired output file.
Parameters:
_outputFile Output file.
References errorCount, errorVisibility, infoVisibility, outputFile, VS_VISIBLE, and warningVisibility.
MessageHandling::MessageHandling (VisibilityStatus _errorVisibility, VisibilityStatus _warningVisibility, VisibilityStatus _infoVisibility)
Constructor which takes the desired visibility states.
Parameters:
_errorVisibility Visibility status for error messages.
_warningVisibility Visibility status for warning messages.
_infoVisibility Visibility status for info messages.
References errorCount, errorVisibility, infoVisibility, outputFile, stdFile, and warningVisibility.
MessageHandling::MessageHandling (FILE * _outputFile, VisibilityStatus _errorVisibility, VisibilityStatus _warningVisibility, VisibilityStatus _infoVisibility)
Constructor which takes the desired output file and desired visibility states.
Parameters:
_outputFile Output file.
_errorVisibility Visibility status for error messages.
_warningVisibility Visibility status for warning messages.
_infoVisibility Visibility status for info messages.
References errorCount, errorVisibility, infoVisibility, outputFile, and warningVisibility.
MessageHandling::MessageHandling (const MessageHandling & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
References errorCount, errorVisibility, infoVisibility, outputFile, and warningVisibility.
MessageHandling::~MessageHandling ()
Destructor.
References outputFile.
Member Function Documentation
const char * MessageHandling::getErrorCodeMessage (const returnValue _returnValue) [static]
Provides message text corresponding to given returnValue.
Returns:
String containing message text.
References MessageHandling::ReturnValueList::data, and TERMINAL_LIST_ELEMENT.
int MessageHandling::getErrorCount () const [inline]
Returns error count value.
Returns:
Error count value.
References errorCount.
BEGIN_NAMESPACE_QPOASES VisibilityStatus MessageHandling::getErrorVisibilityStatus () const [inline]
Returns visibility status for error messages.
Returns:
Visibility status for error messages.
References errorVisibility.
VisibilityStatus MessageHandling::getInfoVisibilityStatus () const [inline]
Returns visibility status for info messages.
Returns:
Visibility status for info messages.
References infoVisibility.
Referenced by getSimpleStatus().
FILE * MessageHandling::getOutputFile () const [inline]
Returns pointer to output file.
Returns:
Pointer to output file.
References outputFile.
Referenced by myPrintf().
VisibilityStatus MessageHandling::getWarningVisibilityStatus () const [inline]
Returns visibility status for warning messages.
Returns:
Visibility status for warning messages.
References warningVisibility.
returnValue MessageHandling::listAllMessages ()
Prints a complete list of all messages to output file.
Returns:
SUCCESSFUL_RETURN
References MAX_STRING_LENGTH, myPrintf(), SUCCESSFUL_RETURN, and TERMINAL_LIST_ELEMENT.
MessageHandling & MessageHandling::operator= (const MessageHandling & rhs)
Assignment operator (deep copy).
Parameters:
rhs Rhs object.
References errorCount, errorVisibility, infoVisibility, outputFile, and warningVisibility.
returnValue MessageHandling::reset ()
Resets all preferences to default values.
Returns:
SUCCESSFUL_RETURN
References setErrorCount(), setErrorVisibilityStatus(), setInfoVisibilityStatus(), setOutputFile(), setWarningVisibilityStatus(), stdFile, SUCCESSFUL_RETURN, and VS_VISIBLE.
Referenced by QProblemB::QProblemB(), and QProblemB::~QProblemB().
returnValue MessageHandling::setErrorCount (int _errorCount) [inline]
Changes error count.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENT
Parameters:
_errorCount New error count value.
References errorCount, RET_INVALID_ARGUMENTS, and SUCCESSFUL_RETURN.
Referenced by getSimpleStatus(), and reset().
void MessageHandling::setErrorVisibilityStatus (VisibilityStatus _errorVisibility) [inline]
Changes visibility status for error messages.
Parameters:
_errorVisibility New visibility status for error messages.
References errorVisibility.
Referenced by reset(), and QProblemB::setPrintLevel().
void MessageHandling::setInfoVisibilityStatus (VisibilityStatus _infoVisibility) [inline]
Changes visibility status for info messages.
Parameters:
_infoVisibility New visibility status for info messages.
References infoVisibility.
Referenced by getSimpleStatus(), reset(), and QProblemB::setPrintLevel().
void MessageHandling::setOutputFile (FILE * _outputFile) [inline]
Changes output file for messages.
Parameters:
_outputFile New output file for messages.
References outputFile.
Referenced by reset().
void MessageHandling::setWarningVisibilityStatus (VisibilityStatus _warningVisibility) [inline]
Changes visibility status for warning messages.
Parameters:
_warningVisibility New visibility status for warning messages.
References warningVisibility.
Referenced by reset(), and QProblemB::setPrintLevel().
returnValue MessageHandling::throwError (returnValue Enumber, const char * additionaltext, const char * functionname, const char * filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus)
Prints an error message(a simplified macro THROWERROR is also provided).
Errors are definied as abnormal events which cause an immediate termination of the current (sub) function. Errors of a sub function should be commented by the calling function by means of a warning message (if this error does not cause an error of the calling function, either)!
Returns:
Error number returned by sub function call
Parameters:
Enumber Error number returned by sub function call.
additionaltext Additional error text (0, if none).
functionname Name of function which caused the error.
filename Name of file which caused the error.
linenumber Number of line which caused the error.incompatible binary file
localVisibilityStatus Determines (locally) if error message can be printed to stdFile. If GLOBAL visibility status of the message is set to VS_HIDDEN, no message is printed, anyway!
References __FILE__, __FUNC__, __LINE__, errorVisibility, RET_ERROR_UNDEFINED, SUCCESSFUL_RETURN, throwMessage(), and VS_VISIBLE.
Referenced by readFromFile(), throwInfo(), throwMessage(), throwWarning(), and writeIntoFile().
returnValue MessageHandling::throwInfo (returnValue Inumber, const char * additionaltext, const char * functionname, const char * filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus)
Prints a info message (a simplified macro THROWINFO is also provided).
Returns:
Info number returned by sub function call
Parameters:
Inumber Info number returned by sub function call.
additionaltext Additional warning text (0, if none).
functionname Name of function which submitted the info.
filename Name of file which submitted the info.
linenumber Number of line which submitted the info.
localVisibilityStatus Determines (locally) if info message can be printed to stdFile. If GLOBAL visibility status of the message is set to VS_HIDDEN, no message is printed, anyway!
References __FILE__, __FUNC__, __LINE__, infoVisibility, RET_INFO_UNDEFINED, SUCCESSFUL_RETURN, throwError(), throwMessage(), and VS_VISIBLE.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), QProblem::changeActiveSet(), QProblemB::changeActiveSet(), QProblem::performStep(), QProblemB::performStep(), QProblem::solveQP(), and QProblemB::solveQP().
returnValue MessageHandling::throwMessage (returnValue RETnumber, const char * additionaltext, const char * functionname, const char * filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus, const char * RETstring) [protected]
Prints a info message to stdFile (auxiliary function).
Returns:
Error/warning/info number returned by sub function call
Parameters:
RETnumber Error/warning/info number returned by sub function call.
additionaltext Additional warning text (0, if none).
functionname Name of function which caused the error/warning/info.
filename Name of file which caused the error/warning/info.
linenumber Number of line which caused the error/warning/info.
localVisibilityStatus Determines (locally) if info message can be printed to stdFile. If GLOBAL visibility status of the message is set to VS_HIDDEN, no message is printed, anyway!
RETstring Leading string of error/warning/info message.
References __FILE__, __FUNC__, __LINE__, errorCount, MAX_STRING_LENGTH, myPrintf(), RET_EWI_UNDEFINED, TERMINAL_LIST_ELEMENT, throwError(), and VS_VISIBLE.
Referenced by throwError(), throwInfo(), and throwWarning().
returnValue MessageHandling::throwWarning (returnValue Wnumber, const char * additionaltext, const char * functionname, const char * filename, const unsigned long linenumber, VisibilityStatus localVisibilityStatus)
Prints a warning message (a simplified macro THROWWARNING is also provided). Warnings are definied as abnormal events which does NOT cause an immediate termination of the current (sub) function.
Returns:
Warning number returned by sub function call
Parameters:
Wnumber Warning number returned by sub function call.
additionaltext Additional warning text (0, if none).
functionname Name of function which caused the warning.
filename Name of file which caused the warning.
linenumber Number of line which caused the warning.
localVisibilityStatus Determines (locally) if warning message can be printed to stdFile. If GLOBAL visibility status of the message is set to VS_HIDDEN, no message is printed, anyway!
References __FILE__, __FUNC__, __LINE__, RET_WARNING_UNDEFINED, SUCCESSFUL_RETURN, throwError(), throwMessage(), VS_VISIBLE, and warningVisibility.
Referenced by QProblem::performStep(), QProblemB::performStep(), QProblem::solveQP(), and QProblemB::solveQP().
Member Data Documentation
int MessageHandling::errorCount [protected]
Counts number of errors (for nicer output only).
Referenced by getErrorCount(), MessageHandling(), operator=(), setErrorCount(), and throwMessage().
VisibilityStatus MessageHandling::errorVisibility [protected]
Error messages visible?
Referenced by getErrorVisibilityStatus(), MessageHandling(), operator=(), setErrorVisibilityStatus(), and throwError().
VisibilityStatus MessageHandling::infoVisibility [protected]
Info messages visible?
Referenced by getInfoVisibilityStatus(), MessageHandling(), operator=(), setInfoVisibilityStatus(), and throwInfo().
FILE* MessageHandling::outputFile [protected]
Output file for messages.
Referenced by getOutputFile(), MessageHandling(), operator=(), setOutputFile(), and ~MessageHandling().
VisibilityStatus MessageHandling::warningVisibility [protected]
Warning messages visible?
Referenced by getWarningVisibilityStatus(), MessageHandling(), operator=(), setWarningVisibilityStatus(), and throwWarning().
The documentation for this class was generated from the following files:
include/qpOASES/MessageHandling.hpp
src/MessageHandling.cpp
include/qpOASES/MessageHandling.ipp