qpOASES: Flipper Class Reference
Flipper Class Reference
Auxiliary class for storing a copy of the current matrix factorisations.
#include <Flipper.hpp>
Public Member Functions
Flipper ()
Flipper (unsigned int _nV, unsigned int _nC=0)
Flipper (const Flipper &rhs)
~Flipper ()
Flipper & operator= (const Flipper &rhs)
returnValue init (unsigned int _nV=0, unsigned int _nC=0)
returnValue get (Bounds *const _bounds, real_t *const R, Constraints *const _constraints=0, real_t *const _Q=0, real_t *const _T=0) const
returnValue set (const Bounds *const _bounds, const real_t *const _R, const Constraints *const _constraints=0, const real_t *const _Q=0, const real_t *const _T=0)
Protected Member Functions
returnValue clear ()
returnValue copy (const Flipper &rhs)
unsigned int getDimT () const
Protected Attributes
unsigned int nV
unsigned int nC
Bounds bounds
Constraints constraints
real_t * R
real_t * Q
real_t * T
Friends
class QProblemB
class QProblem
Detailed Description
This auxiliary class stores a copy of the current matrix factorisations. It is used by the classe QProblemB and QProblem in case flipping bounds are enabled.
Author:
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version:
3.1
Date:
2007-2015
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES Flipper::Flipper ()
Default constructor.
References init(), Q, R, and T.
Flipper::Flipper (unsigned int _nV, unsigned int _nC = 0)
Constructor which takes the number of bounds and constraints.
Parameters:
_nV Number of bounds.
_nC Number of constraints.
References init(), Q, R, and T.
Flipper::Flipper (const Flipper & rhs)
Copy constructor (deep copy).
Parameters:
rhs Rhs object.
References copy(), Q, R, and T.
Flipper::~Flipper ()
Destructor.
References clear().
Member Function Documentation
returnValue Flipper::clear () [protected]
Frees all allocated memory.
Returns:
SUCCESSFUL_RETURN
References Q, R, SUCCESSFUL_RETURN, and T.
Referenced by init(), operator=(), and ~Flipper().
returnValue Flipper::copy (const Flipper & rhs) [protected]
Copies all members from given rhs object.
Returns:
SUCCESSFUL_RETURN
Parameters:
rhs Rhs object.
References bounds, constraints, Q, R, and T.
Referenced by Flipper(), and operator=().
returnValue Flipper::get (Bounds *const _bounds, real_t *const R, Constraints *const _constraints = 0, real_t *const _Q = 0, real_t *const _T = 0) const
Copies current values to non-null arguments (assumed to be allocated with consistent size).
Returns:
SUCCESSFUL_RETURN
Parameters:
_bounds Pointer to new bounds.
R New matrix R.
_constraints Pointer to new constraints.
_Q New matrix Q.
_T New matrix T.
References bounds, constraints, getDimT(), nV, Q, R, real_t, SUCCESSFUL_RETURN, and T.
Referenced by QProblem::removeBound(), QProblemB::removeBound(), and QProblem::removeConstraint().
unsigned int Flipper::getDimT () const [protected]
Returns dimension of matrix T.
Returns:
Dimension of matrix T.
References nC, and nV.
Referenced by get(), and set().
returnValue Flipper::init (unsigned int _nV = 0, unsigned int _nC = 0)
Initialises object with given number of bounds and constraints.
Returns:
SUCCESSFUL_RETURN
RET_INVALID_ARGUMENTS
Parameters:
_nV Number of bounds.
_nC Number of constraints.
References clear(), nC, nV, and SUCCESSFUL_RETURN.
Referenced by Flipper(), QProblem::QProblem(), QProblemB::QProblemB(), QProblem::reset(), and QProblemB::reset().
Flipper & Flipper::operator= (const Flipper & rhs)
Assignment operator (deep copy).
Parameters:
rhs Rhs object.
References clear(), and copy().
returnValue Flipper::set (const Bounds *const _bounds, const real_t *const _R, const Constraints *const _constraints = 0, const real_t *const _Q = 0, const real_t *const _T = 0)
Assigns new values to non-null arguments.
Returns:
SUCCESSFUL_RETURN
Parameters:
_bounds Pointer to new bounds.
_R New matrix R.
_constraints Pointer to new constraints.
_Q New matrix Q.
_T New matrix T.
References bounds, constraints, getDimT(), nV, Q, R, real_t, SUCCESSFUL_RETURN, and T.
Referenced by QProblem::removeBound(), QProblemB::removeBound(), and QProblem::removeConstraint().
Member Data Documentation
Bounds Flipper::bounds [protected]
Data structure for problem's bounds.
Referenced by copy(), get(), and set().
Constraints Flipper::constraints [protected]
Data structure for problem's constraints.
Referenced by copy(), get(), and set().
unsigned int Flipper::nC [protected]
Number of constraints.
Referenced by getDimT(), and init().
unsigned int Flipper::nV [protected]
Number of variables.
Referenced by get(), getDimT(), init(), and set().
real_t* Flipper::Q [protected]
Orthonormal quadratic matrix, A = [0 T]*Q'.
Referenced by clear(), copy(), Flipper(), get(), and set().
real_t* Flipper::R [protected]
Cholesky factor of H (i.e. H = R^T*R).
Referenced by clear(), copy(), Flipper(), get(), and set().
real_t* Flipper::T [protected]
Reverse triangular matrix, A = [0 T]*Q'.
Referenced by clear(), copy(), Flipper(), get(), and set().
The documentation for this class was generated from the following files:
include/qpOASES/Flipper.hpp
src/Flipper.cpp