qpOASES: examples/example1b.cpp File Reference
examples/example1b.cpp File Reference
#include <qpOASES.hpp>
Functions
int main ()
Detailed Description
Author:
Hans Joachim Ferreau
Version:
3.1
Date:
2007-2015
Very simple example for testing qpOASES using the QProblemB class.
Function Documentation
int main ()
Example for qpOASES main function using the QProblemB class.
References Options::enableCholeskyRefactorisation, g, QProblemB::getObjVal(), QProblemB::getPrimalSolution(), QProblemB::hotstart(), QProblemB::init(), Options::initialStatusBounds, lb, Options::numRefinementSteps, real_t, QProblemB::setOptions(), ST_INACTIVE, ub, and USING_NAMESPACE_QPOASES.