qpOASES: examples/example4.cpp File Reference
examples/example4.cpp File Reference
#include <stdlib.h>
#include <qpOASES.hpp>
#include "example4CP.cpp"
Functions
int main ()
Detailed Description
Author:
Hans Joachim Ferreau
Version:
3.1
Date:
2009-2015
Very simple example for testing qpOASES (using the possibility to specify user-defined constraint product function).
Function Documentation
int main ()
Example for qpOASES main function using the possibility to specify user-defined constraint product function.
References g, QProblemB::getObjVal(), QProblemB::getPrimalSolution(), QProblem::hotstart(), QProblem::init(), lbA, PL_NONE, real_t, QProblem::setConstraintProduct(), QProblemB::setPrintLevel(), and USING_NAMESPACE_QPOASES.