qpOASES: examples/example3.cpp File Reference
examples/example3.cpp File Reference
#include <qpOASES.hpp>
Functions
int main ()
Detailed Description
Author:
Hans Joachim Ferreau
Version:
3.1
Date:
2008-2015
Example demonstrating usage of qpOASES for solving a QP sequence of the Online QP Benchmark Collection. In order to run it, you have to download "Example 02" from from http://www.qpOASES.org/onlineQP/ and store it into the directory bin/chain80w/.
Function Documentation
int main ()
Example for qpOASES main function using the OQP interface.
References BT_FALSE, myPrintf(), PL_NONE, Options::printLevel, real_t, runOQPbenchmark(), Options::setToMPC(), SUCCESSFUL_RETURN, and USING_NAMESPACE_QPOASES.